# 训练历史存档

冻结时点：2026-10-02。2026-10-03重构时从原档案迁出。

本文件保存旧版叙述以供溯源，不代表当前训练处方或已验证结论。正文中的旧章节号均指冻结版本。第五章已按用户要求删除，不在此复制。逐日数值仍以《训练数据集.json》为准。

运动员卡

孙笑川 · 22岁（2026年4月2日生）· 178cm · 约60kg（晨起空腹读数在57.9-61.8kg间波动，未定基准，见训练数据集）

一页看完：我是谁、现在什么水平、身上有什么限制、这周该干什么。内容变动不频繁，每次能力测试或伤病状态变化时更新。

##   一    当前能力

长跑为主项。半马 PB 1:28:05（2026年5月17日安顺，4:09/km @164bpm，净成绩）。5km PB 17:40（2025年11月，约80%主观强度，严重低估，全力预测区间 16:40–17:20）。VO2Max 估算 51。日常有氧配速 6:10–6:30/km @135bpm 左右，单次 9–10km。

力量为维持性质，非主攻。当前三项PB（均为含20kg奥杆的总重）：硬拉70kg×3、深蹲60kg×5、卧推50kg×6（9月11日）。相对力量：硬拉约1.16倍体重，深蹲约0.99倍，卧推约0.83倍。自重引体2次，为不受助力档位干扰的能力锚点。

##   二    当前限制

| 部位 | 起始 | 当前状态 | 仍在执行的限制 | 下一步／解除条件 |
|---|---|---|---|---|
| 右肩 | 8/20 | 三次功能性阴性记录后大部解除。9/2肩胸课容量6416kg，重新引入蝴蝶机与过顶推举全程零诱发；9/9正握内旋位（引体＋下拉47kg新高两组）仍无感；9/11肩胸课容量6671kg、卧推50kg×6，用户报告感觉不错、未报告肩部诱发。原症状：外展20–30度前屈痛、晨起明显、旋前诱发旋后不痛、被动不痛，机制推断指向肩峰下间隙，未经查体确认。 | 承重闭链动作（平板支撑、健腹轮）暂停。面拉列为优先动作。 | 承重闭链需单独测试后才能撤——8/26 平板支撑是唯一确凿阳性条件，此后从未复测。查体建议维持：姿势为未处理的上游变量。 |
| 左膝 | 8/24 | 9/8 命中就医触发条件。五个点：8/24 硬拉 70kg 撑不住无痛、9/5 深蹲 55kg 伸膝瞬间痛、9/5 降 50kg 无异常、9/6（React）跑步全程无感觉、9/8 与 9/10（均 Adios 9）跑步过程中有感觉、跑完消失。症状形态两次一致：低强度或未热开时有，提速或热开后消失，方向与负荷驱动的机械性机制相反。 | 硬拉暂缓冲击新 PB。 | 就医触发条件已成立（跑步中出现），是否就医由用户决定。待测变量：鞋——两次有症状均为 Adios 9，唯一无症状为 React，强度候选已被排除；下次跑步穿 React 即可测。 |
| 颈段 | 9/2 | 观察项。伏案约 10 小时后于傍晚出现。三个来源不可分离——久坐前倾静态负荷、当日 12 组涉肩胛上提/后缩动作、8/31 背日残留；不分离的理由是三者处置相同。 | 无动作限制。 | 处理：伏案每 25–30 分钟起立；屏幕抬至视线水平；执行模板中长期未落地的「收下巴 2×10、停 5 秒」。若伴上肢麻木、放射痛或握力下降，属另一类问题，不以观察处置。 |
| 上呼吸道 | 9/10 | 9/10短暂出现体感一般、隐约吞咽痛，9/11恢复正常，仅持续一日，未证实感染。同期Elite低谷继续加深至z=−3.62，但症状与HRV未同向，感染候选降级。 | 无。 | 本轮关闭；若吞咽痛、鼻塞、咳嗽、发热或明显乏力重新出现，再按非训练因素重新开启。 |
| 肛裂 | 8/26 | 8/30 大幅好转，已解除。机械性擦伤非感染性，每晚睡前温水坐浴，四天内明显好转，恢复期饮食持续含辣未作限制。 | 已撤销。 | 若排便痛或出血再现则重新启用腹内压相关限制。 |

左侧信号线（观察项，未确证）：左髌腱弹响、左股外侧肌单侧酸、PAP 冷启动时左侧髌骨连接处不适、平衡曾偏左 50.5%，以及 8/24 硬拉 70kg 末组的左膝支撑不足。前四条为被动观察，末条为负荷下的功能性表现。可用保加利亚分腿蹲双侧力竭次数差作为不对称的测试工具。该线与上表「左膝」为同一条，上表记当前处置，此处记构成条目。

##   三    当前处方

训练：每周 4–6 次有氧（9–10km，心率 135 上下），力量按维持计划四分化轮转，每周至少安排一个完全休息日。加重量节奏每次 2.5kg，不按主观储备速度推进——神经适应领先于肌腱、韧带与骨的适应，当前正处于该时间差的高点。

营养：蛋白 100–115g/日，跑步日 2900–3100kcal，力量日同区间，完全休息日蛋白不下调、碳水可降至 250–300g。训练后补给按日型取默认剂量：跑步日 0.5 勺，力量日 1.5 勺完整配方。

监控：晨起流程为起床→排尿→称重→测 Elite HRV，全程不进食不饮水不洗澡。常态带 77.3–93.2ms（锁定参考期 2026-08-08 至 08-23）。日常训练决策以体感为准，客观数据仅在与体感明显分离时提示。

优先级　2026年12月研究生入学考试（体育管理方向）为主线。训练的作用是维持状态以保障学习，任何以牺牲学习时间或增加受伤风险为代价的训练安排都不成立。

##   1    基本身体信息

| 年龄 | 22岁（2026年4月2日生日） |
|---|---|
| 性别 | 男 |
| 身高 | 178 cm（2026-08-25 用户确认，原记179cm为误记） |
| 体重 | 基准未定（晨起空腹读数在 57.9-61.8kg 间波动，极差 3.95kg）。2026-08-31 修正：8/26 曾把单次读数 57.85kg 定为档案基准口径，次日 61.80kg 即将其推翻，该基准作废——单次读数不能当基准，需累积两周后取滚动均值再定。口径本身有效：晨起空腹、排尿后、光脚硬地、未进食未饮水未洗澡，每日仅测一次。8/25 的 61.05kg 为 18:31 非标准时点值，与晨起值相差 3.20kg，拆分核实后差额几乎全部为体水分（-2.38kg）与去脂体重（-2.90kg），非脂肪变化，仅作口径对照保留 |
| 体型 | 偏瘦长。2026-08-31 修正：原记「外胚型（Ectomorph）——新陈代谢快，热量盈余困难」，体型三分法不是可测量的代谢变量，用它解释吃不胖属循环论证，且被后续引用为膳食策略的依据。可留存的事实只有两条：体重长期在 58-62kg 区间；8 月 26 个有记录日的实测均值 2705kcal 下体重无明确上升趋势。真实维持热量须按晨起体重趋势实测，不由体型推定 |

营养策略核心：3 顿正餐 ＋ 每日一个固定加餐模块（训练日追加，见§9），训练后即时补充混合补给，晚餐蛋白质目标 35-40g 以上、20:00 前完成。2026-08-31 由「高频次进食（目标5-6餐）」改写，原依据（单餐吸收上限）不成立。

### 1.1 运动能力基础

| 主要专项 | 长跑 |
|---|---|
| 训练方法 | 数据驱动，记录HRV、配速、功率数据优化训练效果 |
| 5km PB | 17分40秒（⚠ 严重低估：2025年11月，Kinvara 13，约80%主观强度，跑完无疲劳感；全力预测区间16:40-17:20；测试推迟至比赛后） |
| 有氧基准（半年前） | 心率139bpm区间维持5:00/km配速，持续约两小时 |

赛后状态（5月18日）：5月17日安顺半马：净成绩1:28:05（4:09/km@164bpm），Sub-1:30完成，超出赛前Sub-1:35目标整整6分钟。触地215ms回归绝对巅峰期，心率回落27bpm，步频184spm，左右平衡50.2/49.8%，功率267W（峰值371W）。糖原管理：三颗能量胶方案执行完整，全程无撞墙。VO2Max估算53，心率回落稳定在27-33bpm区间。赛后39小时恢复时间。

2025年因学业中断系统训练。2026年1月起恢复系统训练，4月起有氧指标持续向巅峰期收敛。

##   2    历史能力坐标系

| 指标 | 裸跑半马 | 巅峰期日常 | 首次正式半马（5月17日） |
|---|---|---|---|
| 距离 | 21.13 km | 21.12 km | 21.0975 km（首次正式赛事） |
| 平均配速 | 4:53/km | 5:05/km | 4:09/km（净时1:28:05） |
| 平均心率 | 161 bpm | 150 bpm | 164 bpm |
| 心率回落(1min) | 17 bpm | 30 bpm | 27 bpm |
| 触地时间 | 未记录 | 215 ms | 215 ms（回归巅峰） |
| VO2Max估算 | 55 | 55 | 54 |

坐标系解读：发展弧线完整闭环：裸跑半马1:43:12（4:53/km@161bpm，心率回落17bpm）→训练中断→2026年1月重建→4月有氧指标全面收敛→5月17日首次正式半马1:28:05（4:09/km@164bpm，触地215ms回归巅峰，心率回落27bpm）。Sub-1:30完成，较裸跑基线提速14分钟，较赛前目标超出6分钟。2023年大一高强度参考：三次5km全力跑（安顺海拔1300m，4:32-4:42/km@164-174bpm），手表VO2Max稳定读数63——高心率采样使算法外推距离短、估算更可靠；若校正海拔因素，平原真实值可能更高。短距离速度推算（基于Riegel外推+VDOT 55-57交叉验证）：1000m约2:55-3:10，800m约2:15-2:30。参照2022年体考800m实测2'18"（当时以乒乓球为主、跑步训练量远不如现在），落在推算区间内。注意：训练体系长期耐力导向，无氧速度素质基本未开发（"出厂设置"），速度上限被系统性低估，未来正式测试大概率突破。绝对速度峰值窗口25-30岁，22岁神经肌肉可塑性仍高，转专项后有明确提升空间。

##   3    装备信息

### 三层鞋型分级系统

| 层级 | 鞋型 | 落差 | 使用场景 |
|---|---|---|---|
| 第一层（主力） | Adidas Adios 9 | 6mm | 主力训练鞋：全距离有氧跑、LSD、恢复跑、乳酸阈值测试高速段。Lightstrike 2.0中底+Energyrods+Continental马牌大底（暴雨湿地零打滑验证）。6月29日取代已退役的Kinvara 13。适应进度：约70-80%，7月5日跑后腿部反应几乎消失，但7月6日回贵阳9.93km后双脚足底仍有涨感——适应尚未完全脱离期，距离略增+海拔环境切换仍会诱发反应，未达稳定加量门槛。力学较Kinvara显著激进，Energyrods刚性传导对下肢动力链要求高，适应期连续跑量后曾出现股四头DOMS、足底酸胀、右脚足弓撕裂感、左小腿紧绷；石板路铺装与Energyrods刚性叠加可引发足底撕裂痛（柏油路无症状），虹山湖石板路段需降速或绕行。适应策略参照结缔组织慢变量特性（见§7），升量以连续多天晨起无症状为准，不依赖单日无痛 |
| 第二层（备选） | Nike React Infinity Run | 8-9mm | 保护性备选：伤病/生病时使用；Kinvara LSD距离上限未达标时承接超出部分。日常训练不再使用（泡棉回弹率65-70%·较飞电6C PEBA的85-90%体感拖沓·单只重280-290g较飞电重70-80g） |
| 第三层（竞赛） | 李宁飞电6C Challenger | 10mm | 比赛日、关键节奏跑；碳板弹射+减量后超量恢复叠加 |

飞电6C规格：超䨻PEBA+䨻双密度中底，T700全掌碳板，210-214g，前掌28mm/后跟38mm/落差10mm，有效配速3:30-5:30/km。

飞电6C神经自动化状态（5月8日）：✅ 完全完成。注意力已从小腿/跟腱对碳板的支撑转移至臀部送髋——运动程序已写入小脑/基底核长期记忆，前额叶皮层不再需要分配监控资源。连续5次以上穿着后小腿紧胀感完全消失，跑完零感觉。比赛当天全部认知资源可专注于配速感知、补给和体能管理。

##   4    生理监控系统

### 设备

| 设备 | 类型 | 采集内容 | 使用时段 | 精度／说明 |
|---|---|---|---|---|
| 华为 Watch 5 | 智能手表 | 夜间睡眠 HRV／心率 | 夜间睡眠时段 | 整晚滚动均值（副交感主导） |
| 华为运动健康 App | 配套应用 | Watch 5 数据记录／可视化 | — | 与 Watch 5 配合使用 |
| Polar H10 | 心率胸带 | ECG 直采 R-R 间期 | 晨起静息 ＋ 训练时段 | 精度 1–2ms；CR2025 电池，不用于夜间佩戴（7/4 到手）。佩戴方案（胸围仅72cm偏小）：绑带位置上移至胸骨下缘自然收窄处+调松近1cm+电极片打湿；过紧会压迫胸廓致岔气+胸大肌下缘胀痛+放射肩痛（7/8实测，松开即消失）。响应速度秒级远超腕式光电，抗雨水/汗水干扰 |
| Elite HRV App | 配套应用 | 导出原始 RR 间期数据 | — | zip／txt 格式 |

双设备分工　华为 Watch 5 负责夜间睡眠时段，Polar H10 负责晨起静息 ＋ 训练时段；两者共同服务于当天晨起 RPE 体感，最终由 RPE 仲裁当天学习与训练计划。

晨起测量标准协议　醒来 → 如厕后 → 平躺 → 测量 5 分钟（固定状态排除体位／膀胱干扰，保证数据可比性）。

重要区分：华为夜间睡眠HRV（副交感主导，整晚滚动均值）与Polar/Elite HRV晨起静息RMSSD（清醒静息即时值）是两个不同变量，数值不可直接横向换算，只能各自追踪趋势线再看两者是否同步。白天实时HRV波动60-110ms，仅作瞬时参考，不用于训练决策。

### 功率基线——飞电6C（碳板竞速鞋）

碳板弹性回收使功率读数系统性偏低约60-80W，不可与React横向比较。

| 功率区间 | 体感 | 心率 | 生理区间 |
|---|---|---|---|
| ~190W | 轻松，可长时间对话 | ~145bpm | 有氧基础区下限 |
| 200-210W | 轻微疲劳，呼吸变急 | ~155bpm | 有氧基础区上限 |
| ≥220W | 中高强度，乳酸堆积 | ≥165bpm | 乳酸阈值区 |

### 功率基线——React（训练鞋）

温度是功率的系统性修正变量：凉爽天气（25°C以下）有氧区下限约230-240W；温暖天气（28°C以上）约260W。坡道数据因下坡离心收缩导致功率被系统性低估，不可与平路基线比较，坡道训练以心率和RPE为锚点。下方强度分区表系安顺期（~1350m）或更早建立；海拔已降至贵阳~1050m，不可直接套用，贵阳期基线须重新累积，逐次数据点见另表。

| 功率区间 | 体感 | 心率 | 生理区间 |
|---|---|---|---|
| ~260W | 轻松，可长时间对话 | ~145bpm | 有氧基础区下限 |
| 270-285W | 轻微疲劳，呼吸变急 | ~155bpm | 有氧基础区上限 |
| ≥295W | 中高强度，乳酸堆积 | ≥165bpm | 乳酸阈值区 |

| 日期 | 平均功率(峰值) | 均心率 | 配速 | 触地 | 备注 |
|---|---|---|---|---|---|
| 贵阳期 海拔~1050m（数据点累积中，n=2） |  |  |  |  |  |
| 8/10 | 218W(296W) | 135 | 6'36" | 237ms | 步频178spm；爬升48m／降47.2m |
| 8/13 | 175W(314W) | 138 | 6'31" | 237ms | 步频179spm；腿日次日，左股外侧肌单侧DOMS |

两点相差43W而跑姿指标几乎重合（触地237／237ms、步频178／179spm、垂直振幅9.1／9.2cm），且8/13配速反而更快（6'31" vs 6'36"）——"技术动作或跑步经济性改变"的解释因此不成立：经济性改善应表现为同功率下更快，而非更快却功率低20%；华为跑步功率本身即由速度、步频、触地与垂直振幅估算，输入几乎相同则输出不应相差如此之大。

当前最可能的解释为路线坡度差异（8/10爬升48m／降47.2m，8/13海拔跨度约20m），与本节既有的坡道规则同源：上坡段推高平均功率、下坡段压低。处理方式：两点均作独立数据点留存并标注坡度待确认，n=2且相差43W尚不足以建立贵阳期基线；亦不得用其中任一点去推翻"React较Adios 9同心率高约50W"这一安顺期结论——该偏移在贵阳期尚未验证。需再积累2-3条平路数据。

### 功率基线——Adios 9（主力训练鞋·建立中）

Lightstrike 2.0+Energyrods存在弹性回弹（幅度介于React与飞电6C之间），功率读数较React同心率低约50W。无碳板但有Energyrods刚性推进，功率读数不可与React横向比较。海拔为系统性背景变量：7月6日起由安顺~1350m回贵阳~1050m，两期数据分列，不得跨期比较。（本节数据于8月9日补齐至8月9日，此前停留在7月6日；表内数据点均为Adios 9有氧课）

| 日期 | 平均功率(峰值) | 均心率 | 配速 | 触地 | 备注 |
|---|---|---|---|---|---|
| 安顺期 海拔~1350m（6/29-7/5） |  |  |  |  |  |
| 6/29 | 210W | 154 | 5'17" | — | 雨天 |
| 6/30 | 177W | 145 | 6'20" | — | 晴天 |
| 7/1 | 169W | 141 | 6'36" | — |  |
| 7/2 | 173W | 140 | 6'26" | — |  |
| 7/5 | 176W | 144 | 6'23" | — | 安顺期有氧区169-177W，触地226-235ms |
| 贵阳期 海拔~1050m（7/6起） |  |  |  |  |  |
| 7/6 | 169W | 141 | 6'38" | — | 回贵阳首课，海拔变量分期起点 |
| 7/29 | 174W(312W) | 141 | 6'32" | 237ms | 步频179spm；感冒恢复期 |
| 7/30 | 176W(365W) | 141 | 6'21" | 233ms | 峰值含途中冲厕所冲刺，不作趋势 |
| 8/6 | 182W(331W) | 138 | 6'10" | 236ms | 22°C小雨，温度红利异常点 |
| 8/8 | 179W(345W) | 140 | 6'23" | 236ms | 能量赤字日，输出下降主要体现在配速 |
| 8/9 | 187W(386W) | 140 | 5'59" | 234ms | 贵阳期新高；步频179spm，峰值含途中冲厕所冲刺 |
| 8/15 | 180W(323W) | 134 | 6'14" | 236ms | 8月15日课，原应入表而漏记，8/16补录；爬升66.5m，10.09km，步频179spm |
| 8/16 | 186W(299W) | 135 | 6'05" | 231ms | 触地为序列最低；爬升54.0m，明显负分割，均值配对偏乐观，不作锚点样本 |
| 8/18 | 235W(327W) | 136 | 6'14" | 236ms | 功率读数存疑，不作有效样本，见表下说明；爬升57.5m，负分割 |
| 8/20 | 275W(484W) | 135 | 6'11" | 234ms | 功率列已整体降级为不解读，见表下说明；爬升47.3m |

功率列现状（8月20日决定）：功率数值照常录入附录C以保留原始记录，但不再用于任何判断——不建锚点、不作鞋款比较、不进效率推演。依据是8/16、8/18、8/20三节课的「热身段／主课段」读数为175/186W、175/235W、271/275W，呈阶跃而非随机噪声，指向设备或算法层面的系统性变化，非路线或跑法所致；8/20当日另有最快配速2'41"/km、峰值功率484W、峰值心率180bpm等多个不可信读数佐证（当日均心率135、均配速6'11"）。锚点修订条目同日关闭。关闭理由不是问题已解决，而是该指标对当前核心目标（12月考研）没有贡献，而维持它需要主动配合（刻意安排匀速课）。若将来功率读数自行恢复正常且本人主动提出，再行重启。

关闭前已确立、至今仍有效的读数规则：① 同心率下配速与功率可以解耦，功率不可单独用作输出水平的充分指标——8/8的179W@140bpm落在当时锚点区间上沿，而当日判定为真实输出下降，下降主要体现在配速（6'23" vs 8/6的6'10"）而非功率；8/9提供反向印证：同为均心率140bpm，配速快24秒/km时功率同步由179W升至187W，说明解耦发生在小幅波动区间内，输出变化达到一定幅度时功率仍会跟随，二者需并读而非择一。② 8/6为温度红利异常点，不作常温基线：心率最低（138bpm）而功率最高（182W）、配速最快（6'10"），须按§7"阴雨降温段同努力约快1分钟/km"的既有修正读取。③ 峰值功率不作趋势指标：312/365/331/345/386W波动大且受偶发冲刺污染（7/30的365W与8/9的386W均来自途中冲向厕所的冲刺）。④ 负分割课不可用于定锚点：心率对功率变化存在滞后，后段高功率配的是仍在爬升的心率，均功率/均心率这一配对会被系统性地美化。

触地时间的未解释项（留存）：贵阳期233-237ms，略长于安顺期的226-235ms，方向与"效率提升"相反。但安顺期区间含6/29的5'17"快课，配速为混杂因素，两期在此项上不具可比性，暂不归因，待贵阳期出现同等配速的课再对照。

数据缺口（登记，不要求回补）：8/1（9.26km）与8/4（9.48km·59:16·6'15"@137bpm）两课未记录功率值；病程期的7/19、7/20、7/23、7/25四课同样缺功率记录。功率列已停止解读，此处仅作登记。

### 个人生理基线

| 指标 | 个人范围 | 最新观测值 | 备注 |
|---|---|---|---|
| 夜间HRV（睡眠） | 当前设备个人区间83–119 ms（10月2日；历史漂移见备注） | 97ms（10月2日，与10月1日相同，位于设备个人区间）。逐日序列见《训练数据集》，本栏只记最新值与需要文字说明的极值。历史极值：117ms（8/1首次，9/1、9/3再现，为迄今最高）；32ms（6/27，谷值，母亲手术心理应激＋间歇延迟恢复＋首夜余波叠加）。参考区间为双向滚动重算，不是单调上移：由62–100逐步漂移，截至10月2日为83–119；“Above/Below range”标签追踪的是移动靶，历史标签之间不可直接比较，属已确认的设备行为，见§7。需文字说明的单点：8/17为110ms，但当夜仅睡3h30、深睡占比39%（平时14-30%），整夜滚动均值被短窗口与深睡加权双重抬高，按第十节不与完整夜序列横比，仅作记录。8/1创新高紧邻7/31接近正常强度的硬拉训练之后，与"下肢重训压低HRV"规则相悖，留存为反向观察，不强行纳入既有框架。 | 训练、睡眠与心理应激均可与HRV变化并存，当前记录不足以确定因素权重或诊断CNS疲劳。 |
| 睡眠心率 | 45–51 bpm（10月2日设备个人区间） | 47bpm（10月2日，夜间范围40–85bpm） | 正常 |
| SpO2 | 96-99% | 96%（10月2日） | 正常 |
| 呼吸频率 | 14-16 brpm | 15 brpm（10月2日） | 正常 |
| 跟腱长度 | — | 约20cm | 人群均值15-18cm偏长；弹性储能优势（储能=F²×L/2AE） |
| 晨起静息HRV（Polar H10/Elite HRV） | 建立中 | 88.03ms（9月24日，z=0.38，位于锁定正常带77.3–93.2ms）。逐日序列见《训练数据集》，本栏只记最新值与需要文字说明的样本。锁定参考期：8/8-8/23（闭区间，排除8/16、8/17），n=14，lnRMSSD 均值4.4417、SD 0.0935，常态带77.3-93.2ms，离群线73.8／97.7ms。锁定后不再逐日滚动重算。区间与离散度：可采信样本约55.93–109.12ms；8月16日57.09为已识别污染样本，不作为下界。Elite离散度明显小于华为夜间HRV，两者分开追踪、不可换算。7月九条基线区间65–104ms。判据：单日±20ms的往返属该序列的正常波动幅度；是否作疲劳解读取决于静息心率是否同向变动（8/11与8/13两次下跌均伴心率创低，故均按测量波动处理）。需文字说明的样本：8/16=57.09为污染样本（晨起先排尿、后洗热水澡，5分钟内测量；判别证据是坐姿与平躺RMSSD数值相同，正常应有明显差异），不入趋势判读，按录入纪律④照常进入数据集与基线计算，机制见§7"晨起测量的污染源"第③类。8/17=100.07（3h30睡眠后）与8/18=85.66（8h07优质睡眠后回落）构成对8/17读数的事后证伪。8/24=109.12为历史最高，读数干净但无已知污染源可归因，归入"未解"，见§7。外部参考：顶级耐力运动员 RMSSD 均值约60-100ms＋，训练有素者可达110-120ms，当前区间已进入该参考带宽。 9月25日至10月2日因安顺期间未携带心率带而缺测；上述为最近有效读数。 | ECG级精度·清醒静息即时值·与华为夜间HRV分开追踪趋势。7月4日两条为设备磨合数据（非标准静息）不计入基线。附加指标：SDNN、pNN50、Mean RR（内部一致性校验）、HRV CV（7/7起显示·变异系数）、频域LF/HF（争议指标·仅看长期趋势不解读单日值）。需按晨起标准协议继续积累建立个人范围 |

### 乳酸阈值数据

4月26日部分测试分段：①6:22/km@136bpm ②5:17/km@152bpm ③4:39/km@162bpm ④4:10/km@169bpm ⑤3:41/km@171bpm ⑥3:27/km@173bpm（后段传感器漂移）。手表估算Z3乳酸阈值区3:46-4:17/km，Z2马拉松区4:17-4:30/km。

4月29日LSD实测验证：15km后4:15/km巡航游刃有余、越跑越兴奋、上坡无酸感——确认4:15/km处于阈值以内。

5月7日模拟赛验证：10-14km段4:13/km@168bpm维持5km无崩溃——经温度修正后（24→17°C≈-8bpm），比赛当天同配速约160bpm，距阈值有明确余量。

正式乳酸阈值测试推迟至赛后执行（标准400米跑道，穿Kinvara 13正式段，20-25°C，导出FIT/CSV做功率-心率双直线回归分析）。

##   6    近期训练链条

### 9月10日–10月2日｜训练中不适与恢复记录

出现上呼吸道前驱症状：体感一般、隐约吞咽痛。据 8/28 那条「大负荷后 HRV 数日不回升时优先排查非训练因素」的规则，本日起把非训练因素排在累积负荷之前作为首要候选——此轮此前三次越界一直归因于累积负荷，本条改变归因排序。上感前驱期本就会压低迷走张力、拖慢恢复，且常早于自觉症状一到两天，这也解释得了为什么越界一次比一次深、中间还夹着睡眠很好的日子。Elite 67.32（z=−2.48），六天内第三次越界且逐次加深；0 伪迹，SDNN 与总功率差额 1390 为历次最小之一，干净样本。当晚睡眠并不差（420 分钟、深睡 28%、连续性 86），睡眠尚可而 HRV 是三次里最低的，指向驱动因素不在睡眠。

HRR 口径偏倚，由用户提出，成立：本次起测点 149 是全部 17 次里最低的（此前范围 153–169）。现行口径是掉幅÷起测点，分母含静息那一段，起测点越低可下降空间越小，百分比被系统性压低。改按心率储备口径（掉幅÷(起测点−静息 50)）重算全序列后排名基本不变——本次 29.3% 仍为倒数第二，但与 9/8 的 29.9%、9/3 的 30.4% 差距缩到 1.2 个百分点以内（原口径下分别是 19.5%、21.0%、21.0%）。方向不变，确定性下降。记为现行 HRR 口径的已知偏倚：起测点低于 155 时该值偏低，引用须注明。心率 136 也不单独归因于气温：档案换算 24→17°C 约 −8bpm，确能解释与 9/8（5:58／142）的大部分差异，但同日 HRR 为倒数第二，心率低与恢复慢并存，不支持「今天凉快所以轻松」这一单一解释。

左膝第四个点，鞋这条线浮出来了：三次跑步中 9/6（React）全程无感觉、9/8（Adios 9）有、9/10（Adios 9）有。两次有症状的都是 Adios 9，唯一无症状的是 React；而 9/8 配速快心率高、9/10 配速慢心率低，强度这个候选被排除，鞋成为两次症状里唯一不变的因素。n=2 对 1，不足以定论，但它是这条线上当前最值得测的变量，测法零成本：下次跑 React。症状形态两次一致：9/8「提速时反而没感觉」、9/10「后半程跑开了就没感觉」，都是低强度或未热开时有、热开后消失，方向与负荷驱动的机械性机制相反。跑步 9.44km、6:01、心率 136、负荷 46、恢复 10 小时，净海拔 −13.6m；形态 181／233／9.0／50.1。营养约 3819kcal、蛋白 186g，经脚本核对全序列：热量排第二，蛋白为全序列最高（前高 9/1 的 180），约 3.1g/kg，超上沿 71g。炸鸡翅 14 个按 9/7 口径折约 1722kcal，单项占全天 45%，且为高脂。预先标注：次日晨起数据将同时受这顿高脂与上呼吸道症状影响，两者不可分离，解释力削弱。

9月11日晨起Elite 60.56（z=−3.62）为全档最低的非明确污染记录；信号Good，1伪迹0纠正，SDNN²−TP差额1753，样本采信。华为整夜HRV 101处于设备个人区间82–117，两者口径不同不横比。夜间睡眠408分钟，另午睡26分钟；深睡33%、REM 10%、连续性78、觉醒2次，睡眠整体不差。9/10的吞咽不适当日恢复正常，感染候选降级，现有证据不能给本轮低值指定单一来源。

上午肩胸课容量6671kg，超过9/2的6416kg约4%；卧推50kg×6，较9/2的50kg×3进步。手表时长1:33:23、均心率111、峰值168、负荷34、恢复7小时，用户报告感觉不错。晨起自主神经低值没有转化为当次力量输出下降，作为主客观分离反例留存，但单次反例不反向证明低HRV无意义。右肩在高容量开链推举中未报告诱发，继续支持已撤限制；承重闭链条件未测，原限制不变。

体成分60.60kg（08:25），四项分量相加闭合；较9/10档案有效值60.05kg高0.55kg，按短期波动处理。秤端“较上次−0.4kg”与有效序列冲突，不采用变化量。营养约2890kcal、蛋白108g（区间2670–3130／99–118，主要误差来自五种无标签餐食），力量日蛋白达标、热量在误差内接近目标。未吃正餐晚饭，19:30前后以肉松蛋皮面包、鸡胸和椰汁替代，回住处后另吃85g洗沙月饼；晚间糖脂集中，次日数据同时受当日训练与饮食影响，不能单独归因。

9月12日晨起Elite 55.93（z=−4.47），连续三日由67.32降至60.56再降至55.93，成为全档最低的可采信RMSSD记录；信号Good、0伪迹。华为夜间HRV也由101降至81，略低于其个人区间。两台设备口径不同，不横向换算，但同向下降使Elite单设备孤立波动的解释变弱。SDNN²−TP差额约4144，频域与SDNN单点不作恢复归因。睡眠410分钟、01:09入睡、评分85、深睡26%、REM 13%、连续性100、觉醒1次、睡眠心率49；较前夜只晚4分钟，无法用这4分钟解释继续下降。连续晚睡、睡眠机会不足、前日力量负荷和饮食仅列候选，现有观察不能分离主因。

9月11日肩胸课后出现胸部与背部DOMS。背部具体位置未报告，昨日面拉4组本就直接刺激肩后束与上背，故背部酸痛不构成练错的证据。原计划LSD取消，改为日常10km：前段0.79km／4:57，主段9.37km／59:02／6:18@140，合计10.16km／1:03:59；主段负荷55、ATS 2.6、恢复12小时，跑姿为触地233ms、步频180、垂振9.0cm、左侧平衡50.1%。用户报告体感一般，气温不高且心率压得住。较低气温可减轻心率漂移，故心率可控不等于整体恢复良好；本课仍按中低强度有氧完成。鞋款无法可靠辨认，留空。

体成分60.05kg（08:36），四项分量相加闭合；较前日下降0.55kg，按短期波动处理。营养约3600kcal、有效蛋白145g（区间3250–4000／130–160，主要误差来自五种无标签餐食）。跑步日标准补给按0.5勺固定配方，花生酱按25g、两次坚果合计约40g计。蛋白充分；热量中值高于跑步日目标约500–700kcal，主要来自跑后补给、花生酱与大碗羊肉粉叠加，单日不作补偿性节食。

9月13日晨起Elite 71.54（z=−1.83），较前日55.93回升约28%，仍低于锁定基线；信号Good、0伪迹。华为夜间HRV由81回升至83、重回其个人区间，两个设备同向支持本次回升。睡眠438分钟、00:37入睡，比前夜提前32分钟且多睡28分钟；但REM仅8%、浅睡69%，消费级手表睡眠分期不作恢复裁决。胸背DOMS已消失，左膝无感。体成分60.40kg（08:33），四项分量闭合，较前日+0.35kg按短期波动处理。

原定10km实际完成前段0.70km／4:48和主段8.57km／54:08／6:19@135，合计9.27km／58:56；主段负荷44、ATS 2.3、恢复8小时，跑姿为触地238ms、步频180、垂振9.1cm、左右平衡50.0%。主段配速近似9月12日、均心率低5bpm，属有利观察，但气温、路线与收尾方式不完全一致，不作为能力或恢复的确定性比较。末段有3:42/km、177bpm的短暂尖峰，故本课主体为轻松有氧而非完全稳态。37分钟摄入能量胶后疲劳感稍缓解，只作时序记录。手动一分钟HRR为156→116（下降40bpm）；自动显示23bpm与曲线末端109bpm属另一设备口径。

营养约3300kcal、有效蛋白118g（区间3000–3650／108–132）。黑色谷物奶按200ml盒装、两把坚果各按25g、能量胶按约100kcal、跑步日标准补给按0.5勺固定配方计；主要误差来自15个鲜肉馄饨与外卖鸡蛋肉丝炒米线。相对单课日过渡目标热量约高350kcal，蛋白落在目标附近。晚间250ml百事可乐仅列为入睡观察项。

9月14日晨起Elite 82.07（z=−0.36）继续回升并回到锁定基线带内，信号Good、0伪迹；华为夜间HRV由83升至103、仍在其81–117个人区间。两设备同向是回升的记录事实，但测量窗口不同，不能横向换算或把单日变化归因于某一项行为。睡眠397分钟、01:35入睡，连续性62、觉醒4次、深睡8%，为碎片化一夜；HRV改善而睡眠表现下降，说明两类指标短期可不一致，消费级睡眠分期不作恢复裁决。

体成分62.70kg（08:41）较9月13日的60.40kg高2.30kg，水34.36、蛋白16.27、脂肪9.28、骨矿2.79kg四项闭合。BIA把脂肪估算同时抬高1.49kg；若是真实脂肪需约11000kcal的单日盈余，与已记录摄入不符，因此按水合、糖原、胃肠内容物及分量重分配的短期噪声处理，不能据此减少摄入或判定增脂。今日完全休息，目的为调整睡眠。

营养约3000kcal、有效蛋白115g（区间2700–3350／100–130）。三把混合坚果各按25g固定口径计，约516kcal；主要误差来自辣子鸡米粉、大碗羊肉粉、蜂蜜牛奶与肉松面包规格。热量和蛋白均足以支持目前增重方向。晚间150ml百事可乐只列为入睡观察项，不作既定结论。

9月15日晨起Elite 81.92（z=−0.38），与前日82.07几乎不变，连续第二日处于锁定基线带内；信号Good、0伪迹。华为夜间HRV仍为103。睡眠443分钟、00:31入睡，较前夜提前64分钟并多睡46分钟，连续性由62升至92；但觉醒3次、深睡18%，只确认时点和时长改善，不判完全修复。体成分61.35kg（08:34）较前日下降1.35kg，其中水分下降0.98kg，验证62.70kg高点以短期波动为主；较9月13日仍高0.95kg，暂不判增重趋势。

背日训练app容量7093kg，为记录内背日新高，超过8月24日6587kg约7.7%；app时长1:23:38，华为时长1:19:37、均心率114、峰值173、负荷34、ATS 2.0、恢复7小时。硬拉顶组75kg×1是绝对重量新高，但不等于综合力量超过8月31日70kg×8；顶组前60kg×8存在预疲劳。宽距高位下拉后右肩出现轻微不适，虽在安全可承受范围，仍按轻度阳性诱发记录；下次回到中立握或反手，不由单次可承受解除限制。

营养约3000kcal、有效蛋白110g（区间2700–3350／100–125），总量接近力量日目标。漏掉练前坚果，但完整力量日补给约620kcal／30g蛋白已托住训练后补给，无需次日补偿。训练后立即送流浪猫去宠物医院，22:00才以约170g南瓜玉米粥和四个炸香蕉补晚餐；晚餐偏晚、油脂集中与明显心理难受同时存在，均只列为次日睡眠和HRV背景，不作单因果判断。

9月16日晨起Elite 68.82（z=−2.25），低于锁定基线下界73.8；信号Good、0伪迹。华为夜间HRV也由103降至94，但仍在设备个人区间81–117。睡眠435分钟、00:41入睡，评分84，深睡22%、REM 14%、连续性78、觉醒1次，时长和结构整体尚可；因此本次下降不能只归因于入睡时间后移。前日记录内最高容量背日、明显心理难受和22:00偏晚油脂餐均是并存背景，单日不区分因果。体成分60.65kg较前日下降0.70kg，其中水分下降0.46kg，仍按短期波动解释。

跑步热身0.88km／5:14，主跑8.57km／53:20，主跑配速6:13、均心率139、峰值176、均功率176W、负荷53、ATS 2.9、恢复10小时；合计9.45km／58:34。主跑位于前日高容量背日之后，不按轻松恢复跑解释。手动一分钟HRR 160→117=43bpm，归一化26.9%，为近期三次中最高；说明运动后即时回落良好，但不抵消晨起HRV低值。手表自动下降19bpm因窗口不同，仅作旁证。

营养约3200kcal、有效蛋白122g（区间2900–3550／110–135），达到当前增肌期目标。两把混合坚果、500ml牛奶、80g豆沙面包、煎蛋、35g鸡胸肉与跑步日标准补给构成稳定底盘，练后鸡蛋肉丝炒米粉补足主餐；主要估算误差来自软哨细面、炒米粉份量与用油。

9月17日晨起Elite 72.26（z=−1.73），较前日68.82回升，但仍低于锁定基线下界73.8；信号Good，2个未校正伪迹仅占0.72%，按有效读数留存。华为夜间HRV由94降至89，仍处于设备个人区间82–117。两设备均处近期偏低位置，但当日方向不完全一致，不作单因果归因。睡眠453分钟、00:31入睡，评分87，深睡31%、REM 13%、连续性96、觉醒1次，较前日改善而HRV未完全回带，提示恢复可能存在时滞或受多项既往负荷影响，单日不建立新规则。体成分60.45kg较前日下降0.20kg，水分仅降0.04kg，按短期BIA与胃肠内容物波动处理。

按计划完全休息，未记录训练。营养估算约2950kcal、有效蛋白125g（区间2600–3300／110–140）；晚餐实际食用9块KFC热辣香骨鸡和330ml百事，剩余3块未计入。软哨细面份量、香骨鸡可食部、裹粉与吸油量构成主要误差，因此只能判断全天能量和蛋白大概率高于休息日基础目标，不作精确超标判断。

9月18日晨起Elite 92.30（z=+0.89），较前日72.26显著回升，重新进入锁定基线带；信号Good、0伪迹。华为夜间HRV由89升至103，仍在设备个人区间82–117。两设备同向回升，支持当晨自主神经指标较前日改善，但不同测量场景不换算。睡眠仅368分钟、00:48入睡，评分77，深睡29%、REM 6%、连续性75、觉醒2次；HRV回带不构成睡眠负债已消除的证据。体成分60.70kg较前日+0.25kg，水分+0.32kg、脂肪估计-0.15kg，按BIA与短期水合波动处理。

胸肩日完成容量2830kg、训练app时长46:03；华为口径43:32、均心率109、峰值167、负荷14、恢复4小时。卧推50kg×8较9月11日50kg×6增加2次，是同重量重复数进步。此前右肩有轻微可承受不适；本次未报告新诱发不适，但未提及不等于限制解除。营养约3800kcal、有效蛋白160g（区间3300–4400／135–185）；两餐均含米饭，午餐八九分饱、晚间火锅七八分饱。误差主要来自分食比例、火锅肉量、蘸料与米饭量，但在范围内能量和蛋白均高于力量日目标，无需追补或次日限制。

9月19日晨起Elite 81.26（z=−0.47），较前日92.30回落但仍在锁定基线带内；信号Good，1个未校正伪迹仅占0.38%，按有效读数留存。华为夜间HRV由103降至94，仍在设备个人区间82–117。两设备同向回落且均正常，更符合前日高值后的正常回归，不判恢复恶化。睡眠439分钟、01:17入睡，评分82，深睡22%、REM 11%、连续性78、觉醒2次；时长较前夜增加71分钟，但入睡继续后移。体成分59.95kg较前日-0.75kg，水分估算占其中0.41kg；前日高能量摄入后次晨仍下降，进一步说明单日摄入与次晨体重不存在稳定对应。

跑步热身0.85km/4:55，主跑9.58km/56:49，合计10.43km/1:01:44。主跑均配5:56、均心145、峰值187、均功率183W、负荷78、ATS 2.8、恢复15小时；触地232ms、步频182、垂振8.9cm、平衡50/50。用户报告体感很好、越跑越快且无感加速，19:00仍约26℃；配速与功率后段抬升而跑姿稳定，故按渐进跑记录，不归为纯轻松跑。手动一分钟HRR下降43bpm，但缺原始端点，结构字段留空。营养约2900kcal、有效蛋白120g（区间2600–3300／108–135）；意面按熟重约250g估算，全天接近跑步日目标且蛋白充足。

9月20日晨起Elite 70.65（z=−1.97），较前日下降13.1%并低于锁定基线下界；信号Good、0伪迹，按有效读数记录。华为夜间HRV由94降至92，仍在设备个人区间82–117。睡眠455分钟、00:51入睡，评分83，深睡24%、REM 12%、连续性71、觉醒2次；睡眠机会较前夜增加16分钟且入睡提前26分钟，但不能据此判定恢复完全。体成分60.85kg较前日+0.90kg，水分估算+0.91kg，增量几乎全部由水合变化解释，不判为一日组织增长。

跑步热身0.83km/4:50，主跑9.41km/56:38，合计10.24km/1:01:28。主跑均配6:03、均心139、峰值184、均功率197W、负荷60、ATS 2.6、恢复12小时；触地232ms、步频181、垂振9.0cm、平衡50.2/49.8。较9月19日主跑放慢7秒/公里、均心率低6bpm、负荷降低18，但构成连续第二天约10km。手动一分钟HRR下降32bpm，缺原始端点，结构字段留空；手表自动值19bpm不替代手动口径。营养约3200kcal、有效蛋白120g（区间2900–3600／108–135）；跑步日标准补给底液改为豆浆，全天能量与蛋白达到目标。

9月21日晨起Elite 78.67（z=−0.82），较前日回升11.4%，回到锁定基线带内且靠近下缘；信号Good、1个伪迹、占0.36%。华为夜间HRV由92升至107，位于设备个人区间82–117。睡眠429分钟、评分75，深睡15%、REM 7%、连续性73、觉醒7次，结构明显碎片化；HRV回升不抵消这一问题。体成分61.30kg较前日+0.45kg，水分估算+0.53kg而脂肪估算−0.12kg，变化由水合主导。

背部训练容量5407kg，训练记录1:11:41；华为1:10:35、均心107、峰值170、负荷20、ATS 1.4、恢复5小时。较上次背部训练7093kg下降23.8%，未做70–75kg硬拉顶组，属于主动下调的中等训练量。右肩主观正常，仅代表当日状态。营养约3200kcal、有效蛋白118g（区间2900–3550／108–132）；力量日标准补给完整摄入，怪噜饭按更正后的三分之二份计入。

9月22日晨起Elite 81.82（z=−0.40），较前日上升4.0%，位于锁定正常带；信号Good、0伪迹。华为夜间HRV由107微降至105，仍在个人区间83–118。睡眠459分钟、评分87，深睡30%、REM 13%、连续性85、觉醒1次，较前夜全面改善。体成分63.10kg较前日+1.80kg，其中水分估算+1.36kg，占增量约76%，不判为一日组织增长。

跑步热身0.80km/5:08，主跑9.51km/56:11，合计10.31km/1:01:19。主跑均配5:54、均心141、峰值182、均功率195W、负荷60、ATS 2.7、恢复13小时；GCT 231ms、步频182、垂振8.8cm、平衡50.1/49.9。较9月20日主跑快9秒/公里，均心率仅高2bpm且负荷相同。晨起主观、睡眠质量、训练体感及客观表现同向，但已连续第四天正式训练。营养约3150kcal、有效蛋白110g（区间2900–3400／100–120），达到跑步日需求。

9月23日晨起Elite 101.89ms（z=1.95），较前日上升24.5%，高于锁定正常带上界；信号Good、0伪迹。华为夜间HRV 102ms，仍在设备个人区间。睡眠413分钟、评分81，深睡30%、REM 8%、连续性80、觉醒2次；总时长较前夜少46分钟，REM偏低。体成分61.15kg较前日低1.95kg，单日体成分变化不作组织变化解释。

跑步热身0.81km，主跑9.24km/6:00每公里，均心136、负荷43，合计约10.05km。较9月22日主跑少0.27km、慢6秒/公里、均心低5bpm、负荷低17；高温等条件不同，不据此判作状态下降。用户手动一分钟HRR下降40bpm，未提供两端心率，原始端点留空。跑步后半程在高温中出现冷汗和强烈饥饿；当天第一次省略下午茶，但此前吃了35g鸡胸肉，练前仍有65g面包。记录为症状，不作低血糖诊断。

营养估算约3000kcal、有效蛋白120g（约2600–3400kcal、100–140g）。早餐肉松面包80g、牛奶250ml；加餐鸡胸肉35g；午餐15个大鲜肉馄饨和牛奶250ml；练前面包65g；练后怪噜饭一份、较小碗红糖冰粉和跑步日标准补给；下午茶省略。份量、用油、冰粉含糖量与补给配方造成较大估算误差。后半程症状提示炎热天气下需复核训练前碳水和补水、电解质安排。

9月24日晨起Elite RMSSD 88.03ms（z=0.38），较前日下降13.6%，回到锁定正常带；信号Good、1个伪迹、0校正。华为夜间HRV 111ms，较前日上升9ms，仍在设备个人区间。睡眠435分钟、评分84，深睡26%、REM 11%、连续性96、觉醒2次；较前夜多22分钟，REM和连续性改善。体成分61.10kg，较前日下降0.05kg。

9月24日饮食估算约2700kcal、有效蛋白100g（约2200–3300kcal、80–125g；葡萄糖粉用量未知）。早餐鸡胸肉35g；午餐双椒牛肉拌面（加面）；下午茶牛奶300ml；晚餐牛奶400ml、葡萄糖粉和一碗羊肉米粉；夜宵香蕉和奥利奥雪糕。估算误差主要来自餐馆份量、用油和葡萄糖粉克数。用户称拌面辛辣、之后流鼻血并归因于“上火”；只记录时间关联，不据此确认因果。

用户已回安顺，计划停留约半个月备考和训练，忘带心率带。9月24日未提供训练记录；从后续记录起，胸带心率、手动HRR（若需依赖胸带测量）及Elite晨测可能缺失。华为夜间HRV单独保留，不代入Elite锁定基线。

9月25日晨起华为睡眠记录：总睡眠412分钟（6小时52分），01:06入睡、08:00醒；深睡146分钟（35%）、浅睡209分钟（51%）、REM 57分钟（14%），觉醒1次、连续性88分，睡眠心率48bpm，夜间HRV 92ms，位于当时设备个人区间。用户表示在家睡得好。体成分62.30kg（09:02），体脂13.3%、骨骼肌28.8kg；短期体重变化按水合与胃肠内容物波动处理，不据单次读数判断组织增减。Elite晨测与胸带心率未记录，符合忘带心率带后的监测缺项。

上午完成居家徒手上肢：俯卧撑12、15、15、13次，共55次；YTWL 2组×10次，配合3kg俯身哑铃划船20、25次。KeepStrong记录容量135kg、19:54；华为训练时长31:21、均心率99、峰值145、负荷4。下午健身房腿部维持训练，记录容量5320kg、1:05:25：深蹲20×8、30×8、40×8、50×8、60×4kg；硬拉50×8、60×4、55×8kg；腿举90×8×2、坐姿腿屈伸35/40/45×12kg、动态死虫55次、抬腿10次×2。华为训练时长1:01:10、均心率116、峰值174、负荷25、恢复提示5小时。上午与下午分开训练；胸带及Elite数据缺失，手表分别记录，不合并成单一心率或HRR值。

饮食估算约3150kcal、有效蛋白145g（约2750–3650kcal、120–175g，主要误差来自外卖份量、烹调油、烧烤串大小与实际可食量）。早餐香蕉1根、鸡胸肉35g；午餐饭盒米饭、蒸蛋及配菜全部吃完，另吃少量碗装炒鸡；练后增肌粉1.5勺（按档案规格约67.5g，蛋白约15.5g）＋白砂糖1汤匙＋豆浆350ml，未使用完整标准力量日补给；晚餐烧烤约六七分饱，包括牛肉5–6串、牛筋3–4串、小瓜5串、鸡皮2串、火腿肠5串及少量其他食物，另饮康师傅鲜果橙300多ml。热量与蛋白为粗估，不能按补给粉单项推定全天达标。

9月26日晨起记录：夜间睡眠8小时（00:23入睡、08:24醒），评分90；深睡3小时6分（39%）、浅睡4小时10分（52%）、REM 44分钟（9%），觉醒1次、深睡连续性93、睡眠心率48bpm、华为夜间HRV 108ms、SpO₂ 97%、呼吸频率15。体成分61.05kg（09:14），体脂13.8%、骨骼肌28.4kg；与前次读数的单日差异不用于推断组织增减。安顺期间未带心率带，Elite晨测缺失。

当天分两段有氧：第一段2.23km/14:44，均配6:36/km、腕式均心率131、步频179、平均功率约175W；第二段11.58km/1:10:23，均配6:05/km、腕式均心率145、峰值165、步频181、平均功率185W。合计13.81km、1:25:07，约6:10/km；合并均心率和功率为按时长估算值。用户报告跑步过程无负面感觉，跑后非常饿，先吃香蕉1根（练前、练后各半根）。手动一分钟HRR下降40bpm；未提供起始与一分钟末心率，故仅文字记录，结构化原始心率字段留空。未报告跑中冷汗。

当日饮食估算约2750kcal、蛋白质约95g（估计范围2300–3200kcal、80–115g）。早餐洗沙包子2个；午餐大碗羊肉粉；下午茶板栗仁2把；练前半根香蕉；练后/晚餐半根香蕉、E-MASS增肌粉0.5勺（约22.5g粉，按档案标签约87kcal、5.2g蛋白）＋羊奶粉20g＋接近200ml豆浆、拳头大小豆花1块及分量较足的肉丁面1碗。主要误差来自外食份量和用油、板栗重量及奶品标签。当天中间值接近蛋白质100g目标但不能确认达标，热量区间较宽，不据单日估算判断能量盈余。

9月27日睡眠477分钟（7小时57分，01:02入睡、09:02醒），评分85；深睡104分钟（22%）、浅睡308分钟（65%）、REM 65分钟（13%），觉醒2次、连续性74。华为夜间HRV 111ms（设备个人区间84–119），睡眠平均心率47bpm（范围40–79，个人区间45–51），SpO₂ 97%、呼吸频率15、呼吸质量98。安顺期间忘带Polar H10，Elite晨测缺失；体重61.40kg（9月27日10:07），BMI 19.4、体脂率13.5%；测量时段接近上午，但是否严格符合晨起空腹同口径未确认。较9月26日09:14的61.05kg高0.35kg，按短期水合、糖原与胃肠内容物波动记录，不解释为单日组织增长。

两段有氧，原图分别为18:00与18:25开始。第一段2.23km／14:19，配速6:25/km，均心率129、峰值152，平均功率181W、峰255W，负荷8，步频179、峰191，步幅87cm、步数2569，爬升24.4m、下降9.4m，总热量123kcal、活动104kcal，恢复提示2小时。主跑9.02km／54:53，配速6:05/km，均心率141、峰值170，平均功率184W、峰270W，负荷48、ATS 2.4、恢复12小时，步频181、峰240，步幅90cm、步数9980，触地228ms、左右平衡50.2/49.8、垂直振幅9.0cm，爬升48.3m、下降91.0m，总热量518kcal、活动445kcal。两段合计11.25km／1:09:12，合计均配约6:09/km为派生值；结构字段采用主跑原始指标，不填合并心率、功率或负荷。心率为腕式记录，功率仅记录不解读。鞋款未提供。

用户报告“和昨天体感差不多，都挺不错，就是石板路跑着不舒服，膝盖不舒服，不如贵阳南明河那种跑起来舒服”。整体体感与局部膝部不适分别保留；膝盖侧别、程度及跑后是否持续未提供，不据此诊断或确认路面因果。手动一分钟HRR下降29bpm，起始和第60秒心率未提供，hrr0/hrr1留空，不用手表自动恢复数值补齐。未给1–5体感评分，feel留空。

饮食粗估2500kcal、蛋白质105g（范围2200–2900kcal、90–125g）。早餐35g鸡胸肉；午餐照片中米饭、蒸蛋、辣椒肉丝、小瓜丝、玉米、四季豆土豆、黄瓜及汤全部吃完，菜品按图辨认、重量未称。练前一小时50g板栗仁，练前即刻半根香蕉；练后晚餐半根香蕉、200g米饭（暂按熟重）、200g连壳称毛豆、200g已卤好腐竹（湿重）、300ml牛奶、0.5勺E-MASS及一汤匙白砂糖。香蕉全天合计一根；毛豆扣除豆荚估可食量，腐竹不按200g干品计算。增肌粉0.5勺按22.5g、约87kcal和5.2g蛋白；白砂糖暂按12–15g。未自动加入标准补给其他配料。主要误差来自午餐米饭与用油、毛豆出仁率、卤腐竹含水与用油、奶品标签和糖匙大小；不据单日中值判断能量盈余。

9月28日晨起补报睡眠：00:52入睡、08:31醒，实际睡眠443分钟（7小时23分），评分84；深睡105分钟（24%）、浅睡290分钟（65%）、REM 48分钟（11%），三阶段合计443分钟；觉醒2次、深睡连续性100。华为夜间HRV 115ms，设备个人区间84–120ms；平均睡眠心率47bpm、范围40–79bpm，SpO₂ 96%、呼吸频率15次/分、呼吸质量98。数据归属27日晚至28日早晨；Elite晨测仍缺。

9月28日14:03完成胸腹核心训练。华为记录1:20:54（4854秒），总热量362kcal、活动热量253kcal，腕式均心率98bpm、峰值142bpm，训练负荷7（低）、恢复提示1小时。KeepStrong记录容量4300kg；其页面另显示“时长16秒、消耗1千卡”，与华为计时明显不是同一统计口径，不用于替代手表时长和热量。动作：蝴蝶机夹胸15×12、10×12、15×12、10×12kg；杠铃卧推20/30/40/50/60/55/50/50kg各8次；双杠臂屈伸（练胸）自重6组×8次；挂片推胸15×8×2、17.5×8、20×8×3kg；动态死虫65次；抬腿8/6/6次。容量4300kg由有重量的三项闭合：夹胸600＋卧推2840＋挂片推胸860kg；自重与核心次数不计入容量。卧推60kg×8及App估算1RM约76kg按原记录保留；该组是否受助未明确，不能确认独立完成的60kg×8或76kg的1RM，不据此判定相对9月11日的独立力量增幅。本次总容量较9月11日胸肩课6671kg低约35.5%，但动作构成和附件训练数量不同，不能按总容量直接判断退步。手表低负荷反映整堂课的心血管压力较低，不等于胸部局部机械张力或训练刺激低。胸带未携带，心率为腕式记录。 9月29日补充：9月28日与29日均有朋友在各动作最后1–2组接近力竭时给予轻微辅助，并非整组持续助力。具体受助重复次数未记录；按App保留重量、次数和容量，不扣算辅助力量。不能把受助重复用于确认独立完成能力或可靠的1RM。9月28日卧推60kg×8是否受助仍未明确。

9月28日饮食与饥饿反馈如下。早餐洗沙包子2个；午餐大碗羊肉粉；练后为500ml豆浆、E-MASS增肌粉1.5勺及白砂糖1汤匙；晚餐烧烤，用户说明比9月25日那次少一些。随后因仍有饥饿感，加餐200g已卤好腐竹（湿重）、200g连壳称卤毛豆及鹌鹑蛋5个。毛豆按估计可食部计算，腐竹不按干重计算。增肌粉1.5勺按67.5g计，粉体约261kcal、蛋白质15.5g。全天粗估约2950kcal、蛋白质135g；估计范围约2350–3550kcal、110–165g。主要误差来自包子规格、羊肉粉份量与用油、豆浆含糖及浓度、烧烤品种与实际食量、卤汁用油、毛豆出仁率。末次加餐约增加430–650kcal、35–50g蛋白；饥饿感作为当时主观反馈记录，不能单独证明全天存在确定热量缺口。 体重62.35kg（9月28日20:39），BMI 19.7、体脂率13.2%。该值为晚间读数，受全天饮食、饮水、训练后补给和胃肠内容物影响，不纳入晨起空腹体重的直接趋势比较；较9月27日上午读数高0.95kg不解释为组织增长。

9月29日睡眠471分钟（7小时51分，00:53入睡、08:49醒），评分85；深睡102分钟（22%）、浅睡310分钟（66%）、REM 59分钟（12%），觉醒2次、深睡连续性80。华为夜间HRV 104ms，位于设备个人区间84–120ms，较补齐后的9月28日记录115ms下降11ms；睡眠平均心率50bpm，夜间范围42–89bpm，位于个人区间45–51bpm。SpO₂ 96%、呼吸频率16次/分、呼吸质量100。总时长与各阶段分钟数闭合为471分钟。安顺期间未携带Polar H10，Elite晨测继续缺失。同时上传的体脂秤截图标注为9月26日09:14、61.05kg，是已录入的旧读数，不作为9月29日新体重重复记录。 9月29日10:23体重61.65kg，BMI 19.5、体脂率13.3%，均为体脂秤读数；是否严格晨起空腹未确认。较9月26日09:14的61.05kg高0.60kg，属短期读数差，不能据此确认组织增长；9月28日62.35kg为晚间读数，不与上午值直接判断增减趋势。

9月29日13:56背部力量训练。华为时长1:10:04（4204秒），活动热量304kcal、总热量399kcal，两者不相加；腕式平均心率109bpm、最高143bpm、训练负荷17（低）、有氧训练压力1.3、恢复提示3小时。心率区间：极限0分钟、无氧耐力0分钟、有氧1分钟、燃脂18分钟、热身42分钟；区间显示合计61分钟，不补算其余时段。KeepStrong容量8220kg，共5项20组；App时长13秒、消耗0千卡不作为实际时长或热量。引体向上自重8次×4组；宽距高位下拉65kg×12、70kg×12×3组；绳索单臂高位下拉按原记“25kg＋30kg”×12×4组；悍马划船—单侧25kg×12、30kg×12×3组；器械T杆划船—宽距15kg×12、20kg×12×3组。容量按App口径为3300＋2640＋1380＋900＝8220kg，不额外给单侧动作翻倍。App下拉和T杆动作旁另显示98、77、28，保留为应用显示值，不作为独立力量测试结果。设备低负荷和恢复时长不能证明局部肌肉已恢复，也不能作为头痛期间继续训练的依据。 9月29日补充：9月28日与29日均有朋友在各动作最后1–2组接近力竭时给予轻微辅助，并非整组持续助力。具体受助重复次数未记录；按App保留重量、次数和容量，不扣算辅助力量。不能把受助重复用于确认独立完成能力或可靠的1RM。9月28日卧推60kg×8是否受助仍未明确。

9月29日饮食：早餐香蕉1根；午餐香菇肉沫面约400g；练后500ml豆浆＋1.5勺E-MASS增肌粉＋白砂糖1汤匙＋香蕉1根；晚餐肉松鸡蛋三明治约200g、乳酪面包约150g、牛奶250ml。全天香蕉共2根。增肌粉1.5勺按67.5g计，粉体约261kcal、蛋白15.5g。沿用本轮粗估：早餐90–120kcal／约1g蛋白，午餐650–950kcal／25–40g，练后570–700kcal／31–38g，晚餐1100–1450kcal／35–48g。全天代表估值2800kcal、110g蛋白，范围2410–3220kcal、92–127g；非精确称量结果，面条及肉量、烹调用油、豆浆浓度与含糖量、面包配方和糖勺重量是主要误差源，不据此确认热量盈余。

9月29日头痛与视觉症状（用户23:18补充）：午餐快吃完时开始右侧轻微头痛，伴整体视野左下方雪花状干扰，其中几十秒位于视野中央；未交替遮眼，单眼或双眼未确认。视觉症状持续十多分钟，在头痛明显出现时完全恢复。头痛训练中稍加重，傍晚约19时进一步加重并变为双侧；18:30小憩约15分钟后曾缓解，随后玩《瓦罗兰特》后再加重，两条时间线按用户原述保留。晚间疼痛6–7/10，疲累；该分数为头痛强度，不是训练feel评分。既往也出现类似视觉发作，有时不伴头痛，并报告通常次日恢复；截至9月29日晚，本次次日结局未知；9月30日恢复反馈见当日记录。用户未明确回答是否存在无力、麻木、言语异常或眼痛，不写成已排除。用药、正式诊断、查体和就医结果尚未提供。

当前判断与处置：视觉干扰十多分钟后完全恢复、随后头痛的时序与偏头痛视觉先兆相符，但仅为待临床评估的可能，不能在线确诊或排除其他眼科、神经血管原因。视野左下方不等于左眼；进食、训练、游戏与症状的先后关系不证明因果。当晚头痛仍6–7/10且反复加重，已建议停止训练和游戏、今晚就医评估，不以过去次日自愈或正常HRV保证安全。若突发最剧烈头痛、再次视力下降或持续视野缺损、无力、言语异常、意识改变、发热伴颈僵，立即急诊／120；不自行驾驶。就医前安静避强光休息、正常补水；不靠冷水冲头或继续运动试图缓解。是否已就医尚未确认。

9月30日睡眠425分钟（7小时05分，00:46入睡、07:54醒），评分85；深睡129分钟（30%）、浅睡249分钟（59%）、REM 47分钟（11%），合计425分钟。觉醒1次、深睡连续性91；华为夜间HRV 94ms，设备个人区间84–119ms；平均睡眠心率48bpm、范围42–77bpm，个人区间45–51bpm；SpO₂ 97%、呼吸频率15次/分、呼吸质量98。Elite晨测及胸带心率因安顺期间未携带设备而缺失。 9月30日08:56体重60.60kg，BMI 19.1、体脂率13.5%、骨骼肌28.3kg、内脏脂肪2.0、基础代谢1500kcal/d、水分55.5%、骨矿2.74kg、蛋白质26.5%、去脂体重52.4kg、身体年龄20、评分82。体成分水33.65＋蛋白16.03＋脂肪8.18＋骨矿2.74＝60.60kg。较29日上午61.65kg下降1.05kg；称重是否严格同条件未确认，日间BIA变化不解释为组织或肌肉流失。

9月30日跑步两段：17:42第一段2.21km／14:27，配速6:32/km，腕式均心率133bpm、峰值149bpm、负荷10，步频181，活动热量105kcal／总热量124kcal。18:09主跑9.98km／1:07:17，配速6:45/km，均心率140bpm、峰值151bpm、负荷55、ATS 2.7、恢复提示14小时；均功率164W、峰值221W，步频181、触地236ms、垂直振幅9.0cm、左右平衡50.1%／49.9%，海拔1358.1–1384.2m。主跑心率区间基础有氧60分钟、热身5分钟，其余显示区间为0；不补算剩余时间。两段合计12.19km、1:21:44（4904秒），活动热量610kcal、总热量719kcal，两者不相加。结构化跑步字段采用主跑口径，不混入第一段或合计时长。手表自动HRR页面显示下降12bpm、起止145／120bpm，起止差25并非已确认的手动一分钟HRR，hrr0／hrr1留空；VO₂max 52为设备估计。

9月30日饮食：早餐35g鸡胸肉；午餐一荤四素套餐，沿用此前照片类似份量、暂按含米饭且全部吃完估算，未有当日称重；下午茶35g鸡胸肉；练后晚餐鲜肉馄饨20个＋E-MASS增肌粉0.5勺＋羊奶粉20g＋白砂糖1汤匙＋牛奶300ml。鸡胸肉全天70g。增肌粉按每勺45g，0.5勺22.5g约87kcal／5.2g蛋白。羊奶粉新标签每100g：2030kJ、蛋白20g、脂肪22g、碳水51.5g、钠300mg、钙1000mg；本次20g为406kJ（约97kcal）、蛋白4g、脂肪4.4g、碳水10.3g、钠60mg、钙200mg。牛奶暂按普通全脂奶、糖按12–15g。全天代表估值2450kcal／蛋白105g，范围约2050–2900kcal／90–125g；晚餐约1050–1445kcal／43–59g蛋白。主要误差来自套餐米饭及用油、馄饨大小与肉馅、奶品与鸡胸肉标签、糖勺大小；不据估值确认热量盈余、低血糖或确定能量缺口。

9月30日症状转归：晨起自述头痛较29日晚减轻约80%，视野正常；猛烈摇头仍可诱发疼痛。确认未就医；类似症状自高中起反复出现，通常次日明显缓解或恢复，有时视觉症状不伴头痛，也有头痛不伴视觉症状。上午淋浴时热水加重、冷水缓解，最后冷水冲头后自述猛烈摇头基本不痛。傍晚跑后反馈头痛没有加重，状态与上午冷水冲澡后相近，但今天很容易累；疲倦在日常活动或仅跑中发生尚未区分。香蕉已吃完，未吃计划中的跑前半根。正式诊断、查体及用药信息未提供；未报告的神经症状不写作已排除。

综合判断：25日上肢＋腿部双练、26–27日跑步、28–29日力量、30日跑步，连续六天有训练。29日视觉异常和轻微头痛始于训练前，训练可能加重已有发作；此前累积负荷参与诱发属于可能，未建立重复因果规律。近期睡眠总体尚可，26–30日平均459.2分钟（约7小时39分）、评分均值85.8；HRV处设备个人区间，不能据此证明脑部或整体恢复，也不能推断脑血管收缩。主跑心率和步频总体稳定、末段未持续掉速；与27日主跑6:05/km、141bpm相比，今天6:45/km、140bpm，提示相近心率下速度较低，但天气、路线、停顿及腕式误差未控制，不判定体能下降或CNS损伤。偏头痛样发作恢复期疲倦、累积训练与补给分配均为候选解释，未确诊。冷水缓解是主观反应，不能验证血管扩张病因，也不能与自然消退分离。已建议停止摇头测试，残余症状及易累期间休息、正常进食补水，次日暂停跑步与大重量；症状消退后再恢复。长期反复未确诊可安排头痛门诊；突发最剧烈头痛、持续视力缺损、无力或言语异常需及时急诊。参考：American Migraine Foundation，https://americanmigrainefoundation.org/resource-library/how-to-deal-with-postdrome/ ，https://americanmigrainefoundation.org/resource-library/migraine-and-exercise-benefits/ 。

10月1日睡眠494分钟（8小时14分，00:49入睡、09:05醒），评分91；深睡183分钟（37%）、浅睡245分钟（50%）、REM 66分钟（13%），合计494分钟。觉醒2次、深睡连续性100；华为夜间HRV 97ms，设备个人区间84–119ms，较9月30日94ms增加3ms；平均睡眠心率49bpm、范围43–77bpm，个人区间45–51bpm；SpO₂ 97%、呼吸频率15次/分、呼吸质量98。睡眠归属9月30日晚至10月1日晨。Elite晨测仍未提供，不以华为HRV填充。 10月1日09:40体重60.45kg，较9月30日60.60kg下降0.15kg；BMI 19.0、体脂率13.3%、骨骼肌28.3kg、内脏脂肪2.0、基础代谢1502kcal/d、水分55.7%、骨矿2.74kg、蛋白质26.5%、去脂体重52.5kg、身体年龄20、评分82。体成分水33.67＋蛋白16.00＋脂肪8.04＋骨矿2.74＝60.45kg。称重是否严格同条件未确认，单日小幅变化不解释为组织增减。

10月1日晨起确认头痛已消失；本次9月29日发作、9月30日明显缓解、10月1日消失。此前确认未就医，正式诊断未建立。用户补充回安顺后每一天睡醒精力都比较充沛，包括9月30日晨起；与9月30日跑步时容易累分开记录，不能扩写为持续全天疲劳或次晨精力不足。当前症状改善与睡眠指标不用于证明或排除CNS疲劳，也不验证HRV升高导致脑血管收缩。 10月1日用户决定完全休息一天，未报告训练；明确按休息日记录，训练数值留null，不填0。10月2日再安排训练，具体内容和强度尚未确定，不预写为已完成训练。

10月1日饮食：早餐洗沙包子1个；午餐牛肉面1碗；晚餐自助火锅，较多甜品、牛肉和蔬菜，用户自述吃到十分饱、非常撑；夜宵蜜雪冰城柠檬水1杯。份量未称量，用户明确无需再计算具体份量，不增加主动称重任务。沿用品类粗估：早餐180–280kcal、午餐550–850kcal、晚餐1400–2400kcal、柠檬水100–200kcal（暂按常规含糖一杯，规格和糖量未确认）。全天约2230–3730kcal，代表估值约3000kcal；蛋白质约90–140g，代表估值115g为区间中点。kcal／pro均为低置信度估算，并非实测或精确摄入；非常撑是主观饱腹程度，不能准确换算热量。主要误差来自火锅甜品、牛肉实际份量与肥瘦、蘸料及汤底、面碗大小、柠檬水规格和糖量；不据估值断言能量盈余或蛋白必然达标。

10月2日睡眠488分钟（8小时08分，01:17入睡、09:29醒），评分90；深睡173分钟（35%）、浅睡252分钟（52%）、REM 63分钟（13%），合计488分钟。觉醒1次、深睡连续性87；华为夜间HRV 97ms，设备个人区间83–119ms；平均睡眠心率47bpm、范围40–85bpm，个人区间45–51bpm；SpO₂ 96%、呼吸频率15次/分、呼吸质量98。Elite晨测仍缺，不以华为夜间HRV替代。 10月2日10:13体重61.15kg，较10月1日60.45kg增加0.70kg；BMI 19.2、体脂率13.4%、骨骼肌28.5kg、内脏脂肪2.0、基础代谢1513kcal/d、水分55.8%、骨矿2.76kg、蛋白质26.3%、去脂体重53.0kg、身体年龄20、评分82。体成分水34.13＋蛋白16.07＋脂肪8.19＋骨矿2.76＝61.15kg。称重条件未确认；火锅后单日体重回升、BIA骨骼肌增加0.2kg不解释为确定组织增重。

10月2日13:55肩部＋核心力量，手表1:00:36（3636秒），腕式均心率114／峰值151bpm，负荷19、ATS 1.4、恢复提示4小时，活动290kcal／总372kcal。哑铃推肩：7.5kg×8、10kg×8、17.5kg×8、20kg×3、17.5kg×4、15kg×8，间歇100秒；杠铃提拉：10kg×8、15kg×8共5组，间歇60秒；面拉30kg×8共6组，间歇110秒；动态死虫65次，间歇120秒；抬腿8次×3组，间歇90秒。App容量2650kg，与前三个动作截图记账相加一致（530＋680＋1440）；哑铃按App显示口径保留，不自行翻倍。App时长28秒与训练总时长不符，仅保留来源，采用手表总时长。用户补充在安顺均与朋友同练，冲极限重量有辅助；今日20kg×3按该辅助背景保留，独立次数和辅助程度未给出，不记为已确认独立PB、不用于独立1RM估算。9月28–29日倒数一二组接近力竭时轻微辅助的既往说明保留，不扩写为每组均辅助。

10月2日两段跑：17:41第一段2.28km／14:26（866秒），配速6:20/km，腕式均心率133／峰值148bpm，负荷9，平均功率183W／峰值235W，步频179／峰值186，步幅88cm，触地227／最短216ms，平衡50.2／49.8%、垂直振幅9.1／最大9.7cm；爬升26.2m、下降12.7m，海拔1349.9–1376.1m，活动109kcal／总128kcal，恢复提示4小时，设备VO₂max估计52。18:04主跑7.55km／43:25（2605秒），配速5:45/km，均心率140／峰值170bpm，负荷39、ATS 2.2、恢复提示10小时；平均功率193W／峰值299W、步频182／峰值202、步幅96cm、触地227／最短209ms、平衡50.2／49.8%、垂直振幅9.0／最大9.8cm；爬升33.8m、下降64.3m、海拔1363.3–1386.6m，活动360kcal／总417kcal，设备VO₂max估计52。两段合计9.83km／57:51（3471秒）；加上午力量，全天训练1:58:27（7107秒）、活动热量759kcal／总热量917kcal，不把活动与总热量相加。结构化训练字段沿用主跑口径；力量容量及第一段全部保留文字，不把力量时长或容量混入主跑字段。

主跑逐公里6:30、6:29、6:26、6:09、6:01（前5km 31:35）、5:10、4:33，最后不足1km 2:07。前段总体稳定，末段明显加速；配速图有短暂停顿。约30分钟后心率随加速升高，不能把变化独立归因于心率漂移或直接用全天均心率评价末段强度。心率区间基础有氧31分钟、热身8分钟、进阶有氧3分钟、阈值不足1分钟、无氧0；这些为设备区间标签，不替代实测生理阈值。用户跑步体感“OK”，文字保留，feel不自动赋分；图中无持续末段掉速，平衡未明显偏移，不据此证明跑步经济性提升或整体恢复完全。功率仅记录，不解读。 手动一分钟HRR用户明确汇报181→124＝57bpm，hrr0=181／hrr1=124；均为腕式光电读数。用户认为光电延迟明显。起点181高于运动摘要峰值170；自动页面起止159／119、显示20，两种口径独立保留，自动值不填手动字段。计时是否自停止瞬间或延迟峰值开始尚未明确，暂不与历史标准停表序列直接比较、不根据光电延迟反推真实心率。

10月2日饮食：早餐未吃，起晚；午餐豆花饭，照片含米饭、豆花、煎蛋及红油花生蘸料，用户补充白米饭共两碗、蘸料吃干净；力量练后500ml含糖豆浆＋E-MASS增肌粉1.5勺＋羊奶粉20g＋白砂糖1汤匙；跑前半根香蕉；晚餐分量足的酸汤牛肉饭，牛肉足、肥瘦兼有。增肌粉按45g/勺，1.5勺67.5g≈261kcal／15.5g蛋白；羊奶粉20g≈97kcal／4g蛋白。修正后午餐1000–1400kcal、整杯练后补给650–800kcal、香蕉45–60kcal、晚餐950–1350kcal；总范围2645–3610kcal（报告取整约2650–3600），代表估值3100kcal，蛋白120g／范围100–145g。覆盖此前未补充两碗饭、蘸料全吃及豆浆加糖时的2500kcal／110g粗估，不重复累计。误差主要来自饭碗大小、蘸料含油量、牛肉重量及肥瘦、豆浆糖量；范围是品类估算，非实测摄入，不据单点确认热量盈余或蛋白必然达标。用户决定以后饮食采用图片结合文字汇报：图片判断品类和配菜，文字补充实际份量、添饭、剩余及糖量；无需额外称重。

本周结论　9月16日至10月2日，晨起指标与主观状态需按各自设备序列及当天训练情况判读。9月24日Elite RMSSD回到锁定正常带，华为夜间HRV也在设备个人区间；睡眠连续性高、时长正常。当天没有提供训练数据，且饮食估算不确定，不能据此判断训练负荷或能量是否达标。9月23日高温跑步时出现的冷汗和强烈饥饿仍需作为单独的运动中症状保留。用户回安顺后忘带心率带，后续Elite和胸带心率可能暂缺，不以华为HRV替代。 9月25日完成上午居家上肢与下午健身房腿部双练；力量内容覆盖上、下肢，心率带与Elite晨测暂缺。饮食估算为宽区间，补给按档案中每勺约45g、蛋白23%的规格计算。 9月26日睡眠8小时、评分90，夜间HRV 108ms；完成两段跑步共13.81km，用户报告跑中无负面体感、跑后明显饥饿，手动一分钟HRR下降40bpm（仅记录差值）。全天营养粗估约2750kcal、蛋白约95g，范围较宽。HRR起止心率未提供，胸带与Elite数据因未携带设备而缺失。 9月27日两段跑合计11.25km，主跑9.02km；整体体感较好但报告石板路跑步膝盖不适，侧别与跑后持续情况未知。手动一分钟HRR下降29bpm，仅记录差值。当天营养粗估2500kcal、105g蛋白，毛豆按连壳重、腐竹按卤好湿重处理；体重已补录，见下文。 9月28日完成胸腹核心训练：华为1:20:54、均心98、峰值142、负荷7；KeepStrong容量4300kg，卧推最高60kg×8，App估算1RM约76kg。该组是否受助未明确，不能据此确认独立力量提升。全天饮食粗估2950kcal、135g蛋白；晚间加餐使用卤好腐竹湿重和毛豆连壳重口径。该日饥饿感不单独用于判定能量缺口。 9月29日睡眠7小时51分、评分85、夜间HRV 104ms，均在设备个人范围内；Elite晨测仍缺。体重61.65kg（10:23）；背部训练1:10:04、容量8220kg；饮食粗估2800kcal、110g蛋白。晚间仍有6–7/10头痛，午餐时曾有十多分钟可逆视觉异常，已建议今晚就医，未获就医或恢复反馈。 补录体重：9月27日上午61.40kg；9月28日晚间62.35kg。后者因测量时段不同不与晨重直接比较。 9月28日缺失睡眠已补齐。9月30日两段跑合计12.19km，头痛未加重但明显易累，未就医；症状恢复情况及营养标签见当日记录，未确认诊断或CNS疲劳。 10月1日头痛已消失，用户明确完全休息；回安顺后每天晨起精力充沛，9月30日跑中易累不扩写为持续全天疲劳。当天自助火锅份量未称量，饮食仅作低置信度粗估。 10月2日肩核心力量＋两段跑，跑步体感OK、后段加速，手动一分钟HRR下降57bpm但起算口径待明确。饮食经补充两碗饭、全部蘸料和含糖豆浆后修正为3100kcal／120g蛋白，保留估算范围。安顺极限重量有朋友辅助，不当作独立成绩。

本周每日数值见 训练数据集.json（2026-09-10 至 2026-10-02）

### 9月9日｜右肩再撤一项限制，与一条填补空位的新假说

右肩处方再撤一项：本日引体向上与宽距高位下拉均为正握，即内旋位，正是 8/20 处方明确要避开的体位；下拉还创了 47kg 新高两组，全程无感。这是第二份阴性证据，且比 9/2 更有针对性——9/2 测的是推举与蝴蝶机，属开链推，没测内旋位牵拉。据此撤销「引体与高位下拉用中立握或反手」，恢复正常握法。承重闭链限制继续保留，仍未测过。

用户提出新假说：肩部症状与侧卧压迫有关——训练产生疲劳，夜间侧卧压迫，次日晨起明显。这条填补了一个一直空着的位置：8/20 原始描述里就有「晨起明显」，记录端此前未处理这一点，一直只往肩峰下间隙与外旋肌群耐受度上推。首个数据点的形式很干净：本日训练为双侧对称负荷（下拉、划船、引体、面拉均双侧同重），唯一的左右差异是清晨左侧卧压了一段时间，结果左肩有感、右肩无感。用户入睡时平躺，后半夜或临醒时才翻身侧卧，时点与「晨起明显」相符。两条限制必须标注：一是回忆偏倚——睡姿是在假说提出之后回想的，往后要先记睡姿再记症状，顺序反了不算数；二是它只解释得了一部分——8/20 原始描述是「晨起明显、全天持续」，压迫解释不了后半句，旋前诱发／旋后不痛的方向特异性也不是压迫能产生的，8/26 平板支撑那次更是白天诱发。故定位为调制因素，不是成因，两者可以并存。证伪条件：出现「睡的侧别与次日有感侧别不对应」或「平躺整晚仍晨起有感」，该假说出局。

体重读数作废：09:45 显示 62.4kg，但体成分分项缺失，无法做拆分闭合校验，且用户报告称重设备异常；该值较前日高 2.35kg、较序列最高点仍高 1.65kg。不入 08 点档序列。因此 9/8 那条可证伪预判判为「未能检验」，既非成立也非失败——判定它需要一个同口径的有效读数，今天没有。Elite 76.91（z=−1.32），带内偏下但未越界；0 伪迹，SDNN 与总功率的差额 1332 为近期最小之一，干净样本。这个位置与前日负荷相符：9/8 心率 142、负荷 72、恢复 13 小时为有氧课最重一次，且当日摄入 2300 为 8/22 以来最低。睡眠是近期最好的一晚：深睡 35%、连续性 100 满分、觉醒 0 次、评分 84；但时长仅 367 分钟，入睡时间连续第三日落在 00:39–00:53，潜伏期那个问题没动过。背日 lite 版：容量 4777kg 在背日序列里排第三，只是时间上 lite，强度不是——下拉 47kg 两组为重量新高。本日无硬拉，膝关节未吃轴向负荷（是赶时间的结果，非为膝盖设计）。9/10 订正：原记「为背日首次」无依据，该判断来自 flag 字段检索，而 flag 不是动作清单，撤销。营养约 3022kcal、蛋白 172g，热量正压在目标上，但蛋白约 2.9g/kg、超上沿 57g，这部分基本无效，换作碳水更有用。下午茶连续第四日为鸡胸加坚果约 222kcal，该时段形态已稳定。

本周结论　晨起明显这四个字从 8/20 就写在档案里，一直没人解释，而我一直在往结构性机制上推。今天这条假说不一定对，但它至少去解释了那个被绕开的地方。

本周每日数值见 训练数据集.json（2026-09-09）

### 9月8日｜左膝命中就医触发条件

左膝第三个点，且第一次在低负荷情境下出现：跑步过程中有感觉，跑完即消失，提速时反而没有感觉。按 9/6 所立的触发条件，"跑步中出现"单独一条即成立，本日命中。与 9/5 机制的一致性被削弱——9/5 是伸膝力矩最大那一瞬间疼痛，若同源，提速时负荷更大本该更明显，实际相反；故不再沿 9/5 那套机制往下推断。9/6"问题只在轴向高负荷下出现"的结论被本日推翻。本日三个变量同时改变：换回 Adios 9（9/6 为 React）、配速快 25 秒、心率 142 为有氧课历史最高且含 Z4 3 分钟，单独归因不了任何一个。9/6 那趟（React、6:23、心率 136、全程无感觉）是目前唯一干净的对照点。这条线现有五个点：8/24 硬拉撑不住无痛、9/5 深蹲 55kg 痛、9/5 降 50kg 无异常、9/6 跑步无感觉、9/8 跑步中有感觉。9/12 计划的 24km 在四天后，时长约为本日的 2.7 倍，且落在已出现症状的"跑步中"情境；事实与时点已告知，由用户权衡。

Elite 86.42（z=+0.19）回到带内，较 9/7 涨 14.95ms；HF 功率 2187.19 由前日的 1126.46 翻回，LF/HF 由 3.37 降到 1.34，迷走那一侧确实恢复了，0 伪迹。但用户把它归因于"提前入睡"，数据不支持：昨晚 00:00 上床，实际入睡 00:49，比前夜的 00:39 还晚 10 分钟；时长 390 对 381 分钟只多 9 分钟；结构反而更差——深睡 18% 仍低于下限、REM 8% 跌破下限、浅睡 74% 为序列第三高（9/10 订正：原记「序列最高」错误，8/6 为 76%、8/14 为 75%）、觉醒 2 次。恢复是真的，但"睡得更早、更久、更好"这三样今天一样都没发生。同日为完全休息日，是另一个同等强度的候选；但 9/4 同为休息日而次日 Elite 是 72.12 的低值，休息日本身也不能单独解释。真正卡住的是入睡潜伏期 49 分钟：上床提前约一小时，入睡只提前了有限一点，多出来的时间花在卧床未眠上。若目标是增加睡眠时长，该动的是潜伏期，不是上床时间。

跑步 9.44km、5:58、心率 142（有氧课历史最高；9/10 订正：原记前高为 9/1 的 140 错误，前高为 7/29、7/30、8/1 的 141）、功率 184W，负荷 72、恢复 13 小时；含 Z4 3 分钟、Z3 5 分钟，第 6 公里 4:34，非稳态。形态：触地 235、垂振 9.0、步频 181、bal 50.1。HRR 167→132（21.0%），与 9/3 相同。体成分 60.05kg（+0.15），闭合；08 点档六个读数 59.85/60.35/60.55/60.75/59.90/60.05。答用户两问：一，体重能否涨，现有数据答不了——端点算 7 天 +0.20kg 恰落在目标区间，但六个散点标准差约 0.36kg，换起止点可得 +0.90 至 −0.85 的任意结论，效应小于噪声；再记约 8 天才有首个 7 日滚动均值，期间不改摄入。二，摄入够，且蛋白偏多——8/31–9/7 八日均值 3110kcal／135g，较 8 月的 2705 高 405/天，按日型累计盈余 +2126kcal、日均 +266，蛋白约 2.25g/kg 连续超上沿。本日营养约 2300kcal／蛋白 109g，为 8/22 以来最低，较目标低约 650，而今天恰是输出最大的一天——最高输出配最低摄入。练后补给为缩水版，未加燕麦与葡萄糖，碳水侧基本空缺，与 8/31 那次同形态。可证伪预判：次日晨起体重大概率下降且主要落在水分侧；若反而上涨则本判断为错，照记。

本周结论　9/6 立的就医触发条件今天成立了，而且成立的方式和当初设想的不一样——不是重负荷下更痛，是低强度时有、提速时反而没有。这说明按 9/5 那套机制往下推是没有依据的，推断到此为止。

本周每日数值见 训练数据集.json（2026-09-08）

### 9月7日｜三条通道第一次同时指向一个方向

Elite 71.47（z=−1.84）再度跌破离群线，三天内第二次，且比 9/5 那次更低，中间 9/6 曾回到带内。这次的证据和 9/5 不同：HF 功率 1126.46 是近五日最低（前四日 2013、2109、1910、2351），LF/HF 3.37 为近期最高。HF 与 RMSSD 同属迷走指标，两个一起掉，方向自洽，判为副交感活动真实下降，不是算法或伪迹。平均 RR 1134.40 对应心率 52.9，与 9/5 的 1134.97 几乎相同。

睡眠深度是这批数据里最差的：深睡只有 16%，跌破 20% 参考线，与 8/6、8/12 并列全部记录第二低，最低为 8/14 的 14%（9/10 订正：原记「仅高于 8/14」漏掉两个并列值）；连续性 70 贴在下限；浅睡 68% 偏高但非序列最高（9/10 订正：原记错误，8/6 为 76%、8/14 为 75%）。但时长 381 分钟、觉醒 0 次、REM 16% 都正常——是深度不够，不是睡不着。三条独立通道首次同向：用户主观报告很累、晨起 RMSSD 越界、睡眠深度不足。此前数日反复确认的是"睡眠差而 HRV 正常"，今天是两者一起低，更可能有一个共同上游——9/5 腿日 7858kg（腿日次高）、9/6 跑步 9.42km，加上连续多日伏案到深夜。对照 8/25–8/28 那轮（z 在 −3.1 至 −3.2、连续三日不回升），本次尚未到那个程度。用户决定完全休息并争取 00:00 前入睡，数据支持该处置，记录端未提出修改。

体成分 59.90kg（08:32），较 9/6 降 0.85，且口径一致（08:37 对 08:32）。分项：水分 −0.54、蛋白 −0.20、脂肪 −0.10、骨矿 −0.01，64% 为水分。08 点档序列 59.85→60.35→60.55→60.75→59.90，此前的单调上升中断。营养约 2984kcal、蛋白 151g，较休息日目标高约 584；蛋白约 2.5g/kg，为记录中较高的一次。下午茶连续第二日为鸡胸加坚果、同为约 222kcal，该时段开始出现固定形态。晚餐 10 个炸鸡翅脂肪量较大，与§9 睡前 3 小时高脂禁相关，已提示留足间隔。

本周结论　前几天反复说的是 HRV 不跟睡眠走，今天不一样：主观、自主神经、睡眠深度三条线一起往下，更像它们共用了一个上游，而不是互相驱动。

本周每日数值见 训练数据集.json（2026-09-07）

### 9月1日–9月6日｜三条受限的判断，与一次顺带完成的阴性测试

| 日期 | 训练 | Elite (z) | 睡眠 | 摄入 | 当日要点 |
|---|---|---|---|---|---|
| 9/1 | 有氧 9.39km 5:50@140 | 89.82 (+0.60) | 435min 深34% | 3850 / 180g | 配速为当时序列最快，但含阈值段、净降 24.9m，不作有氧能力提升结论。斜方肌 DOMS 分布左右不对称（右上束／左中下束），合并假说「疲劳提供时机、右肩提供方向」。首次超过热量目标。 |
| 9/2 | 肩胸 6416kg | 89.99 (+0.61) | 374min 深28% | 2825 / 122g | 右肩阴性测试，撤销开链推举限制（详见§2）。颈段不适首次出现。体重 +0.50 中 66% 为水分。 |
| 9/3 | 有氧 9.31km 5:53@136 | 88.83 (+0.48) | 431min 深27% | 2740 / 106g | 右肩两周处理期到期。晚餐占比降至 38%，「晚餐占全天近半」模式按 8/24 起的计数首次中断。模块材料到手，按实拍标签替换通用估值。 |
| 9/4 | 休息 | 79.33（污染） | 548min 深30% | 2732 / 108g | 测量中发笑，SDNN 117.78 高而总功率 4322 低、SDNN²−TP 差额 9550 为历次最大，标为污染样本不采信。由此暴露污染判据缺陷：现行规则要求两者同高，本例一高一低反而不算污染，建议改用差额，待定。睡眠 548 分钟为全部记录最长。 |
| 9/5 | 腿日 7858kg | 72.12 (−1.75) | 392min 深30% | 3720 / 135g | 8 天来首次越界，且为干净样本（0 伪迹、差额 1533 最小）。深蹲 55kg 伸膝瞬间左膝痛，当场停、降 50kg 完成 7 次无异常。下午茶为 890kcal 高糖，15:30 模块未按设计执行。 |
| 9/6 | 有氧 9.42km 6:23@136 | 87.00 (+0.26) | 375min 深30% | 3500 / 144g | 越界为单日事件，一天补回 14.88ms；当晚睡眠为近期最差而 HRV 照常回升。依§3 React「保护性备选」条款换鞋，形态三项同时轻微变钝，属换鞋预期效果。 |

本周的主线是三条判断各自受限，以及一次被自己测掉的处方。9/1 想分离排精那个变量，结果当天既无上午背日也无排精，两个变量同时撤除，测试不成立；9/5 的越界样本干净但只有一个点；9/8 之前对左膝「只在轴向高负荷下出现」的结论，也在本周之后被推翻。相反，9/2 那次右肩的阴性测试不是设计出来的——它是在一节正常安排的高容量课里顺带完成的。

本周确立的两条规则：一是模块材料 9/1 才下单，此前记的「模块未执行」属条件不具备而非执行缺失，9/3 订正并把起算点顺延至材料到手日；二是体成分的脂肪分项不可读——9/2 与 9/3 两日累计 +0.27kg，而按能量平衡只应约 +0.10kg，实测为 2.7 倍，9/2 那句「与盈余吻合」判为巧合。称重口径在 9/4、9/5 两日跑偏（10:21、09:26），9/6 起拉回 08:30 前后。

本周结论　测试条件必须在开跑之前定好，事后再想分离已经来不及；而真正有结论的那次测试，恰恰不是专门设计的。

本周每日数值见 训练数据集.json（2026-09-01 至 2026-09-06）

### 8月31日｜同一天出现四个正向因素叠加的一次异常表现

当日上午背日，硬拉顶组 60kg×8，均心率114、峰值178为力量日历史新高。前一夜与再前一夜入睡均超过01:00，REM 连续两日跌破10%（6%、9%），当晚用户确认前夜出现失眠。晨起 Elite 89.87 仍落在锁定常态带内，睡眠碎片化未影响自主神经指标，与此前判断一致：近期压制 HRV 的主要是身体应激，非单纯睡眠时长不足。

傍晚有氧课出现本月最优组合：配速6:00、均心率134，触地232ms、步频182、垂直振幅8.9，三项跑姿指标均为近期最佳。全程含冲坡段，峰值心率179、峰值功率462W。HRR新口径161→118（归一化26.7%），为该序列五个样本的最高值，前四个依次为19.0%、23.1%、23.5%、24.8%，呈持续上升趋势。

当日同时具备四个可能解释：更换为 Adios 9（此前两次穿 React）、气温转凉、训练前排精后洗澡、以及有氧适应基础的持续积累。四者对本次表现的预测方向一致，按共线性判定无法从单次观察中分离主因。排精一项目前证据有限——运动科学中关于射精间隔与运动表现关系的主流结论是间隔2小时以上无显著影响，不构成已确立的表现提升机制，仅在当日精神紧绷的前提下作为催乳素上升、交感张力下降的间接路径列为候选。分离方案为后续同等条件下不排精复现测试。

同日另有两项与训练表现无关的记录。其一，肛裂自 8/26 起，8/30 大幅好转，处理为每晚睡前温水坐浴，恢复期内日常饮食持续含辣、未作限制。该观察不构成「辣不影响愈合」的验证——没有对照组，能说的只是本次的辣摄入量未阻止愈合在四天内发生。腹内压相关的动作限制随之撤销。其二，核查§9膳食计划时发现其宏量目标与热量目标在算术上互不相容（详见§9修订说明与§7），8 月的热量未达标记录因此有一部分不是执行问题，而是目标不可达。

本周结论　晨起认知层面的迟钝（睡眠惯性、REM不足）与自主神经/心血管的恢复状态是两套系统，不能用其一预测另一。本周首个训练日的表现印证了这一点——晨起状态不佳，当日晚些时候的运动表现反而是近期最优。

本周每日数值见 训练数据集.json（2026-08-31 起）

### 8月24日–8月30日｜大负荷后连续五天低于常态带

周一背日，硬拉 70kg×3 创个人纪录，容量 10260kg 为有记录以来最高。末组出现左膝支撑不足、左大腿张力维持困难，主动终止上举，无痛感，48-72 小时观察窗内无延迟症状。归入左侧信号线，为该线首个负荷下的功能性实证，此前四条均为被动观察。

次日晨起 Elite 降至 62.91（z=-3.21），跌破锁定基线下侧离群线，静息心率同步上升 8.5bpm。按既有判据，心率同向即不作测量波动处理。此后 8/26 短暂回升至带内，8/27、8/28 再度跌出，连续三天处于离群线之下。同期叠加两项非训练因素：8/25 起连续三日腹泻，8/26 起肛裂，排便撕裂痛伴少量鲜血。8/28 睡眠为该批最佳（8h10、深睡 36%），HRV 未跟随回升。

8/29 的读数排除了两个候选。当晚 01:30 入睡、总时长 6h59，睡眠条件劣于前一日，Elite 却回升至 84.42（常态带正中），静息心率回落。睡眠因此不成立为限制因素；训练负荷同样不成立——8/28 的大重量腿日之后仍能回升。剩余候选为腹泻失水、电解质流失与肛裂的持续躯体应激。该归因为回溯性，无法逆向证实，但与五天窗口内的时间线吻合。同日 HRR 掉 41bpm（24.8%），四个新口径样本落于同一窄带，与 Elite 共同确认本轮结束。

8/28 腿日在带外第三天执行。深蹲 60kg×2，较 8/21 同重量的 5 次减少 3 次；均心率 115bpm 为力量日历史最高。

8/30 转为完全休息日（原计划练背，取消），为 8/8 起第三个完全休息日。当晚 REM 降至 6%（24 分钟），为该批最低，同时觉醒 3 次、入睡 01:22，连续第二天超过 01:00。Elite 79.86 仍在常态带内。晚餐摄入 450ml 可乐，含糖与咖啡因均可能是当晚入睡延迟的候选因素，与本周腹泻/肛裂恢复期对糖负荷的提醒属同一逻辑。

本周结论　大负荷后 HRV 数日不回升时，优先排查非训练因素。本轮的主要驱动为腹泻与肛裂，非训练负荷本身。

本周每日数值见 训练数据集.json（2026-08-24 至 2026-08-30）

### 8月17日–8月23日｜右肩症状出现，处理方向为调整结构

8/17 肩胸日，前中束动作合计 16 组，后束 0 组——面拉因龙门架故障未执行。数日后出现右肩晨起疼痛：外展 20-30 度做前屈时诱发，全天持续，被动活动不痛，活动度主观正常。自测得出一项特异性规律：前臂旋前位（手心向下）痛，旋后位（手心向上）完全不痛。

该规律缩小了范围。旋前时肱骨内旋，肩峰下间隙变窄，指向该处结构，与此前假设的肱二头肌长头腱方向相反——后者在旋后位应更痛。背景线索：8/7 打球 3.5 小时（停练两年后首次）后冈下肌 DOMS 持续 6 天，该肌群功能为上抬时下压肱骨头，其耐受度不足与当周前后失衡共同构成可能成因。

处理为调整训练结构而非休息：停用过顶推举、蝴蝶机深行程、健腹轮；引体与高位下拉改中立握或反手以避开内旋位；面拉提前并增至 5 组。8/23 背日全程未诱发肩部症状。

8/21 修正健腹轮技术。原执行为仅手臂推出、躯干不跟随，导致肩在末端屈曲位等长承载；改为躯干随轮前移后，次数由 3 组 19 次增至 4 组 31 次，负荷转移至腹直肌与腰椎一带。风险观察点随之由肩迁移至下背。

本周结论　肩部前后侧训练失衡不会因休息缓解，需补足缺失侧。面拉为当前该线最优先动作。

本周每日数值见 训练数据集.json（2026-08-17 至 2026-08-23）

### 8月10日–8月16日｜识别出第三类晨测污染源

8/16 晨测 Elite 57.09ms，跌破 ±1.5SD 离群线。查明为操作问题：当日先洗热水澡，五分钟内完成测量。热水浴使皮肤血管扩张、心输出量重新分配，交感张力代偿性升高，该状态下的 RMSSD 不反映恢复水平。此前仅登记两类非应激污染，本次为第三类。

判别依据比数值本身更具价值：当日坐姿与平躺 RMSSD 数值相同。正常状态下平躺应明显更高（体位反射所致），两者趋同即提示交感张力异常偏高。该判据不依赖与历史值比较，可当场判断。晨测前置条件因此补齐为三条：开灯前、洗澡前、不紧邻急性唤醒事件。

8/15 为该月状态最佳一日：睡眠 8h24、评分 90、Elite 98.36ms、睡眠心率 44bpm 四项同时最优，10.09km 跑出近期最低均心率 134bpm，主观体感与客观数据一致向上。同一周内出现最佳与最差两个读数，差异来源为测量方式与睡眠，非体能变化。

本周结论　数据异常优先排查测量过程。坐姿与平躺 RMSSD 趋同是识别交感张力偏高的现场判据。

本周每日数值见 训练数据集.json（2026-08-10 至 2026-08-16）

### 8月3日–8月9日｜能量赤字导致输出下降，闭环验证

8/7 切伤左手拇指桡侧，出血较多并伴一过性头晕，当日腿日取消。下午打乒乓球 3.5 小时，为停练两年后首次，对手为削球手。次日冈下肌、背阔上部、肩后束出现强烈 DOMS，主观强度超过历次背日。该薄弱环节在三周后的右肩问题中再次出现。

8/7 当日早晚两餐均以蛋白粉顶替正餐，全天约 69-71g 蛋白、1600-1800kcal，为膳食计划执行以来首次未达标。8/8 跑步即反映出来：同为 140bpm，配速由 6:23 降至 5:59（补足后），功率 179→187W，两项同向。补足一天即回弹，时间尺度符合糖原再充填，能量赤字为输出下降主因由此闭环。

据此新增应急方案条款：不得以 E-MASS 等训练补给粉充当正餐。该品碳水蛋白比约 3:1，蛋白效率低、碳水冗余，属补给非正餐。替代方案为即食鸡胸、卤蛋、纯牛奶等无需坐下即可摄入的选项。

本周结论　配速下降优先核查摄入是否达标，其次才是疲劳。补给粉不可替代正餐。

本周每日数值见 训练数据集.json（2026-08-03 至 2026-08-09）

### 7月26日–8月2日｜基线建立期

本周开始系统记录睡眠、晨起 HRV 与训练数据，作为后续全部判断的基础。两台设备关系于本周定性：华为夜间 HRV 为整夜滚动均值，Elite RMSSD 为晨起清醒静息即时值，属两个不同变量，只能各自追踪趋势，不可直接换算或求差值。

8/1 夜间 HRV 创新高，而 7/31 刚完成接近正常强度的硬拉训练，与「下肢重训压低 HRV」这一既有规则相悖。当时未强行纳入既有框架解释，原样留存为反向观察。该处理方式此后成为惯例：反例照原样保留，不默认符合既有规律，也不据单次反例改写原规则。

本周结论　两台设备测量的是不同变量。反例原样留存，不急于解释。

本周每日数值见 训练数据集.json（2026-07-26 至 2026-08-02）

##   7    核心生理认知

### 并行训练干扰效应（表型选择性模型，2026修正）

干扰效应是表型选择性的，不是二元开关：最大力量（SMD −0.06）与肌肥大（SMD −0.01）几乎不受影响，唯独爆发力/功率被显著削弱（SMD −0.28）。原"力量激活mTOR、耐力激活AMPK、两者相互拮抗"的模型不成立——真实机制是残余疲劳、核糖体生成与线粒体生成的能量带宽竞争、神经募集效率下降等多因素叠加；转录组学证据（Zhao 2026）显示并行训练反而下调了泛素-蛋白酶体系统、抑制了肌生长抑制素，分子层面并没有"有氧锁死增肌信号"这回事。（Schumann 2022／Held 2026／Zhao 2026，7月10日核实）适用边界：仅适用于产生真实机械张力/代谢应激的抗阻训练（如 ≥70%1RM 复合动作），不适用于姿态神经再教育课那类刺激（弹力带＋3kg哑铃＋自重核心、均心率103bpm），后者不构成两条通路竞争的前提。本人实测：停止下肢重训后 HRV 由 83-89ms 持续攀升至 111ms，下肢重训是 HRV 最大的单一 CNS 压力源。2025年11月纯 LSD 特化期 HRV 94ms、触地203ms、80%强度3:32/km 无疲劳感；2026年双线并行则换来更强的功率上限与后链力量储备。

### 并行训练操作性指导（基于三文献实证）

真正的抗阻训练日与跑步质量课同天时：①间隔≥3小时可显著降低对爆发力的同日干扰(Schumann)，≥6小时进一步降低残余疲劳(Chen 2024)，理想情况下最耗神经的力量课与最耗强度的跑步课分开不同天；②同日无法避免时，力量课放在前面对力量/肌肥大保护更有利(Eddens 2018；Held的RT-before-ET趋势SMD 1.69/0.83，但p值未达显著，视为合理默认而非铁律)，若当天有关键阈值跑/比赛配速跑等优先级更高的跑步课，则应反过来先跑后力量；③力量训练维持重负荷低次数(≥80%1RM)对跑步经济性有小幅正向帮助(Llanos-Lagos 2024)，不是纯粹拮抗，与现在的维持计划方向一致；④爆发力/增强式动作对干扰最敏感，应安排在身体最新鲜(未受疲劳影响)的状态下进行。

### "换挡感"与摄氧量动力学

提速后氧亏窗口→心肺追上→有氧系统接管→心率回落、主观变顺。是热身完成最可靠信号。凉爽天气（23°C以下）换挡更清晰——散热不竞争心输出量。高温时换挡过程混沌延长。比赛热身必须等此感出现再执行PAP。

### PAP（赛后激活增强效应）

高强度收缩后肌球蛋白轻链磷酸化升高→同等神经信号触发更强收缩，持续8-15分钟。黄金窗口：激活后休息8-12分钟。

比赛热身流程（PAP 激活）

| 步骤 | 动作 | 要点／时长 |
|---|---|---|
| 1 | 慢跑热身 | 慢跑至出现「换挡感」（有氧系统接管信号：心率回落、主观变顺） |
| 2 | PAP 激活 | 3–4 组 100m 渐进加速（触发肌球蛋白轻链磷酸化） |
| 3 | 休息激活窗口 | 8–10 分钟（黄金窗口 8–12min；PAP 效应持续 8–15min） |
| 4 | 出发 | 正式起跑 |

### 超量恢复机制

刺激→功能下降→超量补偿→能力高于训练前→无新刺激则回落。峰值通常在刺激后5-7天。"闲不住"感是急性神经兴奋性峰值（48h消退），HRV代表的ANS深层储备（平静的充裕）可持续数天。4月17日100ms和4月30日111ms分别验证了这个模型。关键教训（4月18日）：峰值当天应立刻执行测试，而非严格遵守日历。

### 衣物/温度对心率的影响

4月21日自然实验：相同配速6:20/km，穿加绒长袖→心率144bpm，脱掉→135bpm（差9bpm）。机制：散热与骨骼肌供氧竞争心输出量。比赛应用：气温升高时心率系统性偏高，应以RPE而非绝对心率为配速参照。

### 糖原耗竭与撞墙机制

5月7日模拟赛实测：第15km配速从4:13/km跌至4:46/km（慢35秒），但心率从168bpm同步降至162bpm——"配速降+心率降"是周边性疲劳的典型指纹，证明限制因素是糖原底物而非心血管能力。补充160g面包后配速立即恢复至4:11-4:14/km。结论：你的有氧引擎足够强，但需要持续供给燃料。三颗能量胶方案直接针对这个问题。

### 结缔组织适应 vs 肌肉适应（新鞋适应期核心认知）

渐进负荷、留恢复窗口、试探当前阈值——这套逻辑对肌肉和结缔组织通用，但两者适应机制有本质区别。肌肉的疲劳信号是实时、剂量依赖、可预测的：DOMS在24-48h内如约而至，可作可靠的实时刻度，允许"推到有感觉再退一步"。但足底筋膜、跟腱这类结缔组织的胶原蛋白代谢周期以周甚至月计，损伤信号非线性、常"沉默积累后突然爆发"——今天无感不代表没有微损伤累积（Adios 9右脚"昨天撕裂痛今天零感觉"、飞电6C首跑后跟腱紧绷均为此机制）。实操含义：结缔组织适应不能依赖当下无痛判断安全，应以连续多天无症状为滞后指标，升量节奏比想象中还慢一档，把"探测"（低强度试跑）和"验证"（同强度多日稳定无症状）分开。

### 心率回落作为外周疲劳指标（HRV盲区）

7月初Adios 9连续跑量期实测：心率回落连续三天下滑（6/30=21→7/1=20→7/2=18bpm），同期夜间HRV却横盘稳定在81ms。这个反差揭示——心率回落（副交感再激活效率）能捕捉到HRV尚未反映的外周肌肉骨骼层面疲劳积累，而夜间HRV主要反映中枢ANS状态。当HRV表面稳定但心率回落逐日走低时，应判定疲劳正在外周层面积累，及时降量。启示：HRV不是唯一决策变量，心率回落趋势+局部组织信号（如足底反应）在结构性负荷判断上更灵敏。Polar H10晨起静息数据引入后，可进一步交叉验证中枢与外周疲劳的分离。

停训流失周期的实测验证（8月1-2日）：结论是 1-2 周停训对本人的力量素质与肌肉维度未造成有意义的实质影响，可作为后续减量期决策的经验参照。7/31 停练背部两周后首次尝试接近正常强度训练（硬拉新高、面拉40kg×5），次日与次次日 DOMS 均为 barely noticeable 级别且持续减轻，未出现异常延迟性酸痛或表现下降。与 detraining 文献方向一致——力量在多数研究中需 3-5 周才显现下降，肌肉横截面积多需 8 周左右。

### 光电 vs ECG 测量差异与心率回落双相机制

Polar H10（ECG）响应速度秒级，在冲刺、心率回落、突发变向躲避等心率变化率快的区间远超华为Watch 5（光电）；稳态跑且环境适宜时两者偏差不大。关键认知修正：两设备测的是同一条真实心率曲线，理论应趋同，所谓"谁偏高偏低"不是固定系统偏差，而取决于测量时曲线处于加速/减速/平台的哪个阶段——光电算法在变化率快的区间因平滑/外推产生滞后与欠冲（例：PAP激活后真实心率进入107-110bpm平台，光电因"下降惯性"外推显示为100bpm）。往后量化偏差须分场景记录（稳态/冲刺瞬间/回落瞬间/静息平台），而非找单一偏差值。

心率回落双相机制（神经调节 vs 体液调节）：运动后心率回落分两相。第一相（前30-60秒）迷走神经重新接管，快速、精确、短暂，属神经调节特点。回落至平台后不再继续下降，由循环中儿茶酚胺（肾上腺素/去甲肾上腺素，半衰期分钟级）的清除速度决定——即使神经已放松，残留激素仍刺激心脏β受体维持一个高于静息的平台，体现体液调节"弥散、持久、缓慢"的特点。Polar H10 因 ECG 零延迟，能准确捕捉这条"快降后进平台"的双相真实曲线。

恢复心率（HRR）的统计口径辨析（7月29日核实华为官方口径）：华为运动健康显示的"恢复心率／Dropped"不是"停表瞬间到1分钟"的降幅，也不是起止心率的简单相减，而是固定2分钟检测窗口内的平均每分钟降速，即（运动结束心率−2分钟后心率）/2，显示时向下取整。实例：7/29跑后161→124bpm，(161−124)/2=18.5，显示18bpm/min。关键含义：巅峰期的27-33bpm与半马的27bpm同样出自华为 Watch 5（Polar H10 为7/4才到手），与7/29的18bpm/min 属同一套2分钟窗口算法，不存在跨口径问题。读法：对照通行参考标准（第1分钟应降30-50次、其后每分钟降15-25次）时应看曲线形态而非单一均值——7/29曲线为前1分钟降约30bpm、后1分钟趋缓至124的典型健康双相形态。手动1分钟掐表值是另一套口径，7/30起单独起算，见本节"HRR口径变更"。

静态 HRV（RMSSD）的精度维度（7月18日新增）：以上讨论的是心率曲线的动态响应速度差异；另一个独立维度是静息 RMSSD 本身的计算精度。已发表验证研究显示，胸带（ECG原理，如 Polar H10）对比金标准心电图的 RMSSD 平均绝对百分比误差仅 2.16%，而智能手机/腕部 PPG 应用达 17.49%，且一致性区间更宽；另一项针对 WHOOP 腕戴设备的验证发现，腕部 PPG 测得的 HR/HRV 变异系数（10-11%）本身就大于其测量偏差，说明日常波动噪音相当可观。结论：华为 Watch 5 的整夜均值 HRV 因样本量大（整夜连续采样）适合捕捉长期趋势方向，但绝对数值精度明显低于 Polar H10 晨起单点 RMSSD——这是"华为看趋势、Polar+Elite 看当天锚点"两轨并行协议成立的底层精度依据，而非仅凭经验形成的权宜安排。

### HRV升高≠恢复更好：功能性过度训练的副交感异常偏高（7月13日新增）

HRV 并非越高越好。Le Meur et al. 2013（Med Sci Sports Exerc）对21名铁人三项运动员的对照实验显示，3周超负荷训练后运动员表现下降（最大递增负荷测试成绩 −9.0%），但静息副交感活动却进行性升高，这种"副交感神经过度活跃"是功能性过度训练（F-OR）的特征性信号，后续多项研究重复验证。机制推测：升高的静息副交感调节可能是身体限制运动时交感参与程度的代偿，伴随最大心率下降与运动表现能力降低。判别方法：HRV 单一数值不能孤立解读，须结合睡眠结构（深睡/REM是否正常）、静息心率是否同步下降、主观体感是否真实轻松，三者不一致时按保守处理。实测对比：7/12 夜间 HRV 100ms＋晨起 RMSSD 99.23ms 高度重合，但当晚深睡18%(Low)＋REM 8%(Low)＋觉醒3次＋主观疲惫，更符合 F-OR 模式；7/13 晨起 RMSSD 104.39ms 创新高，但睡眠结构本周最佳（深睡32%＋REM19%＋0觉醒）且有明确降温解释，更符合良性反弹。同样是"HRV创新高"，背景数据不同，结论方向相反。

第三、四个案例（7月26日、7月29日）：华为夜间 HRV 连续触顶（7/26=110ms、7/27=102ms、7/29=106ms），发生在感冒收尾期，而同夜其余指标全部落在个人正常区间内（睡眠HR 49bpm、SpO2 96%、呼吸14brpm、深睡31%、总时长7h13、觉醒1次），且无急性应激事件、LF/HF仅2.17，测量情境干净，不属污染样本。按本节框架不解读为"恢复得特别好"。文献参照：Schneider 等（Frontiers in Sports and Active Living, 2021）对一名精英耐力运动员完整病毒性上呼吸道感染周期的追踪显示，HRV 在感染期下降、随后回升至病前水平并连续数日维持偏高，作者建议以该"偏高期"作为可恢复训练的信号。该文为单一个案报告（n=1），病原体与个体条件均不同，仅作方向性参照，不作确证。

本轮夜间 HRV 偏高的多因归因（8月2日建立，8月8日合并，8月20日结案转为被动观察）。需要解释的现象：本轮并非全程高于区间。轨迹为起病当晚101ms→7/22跌至70ms（本轮谷值）→逐日爬升→7/26起在上限附近震荡→7/30-7/31回落进区间→8/1创历史新高117ms→8/4回落至78ms→8/5-8/8在94-101ms震荡。要解释的是"后半程反复触顶并二次抬升"，不是一个持续性的高位平台。已确认①：参考区间自身在滚动漂移（实测62-100→65-108），同一数值107ms在8/2标 Above、8/3标 Within。"Above/Below range"标签是在追一个移动靶，历史标签之间不可直接比较，属设备行为。已确认②：华为整夜均值与 Elite 晨起单点之间是稳定的正向偏移，不是一系列"背离事件"——7/29至8/7十天中华为九次高于 Elite，两条序列离散度差一倍（Elite 全程62.7-87.1ms、跨度24；华为78-117ms、跨度39）。8/4那次"收敛"是华为跌至谷底碰到了 Elite 一直所在的带，不是 Elite 升上去。证据不足、不再追：睡眠结构机械性推高整夜均值——方向成立但解释力不够，8/4与8/7是本档案最干净的一对配对样本（深睡156/155min、REM 63/58min、总时长7h38/7h25、觉醒均1次），夜间 HRV 却相差20ms，存在约20ms的未解释项；训练负荷下降致高位平台——与睡眠结构始终未能分离。两条并列维持待验证，不设分离动作，不为凑样本刻意安排训练。已排除：副交感型过度 reaching（训练量在降不在升，方向不符）；异位搏动人为抬高 RMSSD（Elite 信号质量 Good、多数日0伪迹、ECG级采样无异常）；感染后自主神经功能紊乱（体位性心悸、不成比例疲劳、运动不耐受三项均无）。

Elite Readiness 评分的一致性问题（8月6日）：结论是该评分作记录、不作决策依据，评分高低不改变对该指标的处理原则。8/6 当日 Elite 首次给出10/10并提示可加大训练强度。须以与8/1相同的标准对待——8/1该 App 给出4/10及"副交感异常升高、建议减量"，已判定其建立在被深慢呼吸污染的 LF/HF 之上而不予采信；10/10 出自同一套算法，核心仍是 Relative Balance 指针居中（LF/HF 1.20），而本节已确立"LF/HF 的交感-迷走平衡说已被否定、单日值不解读"。8/6 测量本身干净（0伪迹、LF/HF双峰分离清楚），但时域 RMSSD 76.96ms 仅落在65-104基线中段，并非记录级数值。该提示的证据强度远低于其呈现方式。

DOMS 强度不可作为训练质量指标（8月6日）：真正的指标是负荷、次数与容量密度，DOMS 强度与肌肥大/力量增长的相关性本就很弱，用其判断训练质量会产生误导。实测：8/6 晨起背部 DOMS 明显轻于7/31那次，主观产生"没练到位"的错觉，但客观数据相反——8/5背日引体辅助配重降至12kg（7/31最难档19kg）、面拉顶组40kg由5次增至8次、划船第二组加10kg，总容量持平而时长短12分钟。DOMS 减轻的机制是重复训练效应（repeated bout effect）：7/31为停练两周后首次，8/5为5天内第二次背日，肌肉已适应该刺激模式。

1分钟手动 HRR 应作归一化解读（8月6日）：绝对降幅受起始心率高低影响（起点越高回落空间越大），跨日比较时优先看占起始心率的百分比，绝对值仅在起始心率接近时才可直接比较。旧口径三条记录 7/30 161→125、8/4 154→118、8/6 166→125，归一化后为22.4%／23.4%／24.7%，三次仅差2.3个百分点，收敛程度远高于绝对值。方法论留存：异常值与已知口径缺陷同时出现时，先等一次干净复测再裁决，比当场在两种解读间硬选更省事。8/9的30.2%离群点即为一例——该次停表后延迟数秒才计时、窗口长于60秒，8/10的干净复测（22.8%）回到带内后，裁定为口径缺陷所致的测量误差，"恢复能力台阶式提升"的解读放弃。

### Elite HRV 大幅波动的判读：以静息心率是否同向为准（8月19日建立·8月29日补完）

判据：单日或连续数日的大幅波动是否作疲劳解读，取决于静息心率是否同向变动——同向判为真实信号，不同向按测量波动处理。8/17-8/19 三天 Elite RMSSD 单调下行（100.07→85.66→74.16），静息心率（由 Mean RR 换算）单调上升（46.7→49.3→52.9bpm），两条线同向且逐日推进。当时三个候选（8/17起始点本身为伪高／累积训练负荷／连续三日热量低于目标）对这条趋势的预测方向完全一致，按共线性判定不能分离其中任何一个。8/20 在热量仍低于目标、且当日叠加一节背日的情况下，Elite 回升至91.28、静息心率回落至49.4，三日下行序列终止；同期唯一明显改善的变量是睡眠（入睡由02:02提前至00:54、时长6h41增至7h28、深睡连续性由68回升至82）。睡眠因此为当前最佳解释，热量假设被削弱但不撤销（能量可得性的效应通常有滞后）。本节为被动观察，不设验证动作。8/24-8/29 一轮完整案例：8/24 晨起 109.12ms 为本档案历史最高（z=+2.68），读数干净（信号质量 good、0伪迹、睡眠正常、主客观一致），至今没有已知污染源可归因，归入"未解"而非"假"。8/25 跌至62.91（z=−3.21）且静息心率同向由46.2升至54.7bpm，按本判据作真实信号处理，归因为8/24历史最大负荷课（容量6587kg、硬拉PB）后24小时的急性应激。此后连续偏低（62.91／63.57／67.12）至8/29回升至84.42、静息心率同步回落至51.0——回升发生在睡眠条件更差的一夜，说明限制因素不在睡眠；8/28大重量腿日之后仍能回升，也排除了训练负荷持续压制。回溯归因指向同期腹泻失水/电解质流失与肛裂的持续躯体应激。该归因无法逆向证实，但与整个五天窗口的数据形态一致（HRV异常与腹泻/肛裂时间线高度重合，与训练负荷时间线不重合）。已降级：RMSSD > SDNN 的"异常排序"形态学判据（8/18建立、8/20降级为待考）。附录C的32个字段不含 SDNN，该判据从建立之日起就无法用历史数据检验；8/20 在睡眠与静息心率均正常时再度出现该排序，说明它未必指示异常状态。不新增 sdnn 字段，不再用于任何判断。

### 观察项的主动/被动分类：观察服务于人（8月20日确立）

至2026年8月20日，档案中同时挂着九项待验证或待补记事项，其中约半数需要本人改变行为或专门记忆（刻意跑匀速、课末掐表、补记动作顺序、为验证假设而调整进食量）。本人当前的主要矛盾是12月考研，训练的作用是维持状态以保障学习。档案维护由此暴露出一个方向性错误：制造挂账的速度超过了关闭挂账的速度，训练记录逐渐变成了一份数据采集工作。分类原则：①被动观察——设备本就自动采集的数据（配速、心率、功率、触地、步频、平衡、睡眠结构、晨起HRV、静息心率），记录的边际成本为零，一律照常录入；②主动配合——需要改变训练方式、额外操作或专门记忆的观察，默认不设立，除非本人主动要求。已设立的主动类观察若长期未推进，应主动关闭，且"该指标对当前核心目标无贡献"就是充分的关闭理由。体感与客观数据的定位：日常训练决策以体感为准即可；客观数据作为零成本的兜底，仅在与体感明显分离时提示。其余时候不解读、不提醒。本原则优先级高于档案中任何单项观察的推进需求。

### 颈后高位下拉的风险评估（8月14日新增·首次引入即须评估）

结论：以颈前下拉（standard lat pulldown）替代颈后高位下拉——文献上两者的背阔肌肌电激活无显著差异，而颈后版本的关节成本明显更高。握距略宽、拉至锁骨位、肘部沿身体平面下沉，目标肌群刺激等效，去掉极限外旋这一项风险。理由：该动作的风险不在负荷大小而在关节位置——完成位需要肩关节处于"外展90°＋最大外旋＋水平后伸"的复合极限位，此位置下盂肱关节前方稳定结构（前下盂肱韧带、肩胛下肌）张力最高，同时肱骨大结节与肩峰下间隙变窄，冈上肌腱与肩峰下滑囊的撞击风险上升；颈椎亦需前屈避让杠杆，对颈段有额外剪切。对本人另有两条特定关切：8/7球局后冈下肌（肩外旋肌）曾出现剧烈 DOMS 并持续6天，说明该肌群耐受度在停练两年后仍未恢复到位；"左侧信号线"记录的四条同侧观察尚未确证，上游稳定性存疑时引入极限位动作，时机不理想。本条不是禁令：8/14首次引入（33kg×8／26kg×8／33kg×8）三组无当场不适，说明当前活动度可以承受。若坚持保留颈后版本，须降至可控重量、绝不追求次数，出现肩前方弹响或酸胀时立即停止。

### 深蹲传力链：躯干刚度决定表现上限，非单纯下肢力量（8月21日新增）

结论：深蹲的表现上限由躯干刚度决定，不是单纯的下肢力量。8/21 深蹲 60kg×5（RIR 2-3）纳入能力锚点，估算 1RM 由约63kg升至约72kg（+14%）；既往同重量测试为60kg×1-2、动作严重变形、接近力竭，与本次的终止条件不同（技术失效 vs 主动保留储备）。机制：负重深蹲依赖腹内压把腹腔转化为刚性传力柱（belly breathing ＋ 腹内压提升），躯干刚度不足时力在传导链中段被"吸收"、脊柱承受非预期屈曲，是代偿失稳的根源；膝内扣与腿部发抖是髋膝被迫接管本应由核心完成的稳定任务后的次生表现。本人的主观描述与此高度吻合——既往从底部起身时"传到腹部时出现明显损耗"，8/21重测时为"腰椎下腹部自带一圈腰带"，动作全程稳定。归因排序：①核心/躯干刚度提升（主因，可解释多数增幅）；②停训后 CNS 疲劳源移除（贡献通常5-10%，不足以单独解释14%）；③力量本身衰退慢，跑步维持了下肢肌量与肌腱刚度。滑轨卷腹、健腹轮、动态死虫这类抗伸展/抗旋转的核心刚度训练与下肢主项表现存在直接因果关系，不是绕行训练；8/21同一节课完成髋外展68kg×14，臀中肌（膝轨迹控制）与核心刚度同时改善，是传力"更充分"体感的共同来源。风险提示：躯干刚度提升消除了此前"动作变形先于力竭发生"这一天然熔断机制——过去技术失效会先于危险负荷出现并迫使停止，现在负荷可能被真实压到脊柱与髋而没有早期预警。加重节奏建议每次2.5kg，不按主观储备速度推进，理由是神经适应领先于肌腱、韧带、骨的适应，当前正处于该时间差的高点。口径说明：8/28 核实健身 app 的"总重/杆"设置后发现，标准奥林匹克杠铃杆重20kg，此前记录长期少算了10kg。截至9月11日三项PB为：深蹲60kg×5（1RM估算63→72kg）、硬拉70kg×3（1RM估算68→75kg）、卧推50kg×6；其中8月28日口径修正时的卧推里程碑为8月26日50kg×3，历史值不回写。日常训练行的容量数值未逐条回溯修正——同口径内部比较的相对结论不受影响。8/28起新记录一律采用正确口径。

### 健腹轮引入即遇动作顺序问题：核心真实上限未被测出（8月19日新增）

结论：核心在健腹轮上的真实上限尚未被测出。8/19首次执行（跪姿，推出角度约60-70度，3组×6/7/6次）时，限制因素是右侧肩后束酸胀而非腹部力竭；8/21改正执行技术后，当日由3组19次增至4组31次（+63%），且当日核心预疲劳程度更高（深蹲、硬拉、髋外展均已完成）——核心更累却做得更多，瓶颈已从肩转移至核心。压力现集中于腹直肌与下腹、腰椎一带，与预期机制一致。技术要点：推出阶段躯干须跟随手臂前移，全程锁定肩角（视线与轮子平行）。只把手臂伸出而躯干不动，会让肩在末端屈曲位做等长承载，承担本该由核心完成的抗伸展工作——8/19的右肩酸胀即出于此，推出60-70度已属肩关节末端屈曲承载的深位区间，是肩袖与后束最易受损的位置。风险判据：推至最深位时若出现下背塌陷感或酸痛，视为核心圆柱失稳、行程过深，立即回退行程。次要监控保留三项：肩前侧或深处锐痛、外展弧中段疼痛、夜间侧卧压痛，出现任一项即撤下该动作。弥散性乏力的判据是时程而非强度——24-48小时消退属正常疲劳，超过72小时不退或伴随外旋无力，才按肩袖问题处理。

### RMSSD与SDNN比值：三段式认知修正（8月15日）

结论：RMSSD/SDNN 比值反映的是信号的自相关结构（变异集中在逐搏级高频震荡、还是含慢速漂移成分），不是"哪个自主神经分支更活跃"。本人的该比值基线未知，不作判断依据，仅作记录追踪。核实依据：Nunan et al. 2010 系统综述（21438名健康成人，经 Shaffer & Ginsberg 2017 收录）给出5分钟短时程常模为 SDNN 50(16)ms、RMSSD 42(15)ms——群体均值是 SDNN 高于 RMSSD。短时静息记录中 SDNN 的主要来源同样是副交感介导的 RSA；只有当 ULF/VLF/LF 等频段功率大于 HF 时才对 SDNN 贡献更大，而 LF 对 SDNN 有显著贡献是24小时记录的特征，不能套用到5分钟静息记录上。判读注意：只看差值而不看基线走向会选错参照系。8/13至8/15比值由0.98降至0.91，看似"倒挂加深"，但同期 RMSSD 与 SDNN 都在大幅上升（75.83→98.36、74.28→89.89），实际是 RMSSD 涨得比 SDNN 快，不是 SDNN 本身出问题。

### HRR口径变更：等峰值法 → 标准停表法（8月15日）

背景：手动1分钟 HRR 的前六点（7/30、8/4、8/6、8/9、8/10、8/13）经追问确认，计时起点均为"心率因惯性上冲至峰值的那一刻"，而非标准定义的"运动停止的那一刻"。该口径与文献常模（Cole 1999 一脉）不一致，此前得出的收敛带22.4-24.7%及8/9的30.2%离群点，均只在自身序列内部可比，不可与外部常模对照。8/15起改用标准口径：停止运动瞬间即计时，与停表动作同步完成（理想做法是同一手同时按停手表与计时）。

两套口径不可混用、不可换算比较（按第十节跨口径禁令处理）。7/30-8/15 六点冻结为"旧口径·等峰值法"独立序列，仅供历史参照；8/15之后为"新口径·标准停表法"独立序列，另行起算。采样条件：新口径只在收尾即停的课上采集。"从有氧稳态直接停表"与"从接近努力上限收尾停表"之间存在生理差异，归一化只消去起始心率的量纲，消不掉这个差异，故场景不符时不勉强补点，附录C的 hrr0/hrr1 留 null。手表给出的2分钟值按录入纪律②一律不入库，两条序列均不接收。

新口径现有四个样本：8/22 19.0%（当日气温29℃，热应激拖慢心率回落，不解读为恢复能力下降）、8/23 23.1%、8/27 23.5%、8/29 24.8%。四点落在同一窄带内，样本量仍不足以正式建立收敛带，但趋势已足够稳定，可作日常参考区间使用（约19-25%）。8/22与8/23构成一组几乎受控的对照：两日均心率仅差1bpm（135 vs 136）、爬升接近（63.7m vs 61.2m）、同为 React、路线相近，主要差异是气温——由此确认8/22那个偏低的降幅可归因于热应激，而非恢复能力下降。收敛带的验证路径已于8月20日关闭：不再为积累样本而刻意在课末安排冲刺收尾，也不再提醒掐表；顺手测了就照常记录，未测则留 null。口径定义与采样条件在记录时依然适用。

### 左侧信号线：四条同侧观察的归集（8月13日建立·观察项，未确证）

四条被动观察的共同点只有"都在左侧"这一项，故建为观察线而非结论：①8/9跑步左右平衡50.5/49.5，华为标注 Fair symmetry–Leaning left，为近期首次跌出 Good，且同日热身段仍为 Good、仅主课出现，8/10即恢复50.0/50.0；②8/12腿日深蹲热身左髌腱弹响，热开后消失，无痛；③8/13左股外侧肌单侧 DOMS，右侧无任何感觉——双侧动作后出现单侧 DOMS，通常意味着实际负荷分配不对称；④8/13有氧课冷启动 PAP 冲刺时左膝股外侧肌与髌骨连接处不适，后半程进入稳态后消失。四条的层级并不相同（步态指标／组织信号／训练量分配信号／髌股关节轨迹信号），不强行拼成一条因果链。但存在一个能同时覆盖它们的上游候选：左侧髋部稳定性（尤其臀中肌）偏弱→下蹲与跑步时膝盖轻微内扣→身体调用内收肌与股四头代偿控制轨迹→股外侧肌张力升高→髌骨轨迹外偏。该候选目前无直接证据，仅作待查。8/12弹响的48小时观察窗已走完且为阴性（膝盖骨下方按压、下楼梯、蹲下、久坐起身四项均无痛），弹响定性为良性、非病理，符合15周未做深蹲后复训初期的预期现象，不再单独观察——但该阴性只对"髌腱本身有无损伤"这一问题有效，不能据此撤销上游的稳定性假说。

首个功能性实证（8月24日）：硬拉冲 PB 至70kg时，左膝出现明显支撑不住、左大腿感受到"维持不住张力"，主动终止上举，无痛感，训练后及次日均无痛。与前四条的性质不同——那四条均为被动观察，本条是负荷下的功能表现，且高度可复现（触发条件明确：接近1RM的髋主导大重量）。硬拉是髋主导动作，膝关节本应仅承担稳定角色，其率先失守提示问题更可能在髋膝稳定链（臀中肌、股四头肌等长控制）而非拉力本身，与深蹲传力链中膝内扣的机制同源。处理：因无痛且为主动终止，判定为训练安排问题而非伤病，不需就医。硬拉暂缓冲击新 PB。新增单侧诊断工具——保加利亚分腿蹲，自重或轻负荷，双侧做到力竭记录次数差，每周一次，作为诊断工具而非训练量；左右差2次以内属正常，4次以上需专门处理该侧。若确认左侧偏弱，处理方式是把髋外展改为单侧做、左侧多做一组，改的是上游而非患处。

衍生的操作规则（8月13日）：DOMS 期不做冷启动 PAP 冲刺。8/13的触发组合为"腿日次日＋左股外侧肌单侧 DOMS＋冷启动冲刺"三项叠加——股外侧肌本就是把髌骨往外拉的主要肌肉，DOMS 状态下张力更高，冷启动又缺乏温度带来的组织顺应性，冲刺则瞬间放大负荷。要做冲刺则先跑10分钟热开再加速。

### 右肩问题：晨起旋前位疼痛，机制推断与训练调整（8月20-24日累积，8月24日整理）

症状：右肩外展20-30度位做前屈动作时疼痛，晨起最明显但一整天均有；前臂旋前（手心向下）位诱发、旋后（手心向上）位完全不痛；被动活动不痛、活动度主观评估正常；承重闭链位（平板支撑）亦可诱发，诱发后疼痛持续一段时间自行缓解。疼痛定位于肩前方深层。反复自测本身会激惹疼痛，自测频率已降至每周一次。机制推断（非诊断）：被动不痛＋活动度正常，倾向排除关节囊粘连类问题；旋后位不痛与肱二头肌长头腱病的典型方向相反，该假设已弱化；旋前位特异性疼痛（对应查体中 empty can/full can 测试原理）指向肩峰下间隙、冈上肌腱一类结构，机制上与肱骨内旋时大结节转至肩峰下有关。承重与非承重两种情境均可诱发，说明激惹条件比"特定角度的主动活动"更宽；疼痛自行缓解、非持续加重、非即刻锐痛不退，时程上符合肌腱/滑囊受激惹而非结构撕裂。背景线索：①8/7球局（3.5小时，停练两年后首次）后冈下肌（肩外旋肌）出现剧烈 DOMS 并持续6天，提示该肌群耐受度长期不足——外旋肌群的功能是上抬时将肱骨头下压稳定，能力不足会增加肱骨头上移、挤压肩峰下间隙的倾向；②8/17肩胸课前中束动作合计16组、后束（面拉）因器械故障0组，前后失衡可能放大该倾向。训练方向：面拉作为外旋肌群与后束的直接训练动作列为优先项；引体与高位下拉避开内旋位（改用中立或反手握，反手握二头肌参与更多、更接近正手发力模式）；跑步与下肢训练不受影响。当前限制项的具体解除情况以§2为准。已整理详细背景交接报告供其他医疗咨询渠道参考（2026-08-24），本节为该报告在档案中的存档摘要。建议完成专业查体确认。

### 体感与数据的一致性序列（8月13日归并·原分散于四条逐日）

操作规则：体感不是一个笼统的准或不准——一致时作确认、分离时以客观为准。出现不一致时，先判断属于哪一类：(a) 相对参照系差异（如天气红利未发挥）、(b) 真实输出变化、(c) 与生理负荷无关的即时因素（鞋、胃排空、睡眠惯性）。三类的处理完全不同：把 (a) 或 (c) 当成 (b) 会导致不必要的减量，反过来把 (b) 当成 (c) 会掩盖真实的恢复不足。判别的主要工具是同心率下的配速与功率是否同向变动：同向即 (b)；仅配速变而功率不变，多为坡度或参照系问题；两者皆无变化则应查 (c)。晨起主观状态只作记录，不单独进入当日训练强度决策，真正有裁决权的是§8既定的四级优先级。

八次记录的分类：①8/6 背离（体感差·数据好）——同心率下比8/4快5秒/km属效率改善，但按"阴雨降温段同努力约快1分钟/km"的既有修正，22°C小雨本应快得更多；体感捕捉到的是"相对于应有水平的欠缺"而非绝对退步，属 (a)，此时体感与数据都对，量的是两把不同的尺子。②8/8 一致向下——同心率慢13秒/km、触地持平、功率接近，是真实输出下降，主因前一日能量赤字，属 (b)。③8/9 一致向上——同心率快24秒/km且功率同步上升，为输出恢复，使②的归因闭环。④8/10 体感一般·数据无异常——均心率、负荷、恢复时间均为近期最低，客观面无疲劳证据，归因换鞋（React 体感拖沓）＋练前高脂延缓胃排空，属 (c)。⑤8/15 一致向上·本序列最强的一次——体感"像要飞起来"，同期睡眠8h24、评分90、Elite 98.36ms、睡眠HR 44bpm 四项客观数据同时最优，10.09km 跑出近期最低均心率134bpm。⑥8/16 分离·方向与⑤相反（体感差·数据最好）——全天持续"睡不醒"但认知功能正常、可正常学习，当日跑出7/26以来最低触地231ms、最高步频180spm；晨起惯性属认知唤醒度，与自主神经/心血管恢复是独立两套系统，属 (c)。⑦8/17 分离·主观优于客观——体感"还行"，客观为3h30睡眠、REM仅21分钟、全天打哈欠，当日未采信体感，判为清晨皮质醇上升叠加急性睡眠剥夺初期的交感代偿；本人提出的"像5/17比赛那天"类比不成立，5/17睡眠充足属真实状态良好，两者只是主观感受相似而生理基础相反。⑧8/18 一致向上——8h07、评分92、觉醒0次、呼吸质量100分、睡眠心率46、Elite 回落至常态带，主客观同向，此时体感具有信息量。

### 胸带勒感的候选归因（8月6日首现·8月10日收敛）

现象与结论：8/6起佩戴 Polar H10 时勒感明显增加，几日内调松近1cm仍觉紧，静息状态即勒，而戒指、袜口、晨起眼睑等其余部位均无变化。"只有这一圈紧"这一条同时削弱了全身性液体潴留类解释（糖原带水、钠负荷上升），最可能的是胸带弹性带自身老化收缩——H10 于7/4启用，一个多月的汗液与反复清洗正落在该窗口。次要候选是 DOMS 局部肿胀：8/7球局后背阔肌上部剧烈酸痛，而背阔肌正绕胸廓走行、直接压在胸带路径上。已排除肌酸（E-MASS 配料表无肌酸、无钠盐）与胶体渗透压方向（蛋白摄入升高理应使白蛋白略升、把水拉回血管内，预测与观察相反）。8/23胸带与爬升条件基本不变而症状消失，本条暂可放下。操作要点：当前松紧下信号质量仍为 Good、伪迹为0，说明松紧度早已够用。胸带过紧不提升信号质量，反而可能限制胸廓活动、改变呼吸模式而污染频域指标，与深慢呼吸污染属同类风险，不应为求信号而忍受勒感。

### 恢复时间算法的输入不止当日负荷（8月3日实测）

实测：8/3胸肩课负荷16、时长49分钟，恢复时间10h；7/31背日负荷26、时长长24分钟，恢复时间反而只有6h。负荷更低而恢复时间翻倍，说明手表算法纳入的是"进场时的恢复状态"（HRV、睡眠、既往负荷残余），而非仅当日训练量。8/3的实际背景是：8/2阈值课的20h恢复窗口尚未走完（要到8/3下午三点多才到期），且当晚睡眠仅5h30min——两项赤字被算法显性化为更长的恢复时间。

实操含义：恢复时间是一个复合读数，不能反推当日训练强度，也不能用来横比两堂课的难度；它的正确用法是回答"从现在起还需要多久"。同时这是"体感好≠恢复账目已结清"的一个客观印证——当日主观定位为轻松的动作打磨课、练完无疲劳感，算法给出的却是近期最长的恢复时间。

### 协同肌瓶颈与动作排序（8月5日提炼）

现象：背日中二头与三头先于背阔肌力竭，目标肌群刺激被协同肌的提前失败截断。

归因拆解：二头——引体主动肌为背阔肌、肱二头为协同肌，本次辅助配重下调（降至12kg，7/31最难档为19kg）使绝对负荷上升，二头作为该链条上截面积最小的一环故先到极限；当日垂直拉总计52次，累积容量本身偏高；热身那4个自重引体（60kg，难于当日任何工作组）有贡献但非主因（占比不足8%且组间100s恢复）。三头——引体为垂直拉，三头是伸肘肌，既非主动肌亦非主要协同肌（仅长头跨肩关节轻度参与），故其疲劳只能来自8/3胸肩日的残余，与本次热身无关。

排序规则：把最难动作放在热身位会形成"最难→较易→较难"的倒置强度曲线。正确做法是二选一——(a) 移至工作组之后作最大努力收尾，兼作纵向力量指标；(b) 前置但降至1-2个纯作神经激活，高强度低容量不引起疲劳，这才是 PAP 的正确用法。绕过瓶颈的补救：可在引体后补一组器械划船到力竭，避免背阔肌因协同肌失败而未练到位。

### 非训练负荷亦是负荷来源：日常活动与代偿性单侧化（8月8日新增）

实测依据：8/7打乒乓球约3.5小时（两年来首次，且对手为削球手，拉起下旋需大幅前臂内旋＋强烈向上摩擦），次日右侧持拍臂出现自上臂放射至肩胛骨的DOMS，并在肘、腕关节出现深层痛。初次归因仅指向球局时长，经用户补充两项后归因才完整：①备考期每日长时间写字——握笔是持续的低强度等长收缩叠加腕部小幅重复运动，前臂屈肌群与腕伸肌几乎全程紧张，该负荷单独存在时可耐受，但叠在已过载的链条上便不再有恢复窗口；②8/7左手拇指刀伤致几乎全部日常动作单侧化，右臂在非训练时间的基础负荷同步上升（此项为短期变量，左手愈合后自动消失）。判别支持：卸载（不写字、让手闲置）后痛感明显减轻，符合负荷相关的过度使用性疼痛；痛感为深层且说不清定点，指向关节囊／深层结构的累积负荷反应，而非肌腱附着点病（后者按压肱骨外上髁等点应可定点复现）。当日无发热，主观精力感反优于前一日，感染线索不成立。

机制定位：本条与§7"结缔组织适应vs肌肉适应"属同一族。两年未打球等同于该动作模式的耐受度已退至很低，一次性给到3.5小时是典型的负荷跳跃，与"停练14周后深蹲须从30-35kg起步"是同一条道理，区别只在于打球当时没有人替他计这笔账——训练有处方，娱乐没有。

实操启示：①本档案此前只记录训练负荷，本条为首个非训练负荷主导的案例——负荷来源应包括日常活动（写字、久坐用手）与代偿性单侧化，评估累积负荷时须一并计入，尤其在备考期这类日常负荷高度重复的阶段；②急性期不做拉伸至疼、按压揉搓或反复绕环，关节囊炎症期越动越明显，主要靠时间；③减负应作用在源头端而非患处：每写40-50分钟停5分钟让前臂完全放松、降低握笔力度、改用粗笔杆，比处理右臂更有效；④伤侧手在不需要精细捏握与用力的动作上应尽早回到日常分担，避免健侧长期独担；⑤观察窗口48小时，疼痛应逐日减轻；若三日后无变化，或出现关节肿胀、活动时卡顿弹响、晨僵超过30分钟，则超出过度使用范畴，须就医排查。⑥连带决策：背日及一切上肢力量课推迟至疼痛消失后（至少8/10之后）。

### 夜间多尿的候选机制与分离方案（8月11日新增）

现象：8月上旬起连续多日于05:00-06:00被尿意憋醒，尿量偏多，一度憋至排尿无力（后者提示膀胱过度充盈，逼尿肌被过度牵张后收缩力下降，属可逆但不应反复忍受——已确立"醒了就去，不躺着忍"）。

候选机制：①寒冷利尿（机制成立）——贵阳夜热致睡眠不盖下肢，后半夜降温使足部受冷，皮肤血管收缩→血液由外周回流核心→中心血容量上升→心房牵张感受器激活→抑制 ADH 并促 ANP 释放→尿量增加，与浸泡利尿同源。足部富含动静脉吻合（AVA）、是主要体温调节器官，血管收缩反应强于躯干皮肤，故"脚踝以下发冷即尿频"有生理基础；该假说另可解释两点既有观察：为何集中于日出前最低温时段、为何尿量偏多（ADH被抑制产生稀释尿）。②高蛋白渗透性利尿——尿素排泄须携水，蛋白由原水平升至136-150g，溶质负荷实增，可解释"液体量未变而夜尿出现"。③睡前液体时点（晚餐300ml＋睡前250ml集中于睡前3-4小时）。④钠负荷上升——近期以卤味与外食为主，钠远高于自制餐。四项目前未分离，按被动观察处理，不设专门的分离动作。配套观察指标（零成本、设备自动采集）：深睡连续性能否稳定在85以上、晨起睡眠惯性是否减轻。

### 频域指标在本人身上长期不可靠（8月11日固化）

实测依据：Elite 清醒静息测量的 LF peak 反复落在正常呼吸带（0.15-0.40Hz，对应9-24次/分）下缘或以下——8/4与8/8出现双峰重叠于0.15Hz分界、8/9为0.121/0.152Hz、8/10为0.094Hz、8/11为0.090Hz（约5.4次/分），而同期睡眠呼吸频率稳定在14-16brpm。清醒静息呼吸慢于睡眠呼吸在生理上属反常，合理推定为平躺5分钟测量过程中呼吸自然放缓，属稳定的个人测量特征而非偶发操作。须与8/1的污染样本区分：那次系刻意深慢呼吸，形态为 LF peak 0.059Hz 伴 SDNN 119.23ms／TP 8809ms² 同步虚高；8/11则 TP 3643、LF power 较前日降半，方向相反，不属失真。操作规则（固化，不再逐次判断）：本人的 Elite 频域指标（LF/HF、各频段 power、各峰频）一律不解读，只采信 RMSSD 与 Mean RR；仅当出现8/1那类"TP 与 SDNN 同步虚高"的形态时，才额外标注为污染样本并连 RMSSD 一并降级。

### 多信号交叉验证：区分表面矛盾（测量窗口效应）与真实疲劳信号（7月18日提炼）

两个对照案例揭示了同一个判断框架的两种结果。7/15：华为夜间HRV 67ms看似远低于晨起Elite RMSSD 88.11ms，但深睡/REM/呼吸质量/晨起心率全部正常——判定为整夜均值被入睡延迟(00:54)拖累的测量窗口效应，非真实疲劳，属于"单一读数异常，其余信号正常"的表面矛盾。7/18：华为夜间HRV 52ms跌破个人区间下限、觉醒次数2次(参考0-1，判定High)、LF/HF比值2.14（较前几日0.87、0.58明显升高）三项独立信号同向恶化，判定为真实疲劳信号（大概率源于7/17背日额外加练的递增硬拉组，中枢与下背部负荷被训练负荷算法低估），当日按弹性日"疲劳/DOMS明显"档执行快步走而非慢跑。操作规则：单一指标异常且其余信号正常时，优先排查测量窗口/协议差异等技术性解释，不轻易判定为真实疲劳；两个以上独立信号（夜间HRV、觉醒次数、LF/HF、深睡/REM结构、晨起心率等）同向变化时，判定为真实生理信号，按训练决策优先级（§13安全声明）降级处理。

### 晨起单点HRV偏低的机制与睡眠惯性（7月19日提炼·文献细节见附录B）

操作结论：晨起Elite单点RMSSD偏低、但华为整夜均值高位且睡眠结构／主观恢复正常时，优先判定为"测量时机落在睡眠→清醒过渡期"的技术性拖累，不判定为真实疲劳。两条独立机制支撑：①清晨睡→醒转换是全天交感激活转变幅度最大的时点，叠加昼夜节律因素（Boudreau 2012；Somers 1993）；②"睡不够感"是睡眠惯性即认知系统恢复滞后，与自主神经／心血管恢复是独立两套系统，起床活动20-30分钟自然消散，不影响训练决策（Tassi & Muzet 2000）。该判定有前提：须确认测量确实紧接觉醒。8/7的Elite 67.77经用户确认为按标准协议执行的干净数据，此机制即不适用，相应解释已作废，该低值转为观察项、不以另一个顺手的解释替换。三篇文献的完整核实要点与原作者自述局限见附录B。

### 晨起测量的污染源：急性应激唤醒 ≠ 普通睡眠惯性（7月20日提炼）

实测依据：7/20被电话叫醒处理要紧事，在主观"迷糊感消退后"才做晨起Elite测试，结果LF/HF飙至4.54（远超近期0.58-2.14区间）、RMSSD 55.15ms（近半月最低），华为侧同步显示轻睡68%(High)、觉醒2次(High)、评分80偏低。机制解释：被电话叫醒+处理要事是一次急性应激唤醒（触发肾上腺素/皮质醇），与"闹钟/自然醒后的普通睡眠惯性"是不同类别的生理事件；应激唤起的消退速度与睡眠惯性不同步，因此"等惯性消失再测"并不能得到干净基线，反而把一个更强的应激变量混了进去。实操启示：①晨起测量若前置了电话叫醒、争执、噩梦惊醒等急性应激事件，该次读数标注为"应激污染样本"，不作恢复状态解读，尤其不用来给前一日训练负荷做鉴定；②"主观迷糊感消失"不能作为"可以准确测量/身体已恢复"的判据——睡眠惯性属认知系统，与自主神经/心血管恢复是独立两套系统（承接上一小节结论）；③真实的恢复基线需等一次无突发应激的自然醒晨测。此条与"多信号交叉验证"规则配合使用：污染样本往往表现为多个交感相关指标（LF/HF、RMSSD、觉醒次数）同向异常，但这里的"异常"归因于测量情境的应激，而非训练疲劳，两者靠"当日是否发生急性唤醒事件"来区分。

第②类·光照致混乱式急性唤醒（8月2日）：环境漏光在日出时段将人唤醒，若伴随"以为已经睡过头/天已大亮"的短暂认知混乱，即便持续时间不长（本次28分钟），仍带有轻度肾上腺素成分，与电话/噩梦等经典急性唤醒同属一类，区别只在强度更轻。若测量紧邻唤醒事件、或当晚因此类事件导致觉醒次数/轻睡比例同步升高，则当晚夜间 HRV 均值判定为污染样本，不纳入趋势。第③类·热水澡致交感激活（8月16日）：热水浴使皮肤血管扩张、心输出量向体表重新分配，交感张力代偿性升高，该状态下的 RMSSD 不反映恢复水平。8/16晨起先排尿、后洗热水澡，5分钟内完成 Elite 测量，RMSSD 57.09ms，不仅跌破常态带下沿70.2ms，且低于±1.5SD离群线66.1ms。这一类有一个其余污染源都没有的自检手段：正常状态下坐姿与平躺的 RMSSD 应有明显差异（平躺更高，属体位反射），8/16两者数值相同，趋同本身即提示交感张力异常偏高。该判据不依赖与历史值比较，可当场判断，比"数值偏低"更可靠——数值偏低有多种成因，体位反射被压制只有交感张力一种解释。正反双例（8月18日补齐）：8/16为反例，先洗澡后测量得57.09ms；8/18为正例，同样洗了热水澡但测量在洗澡之前完成，得85.66ms，落在常态带中上部，读数干净。两日的差别只在操作顺序，不在是否洗澡——反例证明违反会污染，正例证明遵守即可规避、无需为此取消洗澡。晨起 Elite 的测量前置条件因此为三条：开灯之前、洗澡之前、不紧邻急性唤醒事件。判别缓冲：若该次测量距唤醒事件已有数小时，扰动通常已消退，可正常采信。按录入纪律④，污染样本照常进入附录C与基线计算，是否剔除在使用时判断。

### 睡眠与运动员：BMJ 2021专家共识（7月26日核实·完整要点见附录B）

来源：Walsh NP, Halson SL, Sargent C, et al. Br J Sports Med 2021;55:356-368。与本档案直接相关的可执行结论：①消费级腕戴设备不能准确测量睡眠分期，且系统性高估总睡眠时间与效率、低估觉醒次数——故华为的睡眠分期百分比参考价值低于其 HRV 趋势，支持"华为看趋势、Polar+Elite 看当天锚点"的两轨协议；②按 PSG 常模，本人深睡长期20-35%显著高于16%常模（利好），浅睡61%属典型值无需焦虑，REM 才是当前偏离常模最明显的一项；③午睡协议：≤30分钟、窗口13:00-16:00，若存在夜间入睡困难则应完全避免午睡；④Banking sleep：考前1-2周主动拉长睡眠，比考前一晚临时要求自己睡好更可靠；⑤忽略华为的"睡眠评分"与自动标红提示，只看档案自定义指标。该共识对象为精英运动员，且原文自述该领域证据质量总体偏差、明确反对"一刀切"——完整的十条要点、各条原文局限与 Orthosomnia 适用性评估见附录B。

⑩ 该共识的整体局限（原文自述）：研究对象为精英运动员，与本人（认真的业余训练者+备考学生）在训练负荷、跨时区旅行、赛前焦虑等方面差异显著，相关结论需打折；论文结论段明确指出该领域现有证据质量总体偏差，主因研究方法不一致、不可靠、缺乏有效性验证，其对同行的核心建议之一即为改进研究方法，故文中具体效应量数字均需保守看待；论文摘要明确反对"一刀切"，指出7-9小时统一建议对运动员未必最优，推荐个体化方案并应考虑运动员自己感知到的睡眠需求——此条支持本档案一贯的"用个人基线而非人群参考值判断"的方法论；另有一未解问题与本档案§7已有内容相关：睡眠延长是否会加重睡眠惯性并损害醒后表现，目前尚无定论，与Tassi & Muzet 2000关于睡眠惯性昼夜节律"尚无直接证据"的表述可互相印证——该领域至今存在争议。

### HRV的自主神经与情绪调节理论基础（7月21日五篇文献核实·完整内容见附录B）

定位（避免张冠李戴）：这五篇属于"HRV 作为自主神经／情绪调节指标"体系，回答的是"设备测的这个数本质是什么"，不是"该怎么练"；训练量决策仍属另一支文献（Buchheit／Plews／Le Meur 一脉），两个体系不可混用。四条落地要点：①前额叶抑制回路（Thayer 神经内脏整合模型）解释了心理应激何以能完全独立于肌肉疲劳压低 HRV（6/27母亲手术32ms、7/20电话应激）；②PPG 测的是脉搏间期＝心搏间期＋脉搏传导时间，应激会改变动脉弹性从而污染读数，故 PPG 静息可用、应激／冲刺状态不可靠，这是两设备偏离的第二重机制；③LF/HF 的"交感-迷走平衡"说已被否定，本档案"只看长期趋势、不解读单日值"的立场获权威背书；④静息自然呼吸下不对 HRV 做常规呼吸校正，但须监测呼吸落在9-24次/分内——8/1晨测因刻意深慢呼吸致 LF peak 降至0.059Hz（约3.5次/分），SDNN／TP／LF 同步虚高失真，当日频域指标整体不采信、只用 RMSSD，此规则此后在8/4、8/8的双峰重叠案例上重复适用。五篇的完整机制叙述、Porges 多迷走理论争议等关键局限见附录B。

##   8    偏头痛管理

反复头痛伴可逆视觉异常需由医生评估是否为偏头痛伴先兆。视觉先兆可有闪光、雪花样干扰或局部视野变化，常持续5–60分钟后完全恢复，可伴或不伴头痛。视觉皮层传播性神经电活动变化是主要机制解释之一，不是已证实的机械性神经受压。HRV不能诊断偏头痛、判断脑血管收缩或扩张，也不能排除急性眼科或神经系统问题。

历史症状保留：4月18日头痛7–8/10，同期HRV从100降至70ms、01:45入睡；用户报告布洛芬效果有限、冷水冲洗颈后及头部后自觉减轻约70%。这些是同日观察与主观疗效，不能确认血管扩张型病因或证明HRV因果，不据此规定冷水冲头治疗。

既往记录有起跑前2–3km头痛、随后自行消退；其病因未获医学确认，不能解释为已证实的脑血流过渡紊乱，也不能据此要求带痛继续跑。出现头痛伴视觉症状时停止运动；反复发作应至神经内科／头痛门诊评估，真正单眼症状还需眼科排查。

安全处置以症状为准，不设“HRV从80升至90ms”等医学预警阈值。9月29日晚仍6–7/10且反复加重，已建议当晚就医；9月30日确认未就医，视野正常、晨起头痛减轻约80%，上午冷水冲澡后进一步缓解，晚间跑后未加重但易累；10月1日晨起确认头痛消失、精力充沛，当天完全休息；未建立正式诊断。10月2日用户要求该事件翻篇，关闭主动追问及日常训练分析中的反复带入；历史症状记录保留。详见§6当日记录。突发最剧烈头痛、视力下降或持续视野缺损、无力、言语异常、意识改变、发热伴颈僵，立即急诊；不要自行驾驶。安静避光休息和正常补水不能替代所需评估。资料：NHS《Migraine》；American Migraine Foundation《Understanding Migraine With Aura》（2026-09-29核对）。

资料链接：https://www.nhs.uk/conditions/migraine/ ；https://americanmigrainefoundation.org/resource-library/understanding-migraine-aura/ ；https://www.mayoclinic.org/diseases-conditions/migraine-with-aura/symptoms-causes/syc-20352072 。

##   9    恢复、补给与营养策略

### 训练后混合补给方案（最终版）

| 成分 | 用量 | 作用 |
|---|---|---|
| E-MASS 增肌粉 | 1.5 勺 | WPC／WPI／WPH 三合一 ＋ MCT ＋ 后生元；乳清蛋白在胰岛素高位启动 MPS。8/2标签核查修正：原记"益生菌"不准确，配料为灭活型复合乳酸菌（TWK10／LP28／LDL557），灭活菌属后生元（postbiotics）而非益生菌——后者按定义须为活菌、靠定植起效，前者靠菌体成分与代谢产物起效，机制不同；标注的添加量≥0.1%指含低聚麦芽糖载体的整个固体饮料，实际菌体远低于此 |
| 即食燕麦 | 4 汤匙 | 缓释碳水，延长胰岛素平台期 30–60min（热水预泡至 40°C 以下） |
| 谷氨酰胺粉 | 1.5 汤匙 | 支持肠道健康（对肌肉恢复的额外益处证据较弱） |
| 葡萄糖粉 | 2 汤匙 | 制造即时胰岛素峰值 |
| 底液：牛奶 | 300 ml | 常温冲泡（超 60°C 热水致蛋白质变性） |
| 机制 | 葡萄糖即时胰岛素峰值 ＋ 燕麦缓释碳水（平台期 +30–60min）＋ 乳清氨基酸启动 MPS，构成「快慢双轨碳水 ＋ 快慢双轨蛋白质」完整结构。 |  |
| 时机 | 训练结束 30 分钟内最优。 |  |

### 运动中补给

三通道模型：肌糖原/血糖/电解质同时维持。比赛日能量胶×3（第7-8km、第13-14km、第18-19km），每颗配水服用。节奏跑首选低渗电解质粉。红豆馅面包在节奏跑中引发过肠胃应激，避免。

### 营养禁忌（已实测验证）

| 禁忌项 | 规则 | 实测依据／机制 |
|---|---|---|
| 酒精 | 完全规避 | 300ml 啤酒致深睡 16% → HRV 跌 3ms |
| 咖啡因 | 14:00 后禁 | 绿茶 ＋ 白巧致 HRV 跌至 56ms |
| 高脂食物 | 睡前 3h 禁 | 延缓胃排空 |
| 空腹有氧 | 超 30min 须进食 | 外胚型糖异生风险 |

### 大容量训练后恢复协议

0-30分钟：葡萄糖+香蕉。30-60分钟：冷热水交替冲下肢（血管泵效应）。睡前蛋白质优选酪蛋白（牛奶固体蛋白），消化慢覆盖夜间修复。

### 每日膳食计划（8月2日制订·v1.0）

制订背景：8月2日核查发现，当时实际每日蛋白质摄入估算仅45-50g，约为目标的45%，与§1"外胚型、热量盈余困难、肌肉量增长需要持续大热量摄入"的核心策略直接冲突。缺口本身远比"跑后蛋白粉舀半勺还是一勺"这个配比问题重要。本计划为解决该缺口而制订，适用于考研备考期（力量维持计划＋有氧为主＋每周一次阈值课）。

■ 每日目标量（2026-08-31 修订；按约 60kg 估算，体重基准未定，见§1）

| 营养素 | 目标 | 依据 |
|---|---|---|
| 蛋白质 | 100-115 g | 耐力＋力量混合训练需求区间。8 月 26 个记录日实测均值 121g，已在区间上沿之上，不再上调 |
| 碳水 | 休息日约 300 g／单课日约 425 g／双课日约 460 g | 由当日总热量减去蛋白与脂肪后倒推，不再单独设固定区间 |
| 脂肪 | 约 85／90／100 g | 占总热量 27-30%。由原 65-80 g 上调：原值与总热量目标不相容 |
| 总热量 | 休息日约 2400／单课日约 2950／双课日约 3200 kcal | 维持至微盈余。过渡值，由晨起体重滚动均值裁决，见表下修订说明 |
| 餐次 | 3 顿正餐 ＋ 1 个固定加餐模块 | 原依据「单餐吸收上限」作废：分餐对肌蛋白合成有边际价值，但不存在把蛋白截断在某个克数以外的吸收天花板。现行依据是执行成本——次数越少越不与自习时间冲突 |

2026-08-31 修订说明。原目标集在算术上不相容：蛋白 100-115g、碳水 330-390g、脂肪 65-80g，全取上限为 115×4＋390×4＋80×9＝2740kcal，全取下限为 2305kcal，整个区间够不到原定的 2900-3100kcal。也就是说，严格按宏量目标执行的人永远达不到热量目标，这不是执行偏差，是目标本身从制订日起就无法同时成立。记录端在 8 月 2 日制订时未做加总校验，已记入§7判断修订史。修订后三个日型的宏量与总热量互相自洽。

上表的绝对值是过渡值，不是已确证的需要量。维持热量从未实测，体重基准也未定（见§1），所有 g/kg 折算都建立在「约60kg」这个带 ±3% 不确定度的分母上，由它支撑的结论不能用确定语气。裁决办法是晨起体重的 7 日滚动均值：目标为每周增加 0.10-0.20kg；连续两周不涨，每日加 150kcal；连续两周每周涨幅超过 0.30kg 或腰围明显增加，每日减 100-150kcal。执行这条需要每日晨起体重的连续序列，而 训练数据集.json 的 32 个字段中没有体重字段，读数目前只散落在本档案的叙述里，共六个点。是否新增 bw 字段待用户决定：晨起流程本就含称重，该数据属零成本的被动观察，加字段能让热量目标由实测裁决而非继续估算。

执行上的主要缺口不在吃什么，而在白天的进食次数落在最容易被自习打断的时段。8 月 26 个有热量记录日的均值为 2705kcal，其中 19 天低于 2900；纯有氧日均值 2817、纯力量日 2736、8/31 力量＋有氧双课日只有 2525。改法是把加餐固定为一个不以饿不饿为触发条件的模块：每日 15:30 前后一次约 300-350kcal，在「250ml 全脂奶＋25g 坚果」「两片吐司＋25g 花生酱」「250ml 全脂奶＋50g 即食燕麦」中任选一种，前一晚装包。2026-09-03 材料到手，改用实拍标签口径：混合坚果 686kcal/100g（蛋白 18.2g、脂肪 64.8g、碳水 7.9g、糖 5.4g、钠 0，配料仅五种果仁、无添加糖油盐），25g 份 = 172kcal，较此前按通用值估的 150kcal 高 15%；Skippy 柔滑花生酱 611kcal/100g（蛋白 25.2g、脂肪 48.9g、碳水 16.0g、纤维 6.1g、钠 492mg），25g 份 = 153kcal、蛋白 6.3g、钠 123mg。花生酱配料表为花生、白砂糖、花生油、氢化植物油、食用盐——按含量降序白砂糖居第二，非无添加纯花生酱；标签反式脂肪标 0g，但国标允许每份 ≤0.3g 时标 0，"标 0"不等于零，标签本身无法回答此项，不作结论。两个可用配置的实算值：250ml 全脂奶＋25g 坚果 ≈ 332kcal；两片吐司＋25g 花生酱 ≈ 303kcal，均落在 300–350 区间。模块执行自 2026-09-04 起算。训练日在此基础上追加约 200kcal（香蕉＋花生酱，或晚餐加约 200g 熟米饭）；双课日再追加约 300kcal（午晚餐各加约 100g 米饭）。练后补给维持现行剂量不变，不再加粉或加乳清——缺的是总热量，不是蛋白。含糖饮料不作为增肌热量来源，其与晚间睡眠问题的重合见§6与§10。日型 A／B 中原有的上午加餐维持为可选项，本模块为固定项。

2026-09-01 立固定估算口径——8 寸（直径约 20cm）披萨整张：芝士型约 850-900kcal、蛋白约 38g；含少量肉类型约 900-950kcal、蛋白约 42g。依据为该直径常见薄底商品披萨成分表的区间，误差约 ±10%，无标签时按中值取用。9/1 当日两整张按 1800kcal／80g 计入。8/16 记录中"披萨为无标签估算"未定值，自本日起统一，不再逐次重估。

■ 日型A：跑步日（傍晚训练，最常见）

| 时段 | 内容 | 要点 |
|---|---|---|
| 早餐 07:30-08:30 | 牛奶500ml（从300ml上调）＋鸡蛋2个＋面包/馒头1个（约100g）＋南瓜子20g＋香蕉1根 | 目标P32g/C75g。鸡蛋从0加到2个是本计划最低成本的改动，直接补13g |
| 上午加餐 10:30 | 牛奶250ml 或 无糖豆浆400ml ＋ 全麦面包1片/小馒头1个 | 目标P12g。图书馆自习时最易跳过，但对"高频次进食"最关键，前一晚装包 |
| 午餐 12:00-13:00 | 一碗粉/面（大份）＋煎蛋×2（原1个）＋肉臊/牛肉/鸡丝一份＋青菜 | 目标P30g。加肉是单项最大增量（+15-20g）。贵阳粉面店均可加码，牛肉粉优于素粉 |
| 训练前 17:00-17:30 | 面包1个 或 香蕉1根＋温水；若为阈值课额外加葡萄糖粉20g兑水 | 对应§6 7/9已确立的空腹跑对策；§9禁忌"空腹有氧超30min须进食" |
| 跑后30分钟内 | E-MASS 0.5-0.75勺＋即食燕麦4汤匙＋谷氨酰胺1.5汤匙＋葡萄糖粉2汤匙＋常温牛奶300ml | 维持现行减量方案不改。8/2按实测标签重算（一勺60ml≈45g，粉体蛋白23%）：0.5勺=粉5.2g＋牛奶10g＋燕麦4g≈19g蛋白；0.75勺≈22g。依据ISSN立场耐力运动员建议每小时耐力运动额外补充约0.25g/kg蛋白（60kg×1h≈15g），两档均达标。注意：此前"半勺≈12-13g蛋白"的估算基于纯乳清粉假设（纯乳清蛋白占比70-80%），对本品不成立，已作废——本方案蛋白主要来自牛奶底液而非粉体。碳水约73g（粉15＋葡萄糖粉24＋燕麦20＋牛奶14），对糖原恢复合适不需减。牛奶须常温，超60°C致蛋白变性 |
| 晚餐 19:00-20:00 | 米饭1.5-2碗＋主蛋白（鸡胸/牛肉/鱼/豆腐约150g）＋青菜＋汤 | 目标P35-40g（§1硬性要求）。20:00前完成；高蛋白晚餐DIT效应叠加高温须睡前2-3h完成（§10） |
| 睡前 22:30 | 牛奶250ml | 酪蛋白消化慢覆盖夜间修复（§9） |

■ 日型B：力量日（上午训练）——与日型A的差异：①训练前：早餐提前至练前90分钟，或练前30分钟补香蕉＋葡萄糖水；②练后补给恢复§9完整配方（E-MASS 1.5勺），力量训练MPS需求显著高于跑步；③晚餐蛋白质仍需35-40g，不因上午已补过而减量；④睡前牛奶250ml在力量日为固定项而非可选。说明：原有"力量日晚上冲牛奶＋葡萄糖粉"习惯方向正确，建议扩展到每天执行，而不只是力量日。

■ 日型C：完全休息日——蛋白质目标不下调（维持100g+，肌肉修复在休息日进行）；碳水可下调至250-300g；取消训练前后补给，改为上午加餐＋下午加餐各一次，下午加餐建议酸奶1杯＋坚果一把（约P10g）。

■ 应急方案：无法坐下吃正餐时（8月8日并入，依据8/7执行偏离）——硬性前提：不得以E-MASS等训练补给粉充当正餐。该品碳水蛋白比约3:1，0.5勺仅得约15g蛋白却带入约50g碳水，蛋白效率低、碳水冗余，它是补给不是餐。8/7当日早、晚两餐均因赶时间以蛋白粉顶替，全天跌至约69-71g蛋白／1600-1800kcal，为计划执行以来首次未达标，缺口即全部来自这一模式。

可行替代（均无需坐下，图书馆与路途场景可用）：即食鸡胸肉——8月13日实购规格为35g装，每包仅约10.9g蛋白／50kcal／钠69mg（营养表按每100g标示：蛋白31.1g、脂肪1.5g、碳水1.0g、钠198mg，须按净含量换算，原记"一块约20g蛋白"系按100g规格估算，作废）；卤蛋两个约12g（可前一晚预置或便利店现买）；纯牛奶500ml约16g。据此修正配比：两包鸡胸(21.8g)＋500ml牛奶(16g)≈38g，方顶得上一顿正餐；单包只能算半个替代项。钠优势成立且不受规格影响：两包138mg，远低于两个卤蛋的600-800mg，亦远低于卤鸡腿套餐(整份逾1500mg)与拉面汤底(逾2000mg)。热量极低是使用限制：两包仅约100kcal，宜作加法补缺口，不宜替代主餐，否则热量会塌；若用于替代须同时补碳水。采购提示：藤椒味钠为198mg/100g，黑椒、奥尔良等口味通常显著更高，购前看营养表。若当餐同时需要供能（如后续有训练或长时间自习），须另配一份碳水——面包80-100g或香蕉一根，不要只补蛋白，这与§9既有"空腹有氧超30min须进食"及跑前方案一致。

个人固定规则（8月11日确立）：蛋白粉一律以牛奶冲调，不用水冲。用户汇报时若只写"X勺"，即按标准配方（300ml牛奶）计入，不再逐次追问。该规则源于一次计算口径不一致：8/7按标准配方计、8/10却按无奶计，致当日蛋白被低估至93g并误判为跌破下限，实为约106g、落在区间内。练前补给须为低脂快碳（面包或香蕉）：8/10练前食用120g沙拉酱面包（约450-500kcal且脂肪占大头），高脂显著延缓胃排空、消化道分流血流，为当日"体感一般"的第二因素（第一为React鞋体感拖沓）。力量日练前补给条款（8月15日补立）：§9原只规定"空腹有氧超30分钟须进食"，力量日无明确条款。8/14实测暴露该缺口——练前仅两根香蕉（210kcal、蛋白2.6g）即执行72分钟、容量3649kg的背日课，练后补给又在训练结束后才进，整个上午处于能量赤字，为当日下午乏力的第三项成因。规定：力量日练前应有碳水＋蛋白，而非纯快碳。可行组合为香蕉1-2根＋即食鸡胸两包（约21.8g蛋白）或＋卤蛋2个（约12g）；训练超过60分钟时尤其必要。该条与有氧的练前方案不可互相套用：有氧只需快碳供能，力量训练还需要氨基酸池。配套原则：应急方案是保底不是常态，连续两日以上启用即说明日程结构本身需要调整（如前一晚预置、整箱备货、把加餐装包），而非继续依赖临时替代。

■ 执行优先级（若无法全部执行，按性价比排序，只做前三条即可补上大半缺口）

| 序 | 措施 | 增量 | 累计效果 |
|---|---|---|---|
| 1 | 午餐加一份肉 | +15-20 g | 单项最大增量 |
| 2 | 早餐加2个鸡蛋 | +13 g | 前三条合计约+35-40g， |
| 3 | 早餐牛奶300→500ml | +6 g | 可从45g推至85g左右 |
| 4 | 上午加餐固定执行 | +12 g | — |
| 5 | 睡前牛奶每天执行 | +8 g | — |

■ 采购清单：必备（解决蛋白缺口）——牛奶每日1-1.05L建议整箱买、鸡蛋每日2-4个、无糖豆浆粉或即饮豆浆、原味酸奶、即食鸡胸肉（自习室与路途便携；8月8日由"可选增强"升为必备，为上文应急方案的第一顺位替代项。8月13日到货实测：35g装每包约10.9g蛋白、钠69mg，配料仅鸡胸肉、水、藤椒碎、食用盐，无磷酸盐／卡拉胶／大豆分离蛋白等保水增重添加剂。采购建议：每日用量2-3包时，35g装单位成本偏高，可改购100g装或整鸡胸）；已有继续——E-MASS增肌粉、谷氨酰胺粉、葡萄糖粉、即食燕麦、南瓜子；可选增强——无糖坚果。

■ 验证指标（4-6周后回看）：①体重应稳定或缓慢上升（§12中期目标63-65kg，但考研期以维持为主不强求增重）；②训练后主观恢复——DOMS消退速度、次日晨起体感；③HRV趋势——营养缺口修复后理论上有助于自主神经稳定性（观察项，非因果结论）；④力量表现——维持计划中的重量能否维持或小幅上升。

■ 估算说明：本计划的蛋白质/热量数字为基于常见食物成分表的估算值，非精确计量；个体差异、食材实际重量、烹饪方式均会造成偏差。执行标准以"是否达到餐次结构和主要食物量"为准，不必逐克称量。如需精确追踪，可用MyFitnessPal/薄荷健康记录1-2周，校准后凭经验执行。本计划不覆盖§9既有营养禁忌，酒精完全规避、咖啡因14:00后禁、高脂食物睡前3h禁、空腹有氧超30min须进食、节奏跑中避免红豆馅面包等条款继续有效。

■ E-MASS 增肌粉规格实测（8月2日照标签核查，Foyes／赴野士，GB 24154）：每100g含蛋白质23.0g、碳水化合物68.1g、脂肪1.8g、能量1615kJ、钠69mg，另含维生素B1/B6/C、烟酸、镁118mg、钙334mg、锌3.78mg、牛磺酸0.04g。标签自洽性校验通过（23×4＋68.1×4＋1.8×9≈380.6kcal≈1592kJ，与标称1615kJ在舍入误差内）。一勺=60ml≈45g。

由此得出的三条使用要点：①本品碳水:蛋白约3:1，是名副其实的"增肌粉"而非蛋白粉，任何按纯乳清粉（70-80%蛋白）估算其蛋白贡献的做法都会高估约3倍，历史估算已据此修正；②力量日1.5勺=67.5g粉→蛋白15.5g，加牛奶10g、燕麦4g合计约30g，碳水约104g、总热量约620kcal，落在力量训练后MPS最大化所需的20-25g蛋白区间之上，方案无需调整；③粉内已含四档碳水（葡萄糖→低聚麦芽糖→酶解燕麦粉→异麦芽酮糖，最后一档为低GI≈32的慢释碳水），外加葡萄糖粉与即食燕麦属重复叠加，但该重复有其功能——减勺数会同时减掉碳水，外加快慢碳水正好实现"降蛋白而保碳水"的解耦，故保留；若求简可改为"半勺＋只加葡萄糖粉"。

其他标签相关观察：脂肪仅1.8%属精瘦型配方，不触发§9"睡前3h禁高脂"；不含咖啡因（牛磺酸非咖啡因），故不受§9"咖啡因14:00后禁"限制，晚间力量课后可用；钠仅69mg/100g，几乎无电解质补充功能，夏季大汗后不可依赖本品补电解质；配料中"小麦肽"为不完全蛋白（赖氨酸偏低）但排序靠后、占比小，不影响整体蛋白质量评估；谷氨酰胺粉1.5汤匙（约10g）在成分检测上会计入蛋白质，但作为单一非必需氨基酸对MPS贡献极小，不应计入每日蛋白目标（与§9原有"对肌肉恢复的额外益处证据较弱"一致）。补给剂量的默认取值规则（8月16日补立，与8月11日"蛋白粉一律以牛奶冲调"同类）：用户汇报"标准补给""标准增肌粉补给"而未写勺数时，按当日日型直接取默认值——跑步日0.5勺（日型A已注明"维持现行减量方案不改"），力量日1.5勺（§9完整配方），不再逐次追问。该规则源于8/16的一次多余追问：当日已明示为跑步日，日型A对剂量早有规定，仍去问勺数，属未查档案而非信息不足，成本由用户承担。数值不一致修正（8月18日）：本节应急方案原写"0.5勺仅得约15g蛋白却带入约50g碳水"，与日型A中按实测标签的算法（一勺60ml≈45g、粉体蛋白23%；0.5勺=粉5.2g＋牛奶10g＋燕麦4g≈19g）不符——粉体本身在0.5勺下只提供约5.2g蛋白，15g是整杯（含牛奶底液与燕麦）的数字。这一错位会让"以蛋白粉顶替正餐"看起来没那么差：按正确口径，脱离牛奶底液单喝0.5勺粉，实得蛋白约5g而非15g，应急方案的硬性前提（不得以补给粉充当正餐）因此比原文所述更有必要。据此换算，力量日完整配方1.5勺≈粉15.5g＋牛奶10g＋燕麦4g≈30g蛋白、碳水约103g。睡前牛奶的规则冲突处理（8月17日实例）：日型B规定力量日睡前牛奶250ml为固定项，但当日前夜正因夜尿早醒且全天以"睡回去"为最高优先级，睡前250ml液体与该目标直接冲突，故主动偏离、未补。记为"依睡眠优先原则主动偏离"，不计入执行偏差。通则：日型条款之间发生冲突时，以当日最高优先级目标裁决，并在记录中写明依据，不默认按条款字面执行，也不事后补记为疏漏。外卖食品的重量口径（8月18日补）：外卖标注重量一般为成品重且常含酱料，同一份意面在"干重/熟重/含酱"三种口径下热量可差近一倍。处理办法：首次点某店某品时确定一次口径并记入档案，此后同店沿用，不逐次重估；口径未定前按熟重推断并标注不确定度。

##   10    睡眠管理

噪声管理：3M 1100泡棉耳塞（NRR 29dB）标准装备。

高温入睡：提前30分钟开空调。高蛋白晚餐DIT效应叠加高温，需睡前2-3小时完成。

睡眠债务清偿：连续不足后大脑优先保深睡+REM，产生"短睡高效"（4月28日5h44min→92ms，4月11日5h52min→87ms）。代偿机制不可持续。

午觉：有债务选90分钟完整周期（Waterhouse 2007 BJSM）；无债务需即时警觉选20-30分钟。

手机：睡前调入勿扰模式消除电话觉醒。

赛前失眠管理：重要节点前夜大脑赛前激活过度是正常现象（4月18日、4月26日、5月6日均发生），不需要焦虑——即使只睡5-6小时，ANS储备仍足够支撑比赛发挥。

##   11    赛后状态总结（5月18日）

| 挑战 | 状态 | 应对策略 |
|---|---|---|
| 有氧能力+比赛准备 | 就绪 | 比赛完成——净成绩1:28:05（4:09/km@164bpm）；触地215ms回归巅峰；糖原管理完整无撞墙 |
| 糖原管理 | 关键改进项 | 三颗能量胶方案验证成功——比赛全程无撞墙，较模拟赛（第15km撞墙）彻底解决 |
| 足底/跟腱 | 已解除 | 三层鞋型系统建立，连续多周无症状 |
| 心率回落 | 达标 | 27-33bpm稳定区间，达巅峰期水平（【7月30日标注】该数值系华为Watch 5的2分钟窗口平均算法值，非手动掐表1分钟值，与7/30起新建立的真1分钟口径基准不可直接横比，见§7 HRR统计口径辨析） |
| 偏头痛 | 监控中 | 现行处置见§8；HRV不能判断病因，头痛伴视觉异常需医学评估 |
| 碳板适应 | 完成 | 触地220-225ms接近巅峰215ms；注意力已转移至臀部送髋 |
| 减量期 | 进行中 | 完成——5月17日净成绩1:28:05，Sub-1:30达成 |

##   12    长期训练愿景

近期：5月17日安顺半马1:28:05（4:09/km·Sub-1:30达成，超出赛前目标6分钟）✅ 已完成；赛后执行正式乳酸阈值测试（跑道+Kinvara 13+双直线回归）和5km全力测试

中期：跑步：10km 33:00（VDOT≥65）→半马1:15（3:33/km）；力量：深蹲1.5倍体重（90kg）·硬拉1.5倍体重·引体自重完成；周跑量推至80-100km·引入双阈值训练·体重允许自然增长至63-65kg；

长期：跑步终极目标：5km 15:00(VDOT≥72·需VO2Max 70+·取决于遗传天花板)·全马2:30→2:20；力量终极目标：深蹲2倍体重(120kg)·卧推1.5倍体重(90kg)·硬拉1.8倍体重(108kg)；引入超等长训练+筋膜弹性训练·跑酷/空翻（需专业教练）；核心矛盾（7月10日修正为剂量依赖）：肌肥大导向的高容量训练与跑步经济性存在拮抗，但维持性质的重负荷低次数训练(≥80%1RM)对跑步经济性反而有小幅正向帮助(Llanos-Lagos 2024)，两者并非"根本性"对立；真正的选择点在于追求肌肉量增长时的训练容量与体重增幅，需在第二阶段VO2Max天花板评估后决定倾斜方向；阶段路径：①考研期维持→②考研后2年系统发展(5km 17:00·半马1:20·深蹲1.5xBW)→③第3-4年根据天花板选方向→④第4-5年引入超等长和跑酷

### 考研后专项转型结构（5km/10km主攻·极化训练框架）

方向：考研后转5km/10km专项，与5km 15:00终极目标同一条线。关键认知纠正——5km/10km的限制因子是VO2Max、乳酸阈值利用率、跑步经济性，不是无氧糖酵解容量（后者服务800-1500m）。因此不是"减有氧、加间歇"这么简单，而是结构问题。

极化训练原则（Seiler）：约80%低强度有氧+20%高强度，中间强度占比最小。有氧基础不是被间歇替代的填充物，而是决定能吸收多少高强度刺激的"容器"——基础量削减会同步拉低间歇质量与恢复能力，不是此消彼长。故有氧总量维持甚至略增。

目标结构：有氧基础（现LSD+React体系）维持总量作底盘 → 在其上分化三块：①乳酸阈值跑（提升阈值配速，如4:13-4:17/km可持续吃力强度）②真正的VO2max间歇（贴近vVO2max配速3:20-3:40/km、恢复更完整；区别于现在7×1000m@3:30/km这种阈值/VO2max边界课）③少量strides/坡道冲刺（提升神经肌肉效率与跑步经济性，几乎零糖酵解代价、恢复负债低，与有氧体系兼容性最好）。力量训练目标函数从增肌导向转为爆发力+弹性储能导向（呼应肌肉量与经济性拮抗认知）。频次提升须跟随足底/跟腱恢复信号，非简单排课加量。

##   13    训练安全声明

⚠ 安全声明　所有训练均在运动生理学原理基础上进行，通过HRV、睡眠、心率多维指标监控。生理指标与计划冲突时，优先避免伤病和ANS过度负荷。持续疼痛或功能受限时立即停止。

生病期间训练/恢复判断框架（7月23日提炼）：采用运动医学"颈部以上/以下"经验法则——症状局限颈部以上（鼻塞、打喷嚏、单纯咽喉不适、无发热无全身症状）可考虑低强度训练；症状涉及颈部以下（咳嗽、有痰、胸闷、发热、全身酸痛乏力）应完全停止，带病训练有极小概率诱发病毒性心肌炎等风险，且可能延长病程。恢复训练前自查清单：连续24小时无发热；咳嗽/咳痰基本消失（非"减轻"而是"没有"）；晨起（非靠体位/日间皮质醇撑住）症状基本消失；食欲完全恢复；以上全部满足后再等48小时缓冲期。首次恢复从极低强度（Zone 1下限、20-30分钟）开始，观察当天及次日反应，无异常再逐步回归正常课表。

个人训练档案  ·  v5.2  ·  2026年10月2日

### 判断修订史（记录端自查·8月31日归集）

本节记录记录端在分析过程中出现并已更正的判断错误。此前这些留痕分散在各逐日行内，随 §6 改为周志后集中于此。保留的目的不是追责，而是每条各自暴露了一类可复现的推理缺陷。数据本身的口径修正不在此处，归入 训练数据集.json 的 _calibration_notes。

倒果为因（8月25日）：用 8/25 的低值回头把 8/24 的 109.12ms 定性为"大负荷前夜的迷走饱和假象"。该定性不成立——109.12 测于 8/24 晨起，大负荷课发生在当日 18:40 之后，一个读数不可能反映尚未发生的训练。修正后：两个读数都真实，中间隔着一节课，不构成矛盾。

违规复用已降级的判据（8月25日）：论证 8/24 为伪高时援引"RMSSD>SDNN 即异常排序"，但该判据已于 8/20 由记录端自己降级为待考、不作判断依据（理由：SDNN 不在数据集字段内，无历史基线，无法确定基础发生率）。对不利数据启用、对其他情况不提，属双重标准。

时间线凭印象推断（8月25日，两次）：其一把尚未开始的休息日当作已发生，据此推断"症状对休息不响应"；其二把练后 22 小时说成 72 小时观察窗已走完并宣布结案。已立规则：涉及"过了多久/窗口是否走完"的判断，一律从记录的起始时间点实算并写出算得的数值。

误用手表自动值（8月27日）：将手表 2 分钟 HRR（162→114）当作手动 1 分钟值解读，据此判断为当日唯一负向信号，违反录入纪律②。实际手动值 162→124（23.5%），与前一次持平，不构成异常。

归因过早收敛（8月19-21日）：健腹轮首次执行时肩后束先于核心力竭，记录端归因为动作顺序造成的后束预疲劳；用户随后发现真正原因是执行技术（推出阶段只伸手臂、躯干未跟随，肩在末端屈曲位等长承载）。教训是在用户尚未描述完执行细节时就给出机制归因，容易锁定在错误方向。

量化目标未做加总校验（8月2日制订，8月31日发现）：§9每日膳食计划的三大宏量目标与总热量目标互不相容，全取上限仅 2740kcal，低于所定的 2900-3100kcal。该矛盾自 2026-08-02 存在至 2026-08-31，共 29 天未被发现，期间记录中的「热量未达标」有一部分是目标不可达造成的，不全是执行问题。发现路径为用户提供的外部 AI 分析，记录端在其上核对数据集后确认。教训是给出一组量化目标时须当场验算其能否同时成立，这与第十八条「估算须标注依据与误差」是同一类要求的两面：前者管误差，后者管自洽。

候选因素集漏项（8月31日记录，9月1日发现）：8/31 那次异常表现的候选因素只列了换鞋、气温、排精、有氧适应四项，未列当日上午的背日课——而那是全月唯一一个双课日，是当天最独特的特征。漏项导致其后的共线性判定是在一个残缺集合上做的。发现路径为用户提出"背部激活致摆臂舒展"这一第五候选。同日另有一处归因错误：记录端曾称左右平衡 bal 可反映摆臂对称性，实为触地时间的左右分配，属下肢指标，与上肢无关，是把一个字段的定义记错之后当作证据来用。教训是列候选集时应先问"当天有什么是别的日子没有的"，而不是从既有的怀疑对象里挑；引用字段作证据前须回查 _field_definitions 的原义。

用未陈述的状态补足事实空缺（9月2日记录，9月3日发现）：用户 9/1 发来两张商品页截图并说明"已下单"，记录端此后写成"坚果和花生酱都到位了"，把下单直接当成了到货，而运输这一段是自己填的。错误不止于措辞：据此得出的"卡住的不是材料"把连续未执行归因到执行意愿上，而实际上那几天材料根本不在手边，不构成"未执行"，只构成"不具备条件"——归因方向反了。与前七条的区别在于，这次被裁剪的不是证据而是事实本身：一个从未被陈述的状态被当作已知条件写进了记录，并立刻成为下一层判断的前提。教训是凡涉及用户处境的状态（是否收到、是否完成、是否仍在进行），只采信其明确陈述过的，未陈述即为未知，不得由相邻事实推定。

第八条的两次重犯（均发生于 9 月 3 日，距第八条写入不足一日）：其一，回答"手表睡眠 HRV 是怎么回事"时生成了一张双序列对比图，其中三十余个历史点是凭印象编的，只有末尾几个是真值——数据文件就在手边，未读取即输出，图已撤回。其二，看到坚果与花生酱到货照片后，未查看花生酱配料表即写下口径并称其为"纯"，实际配料为花生、白砂糖、花生油、氢化植物油、食用盐，白砂糖居第二。两次是同一个动作：事实可查而未查，用看起来合理的内容填补空缺；与第八条的区别仅在于第八条填的是用户处境，这两次填的是自己手上的数据和眼前的图片。教训是：凡可查证的，输出前必须实际读取——数据从文件里取，标签从图片里看，"看起来应该是这样"不构成依据。

「首次」与「最」字断言未经核对（9月10日全档核对）：用户指出「悬吊抬腿首次出现」有误——该判断来自数据集 flag 字段检索，而 flag 只记当天被讨论的事项，不是动作清单，用一个不完整的字段去论证「此前没有」，推理从根上不成立；同一来源写下的「正握首次」「无硬拉为背日首次」一并撤销。随后对 8/31 以来全部 flag 与 §6 各节逐条核对，凡带「首次／最高／最低／第几」的断言用脚本对数据集重算，发现硬错 6 处（蛋白首次落入区间——实际此前六日均在区间内；首次连续三日标准口径读数——8/26–8/28 已是；浅睡序列最高两处——8/6 为 76%；华为整夜近八日最低——8/28 更低；力量日峰值心率历史新高——8/21 持平），对照对象错 3 处（有氧心率前高、深睡第二低漏并列、深睡第四高实为第六），并列未标 3 处，来源超出数据集却称「记录最低」1 处，序列定义未说明 1 处，均已逐条订正并在原处保留订正标记。同一天另有两次日期实算未做（把两天后的 24km 写成「明天」），属已写进偏好的规则被违反。教训只有一条：凡「首次」「最」「第几」，写入前必须由脚本对完整字段核对一遍；字段不完整的（动作名、早餐分项、体重时刻）不得据以下「首次／最」的结论，只能写「记录中未见」并注明来源范围。

共同点　十条里有四条是同一个模式：先形成结论，再挑选或裁剪证据去支撑它——把时间线凑上去、把已降级的判据重新启用、用后发生的事解释先发生的读数。第六至第八条属另一类，都不涉及证据裁剪，但同样会让结论显得有依据：一条是根本没做校验，一组自己给出的数字互相矛盾了 29 天没被发现，且它比前五条影响更久，因为它被写进了每天执行的计划里；一条是候选集从一开始就不全，此后所有共线性判定都建在残缺集合上；一条是把一个从未被陈述的状态当作已知条件填了进去，下一层判断随即建在这个虚构的前提上。三者分别是算术自校验缺失、枚举不完全、事实空缺被自行补足。第九条不是新类型，而是第八条在写入后不足一日内的两次重犯，这说明"写进档案"本身不构成防护，真正的约束只能是输出前的一个硬动作：可查的必须实际去查。第十条是这个硬动作在另一类断言上的缺席：「首次」「最」是可以用脚本核对的，却一直凭前几天的印象写，全档核对出十四处。对抗办法有五条：把判据和口径写进数据文件本身而非留在叙述里，这样每次引用都必须面对它当初被写下时的完整条件；量化目标在给出的当场就要验算一遍；列候选因素时先问当天有什么是别的日子没有的；凡涉及用户处境的状态只采信其明确陈述过的，未陈述即为未知；凡「首次」「最」「第几」，写入前用脚本对完整字段核对，字段不完整者只写「记录中未见」并注明范围。

##   A    维持计划（力量训练）

🦵 腿日

| 动作 | 组数×次数 | 关键点 |
|---|---|---|
| 杠铃深蹲 | 4 × 8 | 主项，保重量，RIR 2-3 |
| 杠铃硬拉 | 3 × 6 | 主项，组间休息3min |
| 腿弯举 | 3 × 12 | 腘绳肌孤立 |
| 联动髋外展 | 3 × 15 | 臀中肌，跑步侧向稳定 |
| 平板+动态死虫 | 各 3 组 | 核心收尾（超集） |
| 面拉（优先） | 2-3 × 12-15 | 固定收尾 (28-32kg) |

🦍 背日（🌟 优先级最高：不可跳过或缩减）

| 动作 | 组数×次数 | 关键点 |
|---|---|---|
| 器械辅助引体 | 4 × 8 | 主项，从高辅助递增至低辅助 |
| 悍马划船(单侧) | 4 × 8 | 弱侧(左)先做，强侧跟随匹配 |
| 轻量RDL | 2-3 × 10 | 传统硬拉60-65%重量，背部等长刚性 |
| YTWL(上斜凳) | 2 × 各6次 | 1-2kg或空手，肩胛骨稳定黄金组合 |
| 单臂面拉(左侧) | 3 × 12 | 只做左手，专项矫正左右不对称 |
| 收下巴 | 2 × 10次 | 停5秒，深层颈屈肌激活，矫正头前倾 |
| 面拉（优先） | 3 × 15 | 固定收尾（背日加组至3组） |

🛡️ 胸日（胸肩合并，优先级最低，时间紧可压缩至30分钟）

| 动作 | 组数×次数 | 关键点 |
|---|---|---|
| 杠铃卧推 | 4 × 12 | 主项，胸肩合并期降重量，RIR 2-3 |
| 上斜推胸 | 3 × 12 | - |
| 器械推肩 | 3 × 12 | 三角肌前中束 |
| 侧平举 | 3 × 12 | 胸肩合并期固定保留，时间紧可缩至2组 |
| 面拉（优先） | 2-3 × 12-15 | 固定收尾 |

##   B    文献核实留档

本附录为8月8日档案瘦身时从§7迁出的文献核实全文，内容一字未删。迁出理由：§7的定位是"能反复用来指导未来训练决策的规律"，而这三块是支撑那些规律的参考资料，留在主线上会稀释决策密度。§7对应小节已保留结论索引与出处，需要查证原始核实要点、原作者自述局限时来此。维护提示：本附录只增不改；若某条文献结论被新证据推翻，修正应写在§7对应小节并注明日期，此处保留当时的核实记录，不做静默覆盖。

### 晨起单点HRV偏低的机制与睡眠惯性——三篇原始文献核实（7月19日）

背景：7/19出现与7/15方向相反的设备背离（华为整夜98ms高、Elite晨起单点68ms偏低），同时主观有"睡不够感"但身体DOMS已消失、疲劳减轻。经三篇原始文献核实，该现象有两条独立机制支撑，分别解释"单点HRV偏低"和"睡不够但不累"。

机制一·晨起测量卡在睡眠→清醒过渡期的一过性交感激增。① Boudreau et al. 2012（Chronobiology International, 29(6):757-768）是最贴合本场景的直接证据：72小时强制去同步方案分离睡眠-觉醒效应与昼夜节律效应，发现清醒相比小睡，LF/HF与LF功率显著升高、HF（副交感）显著降低、心率平均高6.5bpm；且LF/HF峰值恰在早晨、与唾液皮质醇峰值重合，清晨睡→醒转换是全天交感激活转变幅度最大的时点。这解释了晨起单点RMSSD为何特别容易被拖低——不仅是"觉醒"动作本身，还叠加清晨时段的昼夜节律因素。局限（原作者自述）：LF/HF非纯交感指标、仅反映交感迷走平衡；样本量13人、统计功效有限——与本档案"单日LF/HF噪声大、不单独下结论"一致。② Somers et al. 1993（N Engl J Med, 328:303-307）是方法学最硬的奠基证据（微神经图直接测交感放电，非HRV间接推算），证实觉醒刺激在睡眠背景下会引发交感激增（其主线发现为REM期交感飙升至清醒水平215%）；但属机制奠基，未直接测量"晨起单点HRV被拖低多少"这一具体数值。

机制二·"睡不够感"是睡眠惯性(sleep inertia)而非身体疲劳，两套系统独立。Tassi & Muzet 2000（Sleep Medicine Reviews, 4(4):341-353，该领域顶级综述，被引超450次）核实要点：醒来前的睡眠阶段是决定睡眠惯性强度最关键的因素——从深睡(SWS/N3)猛然醒来惯性最强、从N1/N2浅睡几乎无惯性、REM居中；正常8小时无睡眠剥夺时惯性一般不超过30分钟（Jewett 1999发现主观警觉度完全恢复可能需2小时）。这与本档案7/12"晨起主观40%→活动后80%"的恢复曲线在时间尺度上吻合。边界：该综述明确指出"睡眠惯性是否有昼夜节律尚无直接证据"，与机制一的HRV昼夜节律是两个独立机制，不可混为一谈。

操作结论：晨起Elite单点RMSSD偏低、但华为整夜均值高位且睡眠结构/主观恢复正常时，优先判定为"测量时机落在觉醒过渡期"的技术性拖累，不判定为真实疲劳；"睡不够但不累"是睡眠惯性（认知系统恢复滞后于身体），起床后活动20-30分钟自然消散，不影响训练决策。此结论与机制二的系统区分一致。

### 睡眠与运动员：BMJ 2021专家共识核实要点（7月26日新增）

来源：Walsh NP, Halson SL, Sargent C, et al. "Sleep and the athlete: narrative review and 2021 expert consensus recommendations." Br J Sports Med 2021;55:356-368. doi:10.1136/bjsports-2020-102025。BMJ运动医学专家共识，作者含Liverpool John Moores、澳洲天主教大学等多国机构。以下为与本档案直接相关的核实要点，含原文自述局限。

① 睡眠结构常模（PSG金标准）：年轻成年人7-9小时睡眠约含61%浅睡、16%深睡、23%REM；15岁青少年8-10小时约含57%浅睡、22%深睡、21%REM。本档案对照：华为的浅睡参考线设为<55%，比该文献常模更严格，61%浅睡按常模属年轻成年人典型值；本人深睡长期20-35%，显著高于16%常模（利好）；但REM近期多次落在8-12%（7/24=10%、7/26=9% Low），明显低于21-23%常模，而华为因参考区间设为10-30%而标注Normal——即REM才是当前偏离常模最明显的一项，与记忆巩固/情绪调节相关，对备考期意义大于浅睡百分比。重要限定：该常模来自多导睡眠图(PSG)，而本档案数据来自腕戴设备，论文表1明确指出此类设备不能准确测量睡眠分期，故两者不可直接横比，此对照仅用于说明"浅睡61%无需焦虑"，不足以反推分期数值的绝对准确性。

② 消费级可穿戴设备的系统性偏差（论文表1）：不能准确测量睡眠分期（除经专门验证）；系统性高估总睡眠时间与睡眠效率，同时低估觉醒次数与入睡后觉醒时间(WASO)；多数设备不公开算法、不提供原始数据；大量设备缺乏充分验证。本档案含义：华为的睡眠分期百分比，参考价值低于其HRV趋势（后者至少为连续量，前者是算法分类结果），进一步支持已有的"华为看趋势、Polar H10+Elite HRV看当天锚点"两轨协议。

③ 睡眠不足与呼吸道感染易感性：论文引用Cohen 2009等指出，习惯性睡眠<7小时增加呼吸道感染易感性，且睡眠不足会降低疫苗保护性免疫反应；另引Hausswirth 2014指出，存在过度反应(over-reaching)客观征象的运动员，上呼吸道感染发生率高于未过度反应者。本轮感冒(7/21晚起病)的回溯对照：起病前多夜睡眠不足7小时（7/17=6h40、7/20=6h57、7/21=6h51），入睡时间连续偏离23:00-23:30目标窗口；且7/17背日额外加练递增硬拉、7/18出现HRV跌破下限+觉醒High+LF/HF升高三线同向报警、7/19仍带残留疲劳完成含情绪性冲刺的10km。判定：受凉是明确的直接扳机，但"睡眠持续不足+训练负荷偏高+自主神经已报警"这一组合恰好构成文献描述的易感窗口，是比单一受凉更完整的解释。此为回溯性关联，非确证因果。

④ 傍晚训练与入睡延迟的结构性关联：论文指出傍晚(18:00-21:00)高强度训练/比赛通常伴随更晚的入睡时间、更短卧床时间与更少总睡眠；并指出核心体温下降或处于低位时最易入睡，体温上升或偏高时最难入睡。本档案对照：跑步固定18:00-18:30出发，而入睡时间连续两周稳定在00:01-00:42、无一日落入23:00-23:30目标窗口。推论（尚未验证）：训练时间安排可能是入睡时间长期偏晚约1小时的结构性原因之一，而非单纯自制力问题；若日程允许，将跑步时间前移可能比"晚上早放手机"更有效（后者已试过，结果为躺床挣扎近1小时）。论文另建议顺应个人时型(chronotype)安排训练与睡眠，并指出夜型者睡眠更易受困扰、早训会减少睡眠时长并升高训练前疲劳——本人作息偏夜型（稳定午夜入睡、8点左右自然醒），故清晨力量课未必是最优时段。备考期日程受图书馆开放时间约束，此条属可选优化项。

⑤ 午睡协议（Tool #3，可直接执行）：时长≤30分钟以避免进入深睡后产生睡眠惯性；最佳窗口13:00-16:00（对应午后警觉度低谷）；"咖啡午睡"为睡前即刻摄入150-200mg咖啡因再睡15-20分钟（咖啡因起效约20-30分钟，恰在醒时生效）；醒后接触明亮光线+洗脸可加速消除惯性；定闹钟时比目标时长多留约10分钟以计入入睡时间。关键例外：若本身存在夜间入睡困难，应完全避免午睡。

⑥ 咖啡因截止时间：论文引用一项涵盖58篇文献的系统综述，指出典型剂量咖啡因即使在睡前16小时摄入，仍对睡眠产生一致负面影响——延长入睡时间(SOL)、减少总睡眠时长与睡眠效率、减少慢波睡眠(深睡)、增加浅睡与觉醒。实操：16小时标准对备考期不现实，但可作为排查工具——若某日入睡异常困难，回查当日咖啡因摄入时间。

⑦ Banking sleep（Tool #4，考研可用）：在预期睡眠不足期之前主动延长睡眠可能保护表现；一项大学篮球运动员研究显示连续5-7周每晚卧床10小时改善了反应时、冲刺、情绪与罚球命中率；论文指出储蓄睡眠不必持续数月，即使1周亦被证明可改善表现，且其价值之一是缓解赛前焦虑（知道前期睡够，就不会因赛前一晚没睡好而慌）。迁移到考研初试：考前1-2周主动拉长睡眠，比考前一晚临时要求自己"必须睡好"更可靠（后者常适得其反）。局限（原文自述）：此类研究常缺对照组，且无法区分是"真正储蓄睡眠"还是"仅偿还既有睡眠债"。

⑧ 监测设备的心理副作用（Box 3第5条）：论文警示部分运动员会过度关注睡眠监测数据，反而增加睡眠焦虑并导致睡眠更差，引用Baron等2017年提出的"Orthosomnia"（为追求完美睡眠评分而产生的睡眠焦虑，本身成为失眠诱因）。本档案适用性评估（经7月26日讨论修正）：初次评估曾据此提示本人可能存在该倾向，但被有效反驳并已收回大部分——真正被数据焦虑支配者不会在HRV未崩、症状明确指向"应停"时仍连续两日坚持训练（7/23、7/25），本人模式为"数据驱动而非以数据为导向"，决策权始终在本人手上、有时压过数据与建议。保留的可用部分：论文建议实践者权衡监测利弊并有能力调整反馈方式——落地做法是忽略华为的"睡眠评分"与自动标红提示，只看档案自定义指标（HRV相对个人基线偏移、深睡连续性、觉醒次数），减少无关信息干扰。

⑨ 浅睡偏高的归因修正（7月26日讨论）：初次分析将本轮浅睡偏高主要归因于"华为阈值比常模严格"，被指出遗漏两个更近因的混杂变量——感冒期气道不适/夜间黏膜干燥打断睡眠连续性、贵阳夜间高温破坏既有热环境入睡适应（7/23已明确记录"有点热、挣扎近1小时方入睡"）。但反向核查发现：7/16轻睡61% High、7/20轻睡68% High，两次均发生在7/21晚起病之前，说明浅睡偏高在病前已间歇出现，非本轮感冒独有。修正后结论：本人存在一个偏高的浅睡基线（大概率与入睡时间稳定偏晚相关），感冒与高温在此基线上叠加了一层，三者共同作用。此修正不改变"无需为61%焦虑"的结论，但不能简化为单一的阈值问题。

### HRV的自主神经与情绪调节理论基础（五篇原始文献核实，7月21日）

背景与边界：应用户备考需要，核实了五篇HRV基础文献原始PDF全文（非二手转述）：Appelhans & Luecken 2006（Review of General Psychology, 10(3):229-240）、Porges 2007《The Polyvagal Perspective》（Biological Psychology, 74:116-143）、Thayer & Lane 2000《A model of neurovisceral integration》（Journal of Affective Disorders, 61:201-216）、Kreibig 2010《ANS activity in emotion: A review》（Biological Psychology, 84:394-421）、Laborde, Mosley & Thayer 2017（Frontiers in Psychology, 8:213）。关键定位（避免张冠李戴）：这五篇属于"HRV作为自主神经/情绪调节指标"体系，回答的是"设备测的这个数本质是什么、机制在哪、怎么测才准"，不是"该怎么练"。训练量决策仍属另一支运动科学文献（Buchheit / Plews / Le Meur一脉，本档案§7其他小节已在用），两个体系不可混用。本小节不推翻既有认知，而是给档案里若干分散的机制注脚补上统一的理论根系。

机制根系一·前额叶抑制回路（Thayer神经内脏整合模型，争议小、被脑成像反复验证）：HRV反映的是"前额叶皮层→中枢自主网络（CAN：前扣带回/岛叶/杏仁核/下丘脑→孤束核/疑核/延髓腹外侧区）→迷走神经→心脏"这条抑制性负反馈回路的完整性。前额叶通过该回路对心脏和杏仁核施加张力性抑制；抑制运转良好时执行功能/情绪调节/应激恢复更佳，回路被削弱（疲劳、担忧、急性应激）时交感"脱抑制"冒出、HRV下降。这条直接解释了本档案反复观察到的"心理应激能独立于肌肉疲劳压低HRV"（如6/27母亲手术32ms、7/20电话应激）——心理应激直接占用/削弱前额叶抑制回路本身，故可完全独立于任何外周肌肉疲劳去压低HRV。Kreibig 2010从情绪特异性角度佐证：情绪状态确有可测量的自主神经印记，故"心理应激污染样本"有实证基础而非主观臆断。

机制根系二·光电vs ECG的脉搏传导时间机制（补强既有"光电vs ECG测量差异"小节，Laborde 2017）：PPG（光电，华为Watch 5原理）测的是脉搏波到达外周的时间，即脉搏间期=心搏间期+脉搏传导时间（PTT）；ECG（Polar H10原理）直接抓R波，无此混入。关键：应激会改变动脉弹性→改变PTT→污染PPG读数，因此PPG在静息可用、在应激/冲刺状态下不可靠。这为本档案既有的"两设备在冲刺/回落瞬间偏离最大、稳态时接近"提供了独立于"算法平滑滞后"的第二重机制解释：不只是光电算法平滑，还有PTT在应激下被生理性污染。原文并给出RMSSD精度对照——胸带ECG对比金标准误差约2.16%，腕部PPG约17.49%，与本档案两轨并行协议底层精度依据一致。

机制根系三·LF/HF"交感-迷走平衡"说已被否定（补强既有Elite HRV解析规则，Porges 2007 / Billman 2013 / Eckberg 1997，Laborde 2017转述）：LF对阿托品（迷走阻断）极度敏感，阻断迷走可几乎消除LF——若LF为纯交感标志，不应被迷走阻断消掉；且LF与交感神经活动关系松散，交感与迷走呈非线性、非互反关系，单一比值无法干净表征"平衡"。Laborde指出约65%的HRV论文仍在错误地基于LF/HF下结论。据此对既有措辞做收紧（结论不变、机制叙述更严谨）：涉及7/20 LF/HF=4.54的解读，表述宜从任何"交感主导"暗示改为"一次强烈的自主神经扰动事件"，不指定具体通路；本档案既有"LF/HF仅看长期趋势、不解读单日值"的立场因此获得权威背书，继续保持。

机制根系四·呼吸不做常规校正（Laborde 2017 / Thayer 2011）：静息自然呼吸下不对HRV做常规呼吸校正——呼吸与HRV有共同中枢神经起源（脑干心肺耦合），强行减去呼吸影响会连带删掉真正关心的神经变异；但需监测呼吸落在9–24次/分（对应HF 0.15–0.40Hz）区间内，呼吸过慢（如慢呼吸<9次/分）会把变异推入LF频段、使HF不再等于迷走张力。本档案晨测采自然呼吸，与此一致；附带确认RMSSD受呼吸影响小于HF，故以RMSSD为核心锚点的选择在方法学上稳健。超短时长补充：Munoz 2015（N=3387）显示测RMSSD无需超过120秒，单次10秒标准ECG即可得有效RMSSD（多段取平均更佳）——仅对时域RMSSD成立，频域仍需≥1分钟。

实测案例（8月1日）：晨测时因sleep inertia未消退，用户主动进行了缓慢深呼吸，导致LF peak降至0.059Hz（约3.5次/分，远低于9-24次/分的正常呼吸范围），变异被人为推入LF频段，SDNN(119.23ms)/TP(8809.36ms²)/LF同步虚高失真，Elite App据此给出的"副交感异常升高、建议减量"提示不可信；RMSSD受呼吸影响较小，仍保持在基线中段，作为该次测量中相对可用的指标。操作结论：晨测前若有意放慢呼吸（无论是为平静情绪还是巧合），当日频域指标（LF/HF、LF peak、SDNN、TP）应整体降权或不采信，只用RMSSD参考基线位置。

关键局限与警示（按维护规则保留原文边界，不只写支持性结论）：① Porges多迷走理论在生理学界非定论——腹侧/背侧迷走二分、"社会参与系统"、RSA=纯疑核迷走输出等理论建构受过实质批评（最有力批评之一Grossman & Taylor发于同卷Biol Psychol 74）；其"迷走刹车/迷走撤除先于交感"等功能性描述可用，但演化等级类建构不宜当作已证事实。② Thayer与Porges在HF/LF解读上存在分歧（Thayer传统上倾向HF=纯迷走、有时谈LF/HF平衡；Porges论证LF亦迷走驱动、平衡说不成立）——本档案"LF/HF只看长期趋势"恰卡在两派分歧中间，为最稳妥立场，不因Thayer框架而回头重度解读单日LF/HF。③ "HRV越高越好"错误，五篇再次确认（Laborde举神经性贪食症患者因低代谢率反而HRV偏高为例），与本档案7/13"HRV升高≠恢复更好、功能性过度训练副交感异常偏高"同向——高HRV须结合睡眠结构/静息心率/主观体感联合判断，不孤立追高。④ 新角度（Park 2014，Laborde转述）：张力性（tonic，晨起基线）迷走张力会调节相位性（phasic，任务中）迷走撤除模式，即晨起基线水平影响当天身体应对训练刺激的调节方式——为"晨起HRV高则有余量吸收刺激"的决策哲学提供更精细支点，可作后续观察方向。
